### ISSUE TITLE
Automatic generation of controller tags

### ISSUE THREAD

**Issue by ejgreenwald** [springfox/springfox#2134] opened 2017-12-06 22:01 UTC
Similar to the issue discussed here: https://github.com/springfox/springfox/issues/1257 

The generated spec has a tag element that is generated based on the controller name:
MetaController becomes meta-controller with a description of "Meta Controller"

For example:

```
swagger: "2.0",
info: {..},
basePath: "/",
**tags: [{
name: "meta-controller",
description: "Meta Controller"
}],**
paths: {...}

```

I'd like to stop that auto-generation or at least create an overide with a plugin but I was hoping you could give some guidance. I tried using the OperationBuilderPlugin but the only tags I could access were the operation tags and not the api level tags.

Any help would be greatly appreciated! Thanks for your great work!

**Comment by dilipkrish** [comment] 2017-12-07 12:42
@ejgreenwald You can annotate your controller with `@ApiController(tag= {'Custom Tag'})` to override

**Comment by ejgreenwald** [comment] 2017-12-07 12:47
@dilipkrish thanks so much for your fast reply. I don't have the @ApicCntroller tag, i jist have @Api and then i can manually configure the tag name. Id like to remove the tag completely though.

**Comment by dilipkrish** [comment] 2017-12-07 13:00
Sorry My bad.. It __is__ the `Api` annotation.

**Comment by ejgreenwald** [comment] 2017-12-07 13:02
@dilipkrish but is there a way to get rid of the auto generated tag? Plugin? If i leave tags empty or set tag to "" it still generates a tag. My methods have tags and the spec would be totally fine without the auto generated controller tags. Thanks!

**Comment by dilipkrish** [comment] 2017-12-07 13:25
Yes there is, don't annotate your classes, and you could create an OperationBuilderPlugin that updates the tags yourself.

See here for an example
https://github.com/springfox/springfox/blob/11c3f2254d20a050964465262523c62747f589f0/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/SwaggerOperationTagsReader.java#L54-L62

**Comment by ejgreenwald** [comment] 2017-12-07 13:29
@dilipkrish I'm sorry to keep bothering you but i tried creating an operationbuilderplugin and i gave it the right order but it looks like the controller tags are already there in the context and I don't see a way to get rid of them.

**Comment by dilipkrish** [comment] 2017-12-07 13:35
Make sure your plugin order is set and it loads before the swaggeroperationsreader plugin has had a chance to run

**Comment by qianyan** [comment] 2017-12-26 09:02
@dilipkrish I think the problem is not just about operation tags. it is about global tags of each docket, which means that tags parsed from the controller simple class name are always displayed in global tags array of generated swagger file even we do override operation tags like `SwaggerOperationTagsReader`.

@ejgreenwald I make a workaround of this problem and I hope it would be a little helpful if you have the similar scenarios.

## scenario 1
```
@Api(tags="Inventory")
public class Foo {
    @ApiOperation(tags="Analysis")
    @RequestMapping(...)
    public String bar (...) { ... }
}
```
if you don't want `Inventory` or `foo` shown, only you need to do is to make Api level tags same as Operation level tags, here, `@Api(tags="Analysis")`.

## scenario 2
```
@Api(tags={"Analysis", "Other"})
public class Foo {
    @ApiOperation(tags="Analysis")
    @RequestMapping(...)
    public String bar (...) { ... }

    @ApiOperation(tags="Other")
    @RequestMapping(...)
    public String buzz (...) { ... }
}
```
if you have multiple tags in one controller, do the same as above.

And then write a plugin to handle 
```
@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1) // lower priority than SwaggerOperationTagsReader
public class DisableAutoGeneratedTagsPlugin implements OperationBuilderPlugin {
    ...
    @Override
    public void apply(OperationContext context) {
        Set<String> tasgOnController = controllerTags(context);
        boolean multipleTagsAtOneController = tasgOnController.size() > 1;
        
        if(multipleTagsAtOneController) {
            context.operationBuilder().tags(operationTags(context)); // replace controller tags with operation tags for redundant Api level tags declaration.
        } else {
            context.operationBuilder().tags(tagsOnController); // handle only one tag in @Api, that means all operations in this @Api are the same tags.
        }
    }
}
```
@dilipkrish I don't know why you think the custom tag plugin should **load** before. But in my point of view, the custom tag plugin should have lower priority than `SwaggerOperationTagsReader` and then it is able to override `SwaggerOperationTagsReader`'s  behaviour.

**Comment by ejgreenwald** [comment] 2017-12-26 20:15
@qianyan thanks for your workaround. Unfortunately it's not working for me. My goal is to not have the description autogenerated for the controller tags - I'm getting the name of the controller as the description. Trying your workaround didn't stop that...

**Comment by qianyan** [comment] 2017-12-27 00:53
@ejgreenwald did you have configured global tags as below:
```
@Bean
....
Docket docket = new Docket(DocumentationType.SWAGGER_2)
     .apiInfo(apiInfo)
     .tags(new Tag("Analysis", "analysis description"))
...
```
this can override autogenerated description of Controller while you tagged it as `Analysis`.

**Comment by dilipkrish** [comment] 2017-12-27 11:45
@qianyan 

> I don't know why you think the custom tag plugin should load before. 

You're right. It can load afterwards since tags does an update/replace.

https://github.com/springfox/springfox/blob/6b9cdd361fd44a3dc87fb080a792e988217ce4f9/springfox-core/src/main/java/springfox/documentation/builders/OperationBuilder.java#L246-L255

**Comment by dilipkrish** [comment] 2017-12-27 19:50
Thats awesome @ejgreenwald. Thanks for reporting back! Closing as answered

**Closed by dilipkrish** 2017-12-27 19:50 UTC
Labels: current, question
