### ISSUE TITLE
@EnableSwagger2 interfering with application configuration.

### ISSUE THREAD

**Issue by rycentious** [springfox/springfox#1708] opened 2017-03-08 00:29 UTC
Hello, I'm trying to integrate swagger2 with a spring mvc project (no spring boot) and am running into a configuration related issue that is causing build failure whenever I use the @EnableSwagger2 annotation. 

pom.xml

```
	    <dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.6.1</version>
		    <exclusions>
		        <exclusion>
		            <groupId>com.google.guava</groupId>
		            <artifactId>guava</artifactId>
		        </exclusion>
		    </exclusions>
	    </dependency>
	    <dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.6.1</version>
	    </dependency>
```

SwaggerConfig

```
@EnableSwagger2
public class SwaggerConfig {
    
    List<Parameter> listParameter = new ArrayList<>();
    
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build()
                .globalOperationParameters(listParameter)
                .apiInfo(apiInfo());
    }
    
    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("some service")
                .description("description")
                .build();
    } 
}
```

AppConfig.java (relevant parts)

```
@EnableWebMvc
@EnableTransactionManagement
@Configuration
@Import(<package goes here>SwaggerConfig.class)
@ComponentScan(basePackages = { "com.company.package1"})

@MapperScan("com.company.model.mappers")
public class AppConfig extends WebMvcConfigurerAdapter {


...
...
...

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }


```

When I attempt to mvn clean install, I get the following error

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.company.KmsClient]: Factory method 'kmsClient' threw exception; nested exception is java.lang.RuntimeException: java.net.MalformedURLException: no protocol: NotConfigured
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 105 more
Caused by: java.lang.RuntimeException: java.net.MalformedURLException: no protocol: NotConfigured
	at com.company.AppConfig.kmsClient(AppConfig.java:269)
	at com.company.AppConfig$$EnhancerBySpringCGLIB$$f5c52e6a.CGLIB$kmsClient$17(<generated>)
	at com.company.AppConfig$$EnhancerBySpringCGLIB$$f5c52e6a$$FastClassBySpringCGLIB$$6b97ed1f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
	at com.company.AppConfig$$EnhancerBySpringCGLIB$$f5c52e6a.kmsClient(<generated>)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 106 more
Caused by: java.net.MalformedURLException: no protocol: NotConfigured
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.company.KmsClient.<init>(KmsClient.java:125)
	at com.company.AppConfig.kmsClient(AppConfig.java:266)
	... 115 more
```

I've been able to track the issue to a particular property value that seems to be missing whenever the @EnableSwagger2 annotation is used, which in turn is causing the above exception. If I remove the @EnableSwagger2 annotation from SwagerConfig.java, the property in question is correctly injected into the appropriate @Bean method and everything builds fine. 

Again, this is a spring mvc application (i.e. no Spring boot). Following the lead of another issue I found in this repo, I elected to remove the @Configuration annotation from SwaggerConfig.java with no success. 

Any help would be greatly appreciated

**Comment by dilipkrish** [comment] 2017-03-08 04:00
Seems like its in your code.

Whats in `com.company.AppConfig.kmsClient(AppConfig.java:266)`?

**Comment by rycentious** [comment] 2017-03-08 05:50
It's a home grown kms client that expects a configuration object. The configuration object is constructed from values that are read in from a .properties file and injected as parameters into the enclosing @Bean method. The issue is arising from the fact that one of the injected parameters is somehow null when @EnableSwagger2 is used, but non null when it's commented out. The code runs and builds fine in the absence of swagger.

**Comment by dilipkrish** [comment] 2017-03-08 21:28
Ah I see... this is a duplicate of #1621. Should be fixed shortly

**Closed by dilipkrish** 2017-03-08 21:28 UTC
Labels: bug, duplicate

**Comment by ManamN** [comment] 2018-06-19 10:02
Hi Dilipkrish,

I have encountered the same problem firstly with 2.5.0 version, later I found this article and updated the version to 2.7.0 which has the fix. But still the same issue occuring. 
I wanted to create swagger JSON file for my RestApi application.My application is Spring boot+katharsis.
Could you please provide your insghts regarding this. Your help much appreciated.

**Comment by dilipkrish** [comment] 2018-06-19 23:41
Could you please try with 2.9.0 @ManamN

**Comment by ManamN** [comment] 2018-06-20 02:07
Thanks for the response @dilipkrish , I have tried with 2.9.0 version but still same issue.

My POM file has the following

		<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger-ui</artifactId>
        <version>2.9.0</version>
    </dependency>
----------------
Application.java file 
@SpringBootApplication
@EnableAspectJAutoProxy
@EnableAutoConfiguration
@EnableWebMvc
@EnableEncryptableProperties
@EnableSpringDataWebSupport
@EnableSwagger2

public class Application extends SpringBootServletInitializer {
	static final Logger LOG = LoggerFactory.getLogger(Application.class);
	
	public static void main(String[] args) {
	SpringApplication.run(Application.class, args);
	}
@Bean
	public Docket api() {
	    return new Docket(DocumentationType.SWAGGER_2)
	            .select()
	            .apis(RequestHandlerSelectors.basePackage("{basepackage}.resource")) //{bacepackage) is my package name
	            .paths(PathSelectors.any())
	            .build()
	            .pathMapping("/api")
	    		.directModelSubstitute(LocalDate.class, String.class)
	    		.genericModelSubstitutes(ResponseEntity.class)
	    		.tags(new Tag("Test Service", "All apis relating to Test Service"));	

	 }
//Other configurations like SpringApplicationBuilder for environment context levels

Katharsis controller class has the following

@RestController
@Import({ CustomKatharsisConfigV3.class })
public class KatharsisController {

	@Autowired
	private ResourceRegistry resourceRegistry;
	
	@RequestMapping("/resources-info")
	public Map<String, String> getResources() {
		Map<String, String> result = new HashMap<>();
		// Add all resources
		for (RegistryEntry entry : resourceRegistry.getResources()) {
			result.put(entry.getResourceInformation().getResourceType(),
					resourceRegistry.getResourceUrl(entry.getResourceInformation()));
		}

		return result;
	}}

Am I missing anything here? Please suggest.

**Comment by ManamN** [comment] 2018-06-20 04:06
We have used JSON API. Does swagger2 support JSON-API attributes for documentation? Please explain

**Comment by dilipkrish** [comment] 2018-06-21 11:36
@ManamN It doesnt support json-api out of the box and Im not sure if `Katharsis` is either. May need your help to figure out a custom configuration/set for it. Id recommend creating a new issue and provide a working example repository (not cut and pasted code.)

**Comment by ManamN** [comment] 2018-06-22 00:52
Yeah we figured out that it doesn't support. So we gonna use Katharsis/Crnk feature itslef which lists the registered resources in the browser. But somehow it is not working as of now, so working on it.

**Comment by dilipkrish** [comment] 2018-06-23 10:50
@ManamN good luck and do report back if you find something interesting.
