### ISSUE TITLE
Schema generator doesn't differentiate between package names for same name classes

### ISSUE THREAD

**Issue by tonisostrat** [springfox/springfox#790] opened 2015-06-12 09:10 UTC
For two different entities with inner embedded classes like so...
```Java
@Entity
public class Foo {

    @Embedded
    private Gob gob;

    @Embeddable
    public class Gob {

        private String value;

        private LocalDate from;
    }
}

@Entity
public class Bar {

    @Embedded
    private Gob gob;

    @Embeddable
    public class Gob {

        private String first;

        private Boolean active;
    }
}
```
... the generator does not see them as different classes and therefore generates a wrong schema:
```
Foo {
    gob (Gob, optional)
}
Gob {
    first (string, optional),
    active (boolean, optional)
}
```
&
```
Bar {
    gob (Gob, optional)
}
Gob {
    first (string, optional),
    active (boolean, optional)
}
```
Am I missing some sort of annotation/configuration line or is this a bug?

**Comment by dilipkrish** [comment] 2015-06-16 19:37
Closing as its a duplicate of #182

**Closed by dilipkrish** 2015-06-16 19:37 UTC
