### ISSUE TITLE
Multiple Dockets with different host names

### ISSUE THREAD

**Issue by gakat2012** [springfox/springfox#764] opened 2015-05-29 02:02 UTC
Is there a way to configure the hostname specific to each group (Docket)
For eg. 1) http://api-internal.com/service which uses basic auth 2) https://api.com/service uses oauth

Currently we can configure only one url via properties "springfox.documentation.swagger.v2.host". The swagger2Controller reads only this value.  How can i override this value based on different Docket

**Comment by gakat2012** [comment] 2015-05-29 03:34
I myself found the answer... I had removed the configuration springfox.documentation.swagger.v2.host . This identifies the dynamic hostnames.. Great framework though i see some issues in the JSON

**Comment by dilipkrish** [comment] 2015-05-29 04:32
> I had removed the configuration springfox.documentation.swagger.v2.host 

Not sure what that means. This library isn't meant to support docs hosted by different hosts. For that you have swagger-ui. The intent of that property is just so that the spec can represent the host name for the service as a whole.

**Comment by gakat2012** [comment] 2015-05-29 06:56
I meant because of that configuration springfox.documentation.swagger.v2.host=api-internal.com, the swagger ui "Try it"  option always going to this host... But i wanted this to be dynamic based on the url i sent via swagger ui... for eg ... http://somesite.com/?url=api-internal.com or http://somesite.com/?url=api.com

**Comment by dilipkrish** [comment] 2015-06-04 01:22
Hostname is an optional element of the swagger spec. Based on that, it doesn't seem like we'll fix this issue. The intended usecase is that the service client would override the host name when it invokes service operations.

Closing this for now.

**Closed by dilipkrish** 2015-06-04 01:22 UTC

**Comment by cbornet** [comment] 2015-09-11 12:51
Hello @dilipkrish, what if I have a backend server behind a reverse proxy and the two following Dockets:
* group "admin" which has" /admin/.*" resources
* group "public" which has" /public/.*" resources

And the proxy maps:
* "https://admin.myDomain.com" to "http://localhost:8080/admin/"
* "https://public.myDomain.com" to "http://localhost:8080/public/"

Here it would be useful to be able to configure a per Docket host so that the swagger.json completely describes how to connect to the API.

**Comment by dilipkrish** [comment] 2015-09-11 13:12
@cbornet thats not a good idea. The host name is deprecated for a reason :wink: 

The idea is that the client needs to be bootstrapped with an entry point 

- `https://admin.myDomain.com/v2/api-docs` -> will have /admin relative to your main url.   

and everything else (paths) is relative to the entry point. Makes client url derefencing more reliable.

**Comment by cbornet** [comment] 2015-09-11 14:09
But what if I want to send the spec by mail or use it to generate client code, static doc, ... ?
Also, it seems that by default springfox renders "host" : "http://localhost:8080" whereas per your comment it would probably be preferable to not render the "host" field at all.

**Comment by cbornet** [comment] 2015-09-11 14:25
Same reasons as #689 and https://github.com/springfox/springfox/issues/236#issuecomment-37798411

**Comment by cbornet** [comment] 2015-09-11 14:29
Also my comment above on how the host is rendered is not true : springfox uses the info from the HTTP request but as the comment on #236 explains, it can be masked by proxies.

**Comment by cbornet** [comment] 2015-09-11 22:26
@dilipkrish If you re ok, I can work on a PR to add a method in the Docket to force an host that yoyu can use or not depending on your use case.
The priority of host determination would then be Docket -> conf file -> HTTP request

**Comment by dilipkrish** [comment] 2015-09-11 23:15
At first thought adding support for a deprecated feature in the spec doesn't seem like a good idea. 😕

**Comment by cbornet** [comment] 2015-09-12 08:53
I can't find where it is said that the host is deprecated in the spec. Do you have a link ?

**Comment by dilipkrish** [comment] 2015-09-12 12:30
> I can't find where it is said that the host is deprecated in the spec

@cbornet You're right. Sorry 😞, sometimes cognitive biases kick in.

My only argument against doing this is that [host name is optional](https://groups.google.com/forum/#!topic/swagger-swaggersocket/ZGYTzP0DCNM). IMO, we should avoid setting it to a value if we can, but I can certainly see your point. May be create a `hostNameOverride()` method in `Docket`?

**Comment by cbornet** [comment] 2015-09-12 13:49
OK. I will do the PR. Can you reopen this issue ?
As for the fact that host is optional, maybe the default should be to not render it at all and have an activation method in the docket.

**Comment by dilipkrish** [comment] 2015-09-12 13:58
Hey I think there is a simpler fix for this than modifying the docket. Let
me get back once I'm in front of a computer.

**Comment by dilipkrish** [comment] 2015-09-12 14:33
there is already a [host name override](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L51) that you can set up via a property. That should work I think.

**Comment by cbornet** [comment] 2015-09-12 14:39
But it doesn't allow per-Docket configuration

**Comment by dilipkrish** [comment] 2015-09-12 14:47
Do u want to chat about this when you have some time over gitter (not right now :)). At the cost of sounding like an opinionated prick, It doesn't seem like this feature belongs in the core library, but I'd like to hear your arguments for it.

**Comment by cbornet** [comment] 2015-09-12 15:19
No problem. I don't know gitter, how do I find you ?

**Comment by dilipkrish** [comment] 2015-09-12 16:04
Its on the main github page. But [here is a link](https://gitter.im/springfox/springfox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) anyways

**Comment by cbornet** [comment] 2015-09-15 08:17
@dilipkrish I sent you a PM on gitter.
Also I have a related issue : I cannot configure springfox to set the "schemes" field to ["https"]. I think springfox never sets this field which is fine for online use cases since in that case, the scheme used to access the Swagger definition is to be used by the client but for offline usage (static doc, autogen'ed clients) this is an issue.

**Comment by dilipkrish** [comment] 2015-09-15 12:51
Sorry I've been a lil busy. Let me take a look and get back in a bit

For the schemes please create a separate issue with steps to reproduce, examples or even better a failing test.

**Comment by cbornet** [comment] 2015-10-15 14:39
Just founs out that there is a ```protocols()``` method for the Docket that should do exactly what I need for the schemes field.
