### ISSUE TITLE
[Question] Is springfox supported for Spring Web Flux?

### ISSUE THREAD

**Issue by balajeetm** [springfox/springfox#2154] opened 2017-12-16 16:20 UTC
- Spring fox 2.7.0

 - Question. Is springfox supported for Spring Web Flux and Spring web reactive? Will it work without Servlet API?

**Comment by dilipkrish** [comment] 2018-01-03 05:41
It is currently not supported, but the plan is to support it.

**Comment by balajeetm** [comment] 2018-01-08 15:06
Thanks

**Comment by o-l-o** [comment] 2018-03-02 13:51
Do you already have any concrete plans regarding Web Flux support? (some release dates, etc.)

**Comment by dilipkrish** [comment] 2018-03-05 11:27
April 1st the plan is to release 2.9.0. The last release supporting jdk versions prior to java 8. There are already a couple of PR's to support webflux that provide support for it, post that

**Comment by o-l-o** [comment] 2018-03-05 12:36
Thank you very much for the answer

**Comment by jivimberg** [comment] 2018-05-17 15:19
I believe this is the issue you want to subscribe to: #1773

**Comment by dilipkrish** [comment] 2018-08-18 14:53
Closing as a Duplicate of #1773

**Closed by dilipkrish** 2018-08-18 14:53 UTC
Labels: duplicate
