### ISSUE TITLE
Api key input missing in swagger ui after upgrading version to 2.6.1

### ISSUE THREAD

**Issue by prajapatkiran** [springfox/springfox#1804] opened 2017-05-08 19:04 UTC
I have a spring boot application which uses swagger. The project runs absolutely fine in swagger version 2.5.0. I had to update the swagger version to v2.6.1 to get @ApiIgnore working for some new requirement. After I upgraded the version I dont see api_key input field in swagger-ui.
Below is my project configuration:

I tried with both 2.6.1 and 2.7.0-SNAPSHOT. Here are the dependencies 
pom.xml

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.7.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.7.0-SNAPSHOT</version>
        </dependency>
<img width="1429" alt="swagger-ui" src="https://cloud.githubusercontent.com/assets/19982364/25820340/f0e71c36-33fe-11e7-97df-bda2eaa3a1c9.png">

SwaggerConfig.java

    @Bean
    public Docket newsApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("some.package"))
                .paths(PathSelectors.any())
                .build()
                .pathMapping("/")
                .produces(Sets.newHashSet(APPLICATION_JSON_VALUE))
                .consumes(Sets.newHashSet(APPLICATION_JSON_VALUE))
                .directModelSubstitute(LocalDateTime.class, Date.class)
                .directModelSubstitute(OffsetDateTime.class, Date.class)
                .directModelSubstitute(Instant.class, Date.class)
                .directModelSubstitute(HttpStatus.class, String.class)
                .apiInfo(apiInfo())
                .useDefaultResponseMessages(false);
    }
    @Bean
    SecurityConfiguration security() {
        return new SecurityConfiguration(
                null,
                null,
                null, // realm Needed for authenticate button to work
                null, // appName Needed for authenticate button to work
                BEARER,// apiKeyValue
                ApiKeyVehicle.HEADER,
                AUTHORIZATION, //apiKeyName
                null);
    }

MvcConfig.java

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        super.addResourceHandlers(registry);
        //Adding swagger-ui webjars resources mapping so swagger-ui can be served
        if (!registry.hasMappingForPattern("/webjars/**")) {
            registry.addResourceHandler("/webjars/**")
                    .addResourceLocations("classpath:/META-INF/resources/webjars/");
        }
        if (!registry.hasMappingForPattern("/swagger-ui.html")) {
            registry.addResourceHandler("/swagger-ui.html").addResourceLocations(
                    "classpath:/META-INF/resources/");
        }
    }

**Comment by dilipkrish** [comment] 2017-05-08 21:37
The API key is configured via the security bean. Where you have `BEARER`, it should be `BEARER KEY....`

**Comment by prajapatkiran** [comment] 2017-05-09 14:44
That is something which we expect the user to enter in swagger ui. Bearer is the default value which shows up in the text box. My issue is that after changing the swagger version I dont see the input text box at all.
Please see snapshot below.

Before upgrade:
<img width="1430" alt="swagger-ui2" src="https://cloud.githubusercontent.com/assets/19982364/25856536/449014f0-34a4-11e7-8fda-e31ca797ef21.png">

After upgrade:
<img width="1429" alt="swagger-ui" src="https://cloud.githubusercontent.com/assets/19982364/25856606/7c0d675c-34a4-11e7-9ee7-e6938a946cba.png">

**Comment by JKI12** [comment] 2017-07-27 15:00
This too is happening to me, before version 2.7 the input box would appear, now the input box isn't no longer renders but the security is still applied

**Comment by dilipkrish** [comment] 2017-07-28 01:34
When we upgrade to 3.x of swagger-ui we'll address this

**Comment by KhushbooRathi** [comment] 2017-09-28 07:08
Hi,
We need this this oAuth functionality in our project. Will you please let me know when the stable version of swagger 3.0 is released?

Thanks,
Khushboo

**Comment by dilipkrish** [comment] 2017-10-02 10:33
Not sure at the moment. Sometime in the next couple of months

**Comment by ngawor** [comment] 2017-11-07 16:31
I am now hitting other swagger bugs due to do my inability to upgrade in order to keep token support.  This fix is very important to us.

**Comment by dilipkrish** [comment] 2017-11-13 13:57
@ngawor What fix are you referring to. This is a question targeting 2.6.1 version of this library.

**Comment by ngawor** [comment] 2017-11-13 14:04
@dilipkrish I have yet to find a version higher than 2.5 that will allow the Bearer token to be passed successfully.  Are you saying that exists?

**Comment by dilipkrish** [comment] 2017-11-13 14:33
@ngawor I'm not sure, so I trust your observation that this is an issue with 2.7.0. I'll change this ticket to a bug instead. I'd like some help/pointers on what needs to happen to get this resolved. A PR would be very welcome.

**Comment by harrygu** [comment] 2017-12-19 18:54
I would like to express that this is a critical bug to fix. Without the fix, I cannot upgrade to any version above 2.5 because the new versions do not allow us to get over api key-based authentication.

**Comment by dilipkrish** [comment] 2018-01-02 11:19
This has been fixed via upgrading to swagger ui 3.x (#2153)

**Closed by dilipkrish** 2018-01-02 11:19 UTC
Labels: bug, in progress

**Comment by harrygu** [comment] 2018-01-17 03:48
@dilipkrish Could you please give an example for how to enable the Api Key field at the top of the screen in 2.8.0? It seems there have been lots of changes in the new release.

**Comment by batizhao** [comment] 2018-01-27 02:21
@dilipkrish  The 2.8.0 version seems to be a problem. Where did I make a mistake?

## 2.6.0 and 2.7.0
These version is ok.

### Maven
```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.6.0</version>
</dependency>
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.6.0</version>
</dependency>
```

### Java code
```
@Bean
public Docket api() {
   return new Docket(DocumentationType.SWAGGER_2)
           .select()
           .apis(RequestHandlerSelectors.basePackage("sh.ideal.ims.controller"))
           .paths(PathSelectors.any())
           .build()
           .apiInfo(apiInfo())
           .securitySchemes(Collections.singletonList(apiKey()));
}

private ApiKey apiKey() {
   return new ApiKey("Bearer", "Authorization", "header");
}
```

### Input at swagger-ui
```
Api key authorization
name: Bearer
in: header
value: Bearer AAA
```

### See curl at swagger-ui
```
curl -X GET --header 'Accept: application/json' --header 'Bearer: Bearer AAA' 'http://localhost:8001/user'
```
<img width="952" alt="2018-01-27 10 04 40" src="https://user-images.githubusercontent.com/431816/35467540-68c0e80c-034a-11e8-812f-afcabcb017ce.png">

## 2.8.0 
This version ```--header 'Bearer: AAA'```  missing in swagger ui.
See curl at swagger-ui

<img width="1212" alt="2018-01-27 10 03 06" src="https://user-images.githubusercontent.com/431816/35467579-5244a9aa-034b-11e8-8f4a-5c2de0841dec.png">

Please help me, Thanks.

**Comment by dilipkrish** [comment] 2018-01-30 04:24
@batizhao Just checking, did you click the lock icon in the API and configure the API to be protected?

**Comment by batizhao** [comment] 2018-01-30 05:37
spring-boot 1.5.9.RELEASE

Java Code
```
    @ApiOperation(value = "xxxxxxx")
    @ApiImplicitParam(name = "p", value = "Page No.", dataType = "int", paramType = "query")
    @GetMapping()
    @PreAuthorize("hasRole('SUPER_ADMIN')")
    public RestResponse list(@RequestParam(value = "p", required = false, defaultValue = "1") int pageNum) {
        Page<User> users = userService.findUsers(pageNum);
        return new RestResponse<>(users);
    }
```

Step 1. Click Button "Authorize"
Step 2. input value "Bearer XXX"
Step 3. Click Button "Authorize", 
Step 4. Click "Done".
Step 5. Try it. 

--header 'Authorization: Bearer XXX' missing.

![2018-01-30 1 28 05](https://user-images.githubusercontent.com/431816/35549688-9e11c58e-05c1-11e8-960c-87df7ddf080b.png)
![2018-01-30 1 28 13](https://user-images.githubusercontent.com/431816/35549689-9e62a10c-05c1-11e8-8a5c-97430178e3c8.png)
![2018-01-30 1 28 44](https://user-images.githubusercontent.com/431816/35549692-a2ba7af4-05c1-11e8-90d2-42b3e1c4dd41.png)

**Comment by jbforth4** [comment] 2018-04-11 18:55
Is there an update on this? We want to use the new 2.8 version but cannot get it to work with OAuth.

**Comment by dilipkrish** [comment] 2018-04-27 11:25
It should be fixed in 2.9.0, if not please report back @jbforth4

**Comment by spamovy** [comment] 2018-05-14 16:09
@dilipkrish still not working in 2.9.0!

**Comment by dilipkrish** [comment] 2018-05-31 01:44
@spamovy This may be a bug in swagger-ui. Is this reproducible using the [the demos](https://github.com/springfox/springfox-demos) project?

**Comment by tah-mas** [comment] 2018-07-10 07:50
This is still not working in 2.9.2. Any update on this?

**Comment by BartoszCoyote** [comment] 2018-07-19 12:06
still no working.

**Comment by dilipkrish** [comment] 2018-07-24 11:12
@BartoszCoyote please create a new issue. 2.6.1 and 2.9.2 have different versions of swagger-ui

**Comment by medialwerk** [comment] 2018-07-26 09:19
We have the same issue with version 2.9.2, would be nice if @BartoszCoyote could create a new issue. Otherwise, I would make one in a few days :-)
