### ISSUE TITLE
Question: how to change type of an api param?

### ISSUE THREAD

**Issue by izabolotnev** [springfox/springfox#2609] opened 2018-08-09 17:32 UTC
Good day!
I write some api. There is a sample of my method:
```
    @PostMapping(value = "/order-api")
    @ApiImplicitParam(required = true, paramType = "body", dataTypeClass = EventRequest.class)
    public ResponseEntity<?> postOrderApi(@ApiParam(hidden = true) @RequestBody String requestBody) {
        return processEventRequest(Client.ORDER_API, requestBody);
    }
```
I get a string with JSON object as request body. And in generated documentation I receive this param with type string. There is exists some way to describe model of the parameter?
This way with concealment of param and writing annotation for implicit param is looking weird.
And `dataTypeClass` doesn't processed. I get string type anyway.

**Comment by dilipkrish** [comment] 2018-08-12 15:40
@izabolotnev this is a duplicate of #1949. This isnt supported yet. However you can achieve the same using the following

`@ApiImplicitParam(required = true, paramType = "body", dataType = 'EventRequest')` and adding `EventRequest.class` to the docket via `additionalModels`

**Closed** 2018-08-12 15:41 UTC
Labels: duplicate

**Comment by danidacila** [comment] 2019-08-27 15:36
ApiImplicitParam can map a parameter to a correct type, but the type must be detected by swagger, so must be a valid reference. The only way I could make this working is by using **additionalModels** method.

Example in spring-boot:
configure swagger

    import springfox.documentation.spring.web.plugins.Docket;
    import com.fasterxml.classmate.TypeResolver;
    ...

    @Bean
    public Docket api(TypeResolver typeResolver) {
    return new Docket(DocumentationType.SWAGGER_2)
    .groupName("your-group-rest-api")
    .select()
    .apis(RequestHandlerSelectors.basePackage("your.package"))
    .paths(PathSelectors.any())
    .build()
    .additionalModels(typeResolver.resolve(YourModel.class))
    .apiInfo(apiInfo());
    }

controller

    @ApiOperation...
    @ApiImplicitParams(
      @ApiImplicitParam(dataType = "YourModel", name = "requestJson", paramType = "body"))
    @ApiResponses...
    @RequestMapping...
    public void yourMethod(@RequestBody String requestJson,...)

Of course you could have an InputStream parameter for the request and map that to your model.
