### ISSUE TITLE
2.1.0 - nickname not getting honored as operationId

### ISSUE THREAD

**Issue by rajeshkamal** [springfox/springfox#880] opened 2015-07-23 21:09 UTC
Springfox seems to not honor the nickname as operationId.

It was working in the earlier Springfox releases. Is it a regression ? @adrianbk @dilipkrish 

CONTROLLER
```
    @ApiOperation(value = "Get the list of VM's in the system", nickname = "getVMs")
    @ApiResponses(value = { @ApiResponse(code = 500, message = "Internal Server Error", response = com.acme.rest.api.model.error.Error.class) })
    @RequestMapping(method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(value = HttpStatus.OK)
    public Resources<VM> getVMs() {
    }
```

SPEC
```
"/api/vms" : {
			"get" : {
				"tags" : [ "vm" ],
				"summary" : "Get the list of VM's in the system",
				"operationId" : "getVMsUsingGET",
				"consumes" : [ "application/json" ],
				"produces" : [ "application/json" ],
				"responses" : {
					"200" : {
						"schema" : {
							"$ref" : "#/definitions/Resources"
						}
					},
					"500" : {
						"description" : "Internal Server Error",
						"schema" : {
							"$ref" : "#/definitions/Error"
						}
					}
				}
			}
		}
```

**Comment by dilipkrish** [comment] 2015-07-23 23:36
May be a regression have you tried 2.1.2?

**Comment by dilipkrish** [comment] 2015-07-24 00:59
@rajeshkamal What is your expectation here. I think its working as expected. This is basically using our algorithm to generate a unique operation name across the service namespace. For e.g. if you rename nickname to `@ApiOperation(value = "Get the list of VM's in the system", nickname = "getMyVms")` you'll get an output 

```json
"operationId" : "getMyVMsUsingGET",
```

By the way this is based on the feature you had requested #825 :)

Closing this issue as works as designed. Please reopen if you still find issues

**Closed by dilipkrish** 2015-07-24 00:59 UTC

**Comment by rajeshkamal** [comment] 2015-07-24 01:15
@dilipkrish How can I override them and give custom method names? Since these are eventually getting into the code generation and it looks really odd to have method names like getVMsUsingGET etc.

**Comment by rajeshkamal** [comment] 2015-07-24 01:29
I was expecting to work something like this,

CONTROLLER
```
@ApiOperation(value = "Get the list of VM's in the system")
    public Resources<VM> getVMs() {
    }
```
SPEC - Since nickname is not give you can produce something like the below. This can be the default behavior.
```
                "operationId" : "getVMsUsingGET",
```
CONTROLLER
```
@ApiOperation(value = "Get the list of VM's in the system", nickname = "getMyVMs")
    public Resources<VM> getVMs() {
    }
```
SPEC - When a nickname is given it should be a customized behavior. And the operationId should be getMyVMs only
```
                "operationId" : "getMyVMs",
```

**Comment by rajeshkamal** [comment] 2015-07-24 01:44
@dilipkrish If you take this use-case,

Lets say if I have many different ways to fetch a VM, if you are saying that the operations ID's will be like this as a default behavior. It is OK to have it. But many would not prefer this one. Since it does not convey the meaning of these different methods.

```
fetchVMUsingGET()
fetchVMUsingGET_1()
fetchVMUsingGET_2()
fetchVMUsingGET_3()
```

But what if I want to customize this and provide my own names to those methods using the nickname property. By doing this the user/developer takes care of the responsibility of providing proper unique names. Ex:
```
fetchVMById()
fetchVMByName()
fetchVMByDatacenter()
fetchVMByUser()
fetchVMByOperatingSystem()
```
Currently there seems to be no way of achieving the above.

The only thing we can get is using the nickname currently is,
```
fetchVMByIdUsingGET()
fetchVMByNameUsingGET()
fetchVMByDatacenterUsingGET()
fetchVMByUserUsingGET()
fetchVMByOperatingSystemUsingGET()
```
If you look ate the above methods, "UsingGET" doesn't seem to provide any additional value & uniqueness since by providing the nickname I had already achieved that.

Let me know you thoughts @dilipkrish

**Comment by dilipkrish** [comment] 2015-07-24 02:28
When you're using the spring provisions, then the compiler guarantees the uniqueness, and if a method with the same name is in another controller, then springfox guarantees name uniqueness. Now when you use `@ApiOperation(nickname="some-unique-name")` then the immediate problem is that if you don't specify a method and we generate methods for all the different http methods, immediately code-generation is going to fail. 

So this is the only sure fire way to ensure uniqueness without ever breaking the code generator.

Secondly, what uniqueId is optional according the swagger spec. So our choice is either to not generate any uniqueId and pass the buck to the code generator or do a best effort in generating a unique id. 

More on this issue and [discussion here](https://github.com/springfox/springfox/issues/682) We're open to better ideas of course, and you've contributed quite a few of them, but I'm of the opinion that this might be the best solution barring a few naming aesthetics for which there can be no unanimous opinion.

**Comment by cbornet** [comment] 2015-09-15 10:05
Hello @dilipkrish, in the #682 discussion there seems to be a consensus that the nickname should be used without modification as operationId when present.
Quote from @who @adrianbk @rajeshkamal 
>1. Generated operationIds will be unique but ugly, as they will be based on the HTTP verb + URI
2. If an author changes nicknames in such a way that introduces duplicates, don't worry about throwing exceptions.

I also think that if a user uses nicknames then he knows what he is doing and if there are duplicates then it is its problem. But at least he can chose the operationId he wants.

**Comment by dilipkrish** [comment] 2015-09-15 12:48
True but not sure what the happy medium is. If you dial the switch like you suggested, people using codegen are going to create issues saying the swagger definitions are causing compilation errors. 

I think dealing with code generated names is better than the latter. Ultimately we want the library users to "fall into the pit of success". Open to suggestions tho'

**Comment by cbornet** [comment] 2015-09-15 15:39
Maybe we can had a warning on using nicknames (in javadoc ?) that it can mess up the spec if not used carefully.

**Comment by cbornet** [comment] 2015-09-15 15:40
If you want code generated names, simply don't use nicknames !

**Comment by ericbriere** [comment] 2015-09-23 10:36
I have the same issue. Version 2.0 was allowing to customize the method names with the Nickname attribute, which is not the case for 2.2. This breaks our generated APIs and prevents us to upgrade. It's unclear in this discussion if it will get fixed or not. What's the status?
