### ISSUE TITLE
Compatibility with Spring Boot 2.2 

### ISSUE THREAD

**Issue by cemo** [springfox/springfox#3124] opened 2019-09-19 09:03 UTC
Latest version of SpringFox unfortunately is not compatible with some API's of Spring Boot 2.2. So far I noticed that spring-plugin-core some methods has changed such as `org.springframework.plugin.core.PluginRegistry#getPluginFor(S, java.util.function.Supplier<E>)` which requires `Supplier` anymore. What do you suggest to migrate to Spring Boot 2.2?

**Comment by ghostd** [comment] 2019-09-20 06:23
Duplicate of #2932

**Closed** 2019-09-20 06:24 UTC
