### ISSUE TITLE
[Question] Multiple Spring-Controllers with same base-URL (same Swagger-resource)

### ISSUE THREAD

**Issue by GitVhaos** [springfox/springfox#761] opened 2015-05-28 07:34 UTC
Hi,
I`m currently integrating Springfox-Swagger in our new company REST-API and have an issue when using multiple Spring-Controller with same base-url.

Let`s say I have at least two Controllers with same @RequestMapping("/basepath") and both have different additional @RequestMapping("<ressource>") Annotaions on method level.
So each URL-Mapping is unique.

I would expect to see all URL-Mappings in my swagger-ui view, but it seems that only the Mappings of one Controller will be exposed in my swagger-ui view. The URL-Mappings of the second Controller doesn`t appear in the view.

When annotating both controller with different @Api(value="<ressource>") it`s working, but both mappings are shown as different "Swagger resources". I would like to list them as same "Swagger resource" only declared in different controllers.

Can you offer me some help on this issue? Is the configuration of same base-url in multiple controllers supported bei (springfox-)swagger?

**Comment by GitVhaos** [comment] 2015-05-28 08:38
As I understand it`s expected that there a 1:1 relation between controller and resource. But shouldn`t it be possible to serve same resource in multiple controllers and hide this in swagger-ui by listing it below same swagger-resource?

**Comment by dilipkrish** [comment] 2015-05-28 11:47
Could you post what your docket looks like? It should list all the paths under different controllers as is. Is that not happening?

**Comment by GitVhaos** [comment] 2015-05-28 11:56
Currently my Docket-Configuration is only:

  @Bean
  public Docket xyzRestApi() {
    return new Docket(DocumentationType.SWAGGER_2)
        .apiInfo(apiInfo())
        .select().build();
  }

Did I missed to configure something?

**Comment by GitVhaos** [comment] 2015-05-28 13:10
Example of my Controllers:

@Api(value = "someswaggerresource")
@Controller
@RequestMapping(value = "/swaggerresource-"
public class RessourceControllerA{

  @RequestMapping(value = "a1", method = RequestMethod.GET)
  public ResponseEntity<Object> leseRessourceA1() { }
}

@Api(value = "someswaggerresource")
@Controller
@RequestMapping(value = "/swaggerresource-"
public class RessourceControllerB{

  @RequestMapping(value = "b1", method = RequestMethod.GET)
  public ResponseEntity<Object> leseRessourceB1() { }
}

I expected to see all mappings below "someswaggerresource" in swagger-ui.

**Comment by dilipkrish** [comment] 2015-06-05 03:57
@GitVhaos Not able to reproduce this issue unfortunately. Closing it for now, feel free to reopen if v2.0.1 doesn't work for you

**Closed by dilipkrish** 2015-06-05 03:57 UTC
Labels: not-reproducable

**Comment by GitVhaos** [comment] 2015-06-05 05:53
@dilipkrish : Only for my understanding one last question. When annotating two controller with same "@Api()" Annotation, it would be the expected outcome to see all operations declared in both controllers below SAME name in swagger-ui view? Only to verifiy my expectations...

**Comment by batcer** [comment] 2015-09-04 08:52
I'm experiencing somewhat similar issue.

I've got in my controller two methods to login a user. Mapping is in interface.
```
@RequestMapping(value = "security",headers ={"Accept=application/json","Accept=application/v0+json"} )
public interface SecurityControllerI {
...
	@RequestMapping(value = User.CATEGORY+"/login",params = {"login","password"}, method = RequestMethod.GET)
	@ResponseBody
	User login(@RequestParam String login, @RequestParam String password, HttpServletRequest request, HttpServletResponse response);

    @RequestMapping(value = User.CATEGORY+"/login", method = RequestMethod.POST)
    @ResponseBody
    User login(@RequestBody String json, HttpServletRequest request, HttpServletResponse response);
...
```
In resulting json doc file, I have only POST method and no GET.
```
@Controller
public class SecurityController extends BaseController implements ISecurityController {
...
    @Override
    public User login(@RequestBody String json,
                       HttpServletRequest request, HttpServletResponse response) {
        LoginJson login = JsonUtils.getFromJson(json, LoginJson.class, true);
        return this.login(login.getLogin(), login.getPassword(), request, response);
    }

    @Override
    public User activate(@PathVariable String id, @RequestBody String json) {
        LoginJson loginJson = JsonUtils.getFromJson(json, LoginJson.class, true);
        User user = userService.activate(parseID(id), loginJson.getActivation_link());
        JsonWebContext.addMapperView(UserView.SHOW_TOKEN.class);
        return user;
    }
...
```
And

**Comment by aserg** [comment] 2017-06-05 08:40
I am too facing same issue ....Two controller with same base path but all other methods have different request mapping path.

My Dock config is

/**
     * Swagger configuration
     *
     * @return Docket
     */
    @Bean
    public Docket pcfgradleApi()
    {
        return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any()).build().pathMapping(Constants.FORWARD_SLASH)
                .genericModelSubstitutes(ResponseEntity.class)
                .alternateTypeRules(newRule(
                        typeResolver.resolve(DeferredResult.class,
                                typeResolver.resolve(ResponseEntity.class, WildcardType.class)),
                        typeResolver.resolve(WildcardType.class)))
                .useDefaultResponseMessages(false)
                .globalResponseMessage(RequestMethod.GET,
                        newArrayList(new ResponseMessageBuilder().code(500).message(Constants.FIVE_HUNDRED_MESSAGE)
                                .responseModel(new ModelRef(Constants.ERROR)).build()))
                .securitySchemes(newArrayList(apiKey())).securityContexts(newArrayList(securityContext()));
    }

    /**
     *
     * @return ApiKey
     */
    private ApiKey apiKey()
    {
        return new ApiKey(Constants.MY_KEY, Constants.API_KEY, Constants.HEADER);
    }

    /**
     *
     * @return SecurityContext
     */
    private SecurityContext securityContext()
    {
        return SecurityContext.builder().securityReferences(defaultAuth())
                .forPaths(PathSelectors.regex(Constants.FWD_SLASH_ANYPATH_DOT_STAR)).build();
    }

    /**
     *
     * @return list of SecurityReference
     */
    public List<SecurityReference> defaultAuth()
    {
        final AuthorizationScope authorizationScope = new AuthorizationScope(Constants.GLOBAL, Constants.ACCESS_EVERYTHING);
        final AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return newArrayList(new SecurityReference(Constants.MY_KEY, authorizationScopes));
    }
