### ISSUE TITLE
Want to remove default error codes

### ISSUE THREAD

**Issue by birajchoudhury** [springfox/springfox#632] opened 2015-03-30 07:55 UTC
For a POST by default these error codes are listed.

200
201	Created
401	Unauthorized
403	Forbidden
404	Not Found
 
If I use
@ApiResponses(value = {
		    @ApiResponse(code = 201, message = "Some Message", response = Something.class),
		    @ApiResponse(code = 404, message = "Some Message"),
		    @ApiResponse(code = 500, message = "Some Message")}
		)
 
Then existing ones get modified by the default ones still remain, is there a way to remove the default error listings.

And what is this empty 200 here ?

**Comment by dilipkrish** [comment] 2015-03-30 20:53
@birajchoudhury what version of the library are you using?

**Comment by birajchoudhury** [comment] 2015-03-31 05:57
@dilipkrish  I am using the release version 1.0.2

**Comment by nyddogghr** [comment] 2015-04-01 14:42
@birajchoudhury Try using useDefaultResponseMessages(false) on your SwaggerSpringMvcPlugin object when creating the bean. it has worked for me : 
@Bean
	public SwaggerSpringMvcPlugin customImplementation() {
		SwaggerSpringMvcPlugin ret = new SwaggerSpringMvcPlugin(this.springSwaggerConfig);
		return ret.useDefaultResponseMessages(false);
	}

**Comment by sheeley** [comment] 2015-04-01 15:00
That worked for me - I was surprised that `@ApiResponses` appends rather than replaces, though.

**Comment by dilipkrish** [comment] 2015-04-01 15:19
@sheeley thats been fixed in the 2.0.0-SNAPSHOT

**Comment by sheeley** [comment] 2015-04-01 18:54
That's awesome!

**Comment by hestad** [comment] 2015-04-10 10:36
Are you using the annotation together with a @RequestMethod ?
If you want to declare the responses globally, I'm doing it like this: Docket.globalResponseMessage(RequestMethod.GET, ImmutableList.of(new ResponseMessage(200, "Some global OK message",null)));

**Comment by nyddogghr** [comment] 2015-04-10 11:22
No, I don't use @RequsetMethod, only @ResponseBody and @ApiResponses

**Comment by birajchoudhury** [comment] 2015-04-29 10:35
I am trying to use 2.0.0 version now , i can see the api-docs but the swagger-ui doesnt work any more. Previously I was using 
org.ajar:swagger-spring-mvc-ui:0.4 and the documentation was in sdoc.jsp, now the same thing doesnt work I have set in properties file springfox.documentation.swagger.v2.path=/api-docs

How to get the documentation working for 2.0.0 ?

**Comment by hestad** [comment] 2015-04-29 10:44
http://springfox.github.io/springfox/docs/current/#spring-java-configuration under "Swagger UI" states you need the dependency 'io.springfox:springfox-swagger-ui:2.0.0' 

Then take a look at https://github.com/springfox/springfox-demos/blob/master/spring-java-swagger/src/main/java/springfoxdemo/java/swagger/SpringConfig.java

then it should be available at context-path/spring-dispatcher-path/swagger-ui.html

**Comment by birajchoudhury** [comment] 2015-04-29 10:49
@hestad - Thanks, that was quick .

**Comment by birajchoudhury** [comment] 2015-04-29 10:51
I have the same question as @nyddogghr  , how to disable the default responses.

**Comment by hestad** [comment] 2015-04-29 10:57
@birajchoudhury That is a bit vague, if you mean globally, have you tried Docket.useDefaultResponseMessages(false)? I'm not sure if it works without configuring Docket.globalResponseMessage(...), but i guess it's worth a try. If you mean locally someone else has to answer.

**Comment by birajchoudhury** [comment] 2015-04-29 11:17
@hestad - Docket.useDefaultResponseMessages(false) works partially

For POST and DELETE , 200 OK still shows, how to remove this.

Also the swagger docs show pet-store swagger docs once in a while , if this happens in production , it is going to be really awful.

Please suggest if you have faced this problem and have any workaround.

**Comment by birajchoudhury** [comment] 2015-05-04 07:12
@dilipkrish  -  Is there a way to remove the default codes For POST and DELETE , 200 OK 

Please know if there is a way or I live with it.

**Comment by nyddogghr** [comment] 2015-05-04 09:37
Hi, the only way I had was to use 
```
return new Docket(DocumentationType.SWAGGER_2)
			.useDefaultResponseMessages(false)
```
when created the docker.
Note that I haven't updated for some some weeks, so I don't know if there is still no other way
This way, it disables **all** responses, so you have to specify them for each method : 
```
@ApiResponses(value = {
		@ApiResponse(code = 200, message = "ACL found"), 
		@ApiResponse(code = 401, message = "You are not authenticated"), 
		@ApiResponse(code = 403, message = "You are not authorized to see these ACL"), 
		@ApiResponse(code = 404, message = "ACL not found")})
```

**Comment by birajchoudhury** [comment] 2015-05-04 09:59
@nyddogghr  - two of my API's don't return 200, so I cannot forcefully set them just to over-ride the default one. Even HTTP says for POST it should be 201 and DELETE 204.

I understand all the effort you  guys have put on this and that this is a community effort etc, but this is taking way more of my time than if I would have done manually.

If there is no work-around for this , you can close this issue, and I will take some time to set up the swagger docs manually.It is not such a tough thing to do.

**Comment by birajchoudhury** [comment] 2015-05-04 10:02
Also just to make it more interesting the 2.0.1-SNAPSHOT now only opens the petstore swagger docs.

**Comment by dilipkrish** [comment] 2015-05-04 14:29
@birajchoudhury The javascript error in `springfox.js` has been fixed, unfortunately that seems like a bug in swagger ui that doesnt want to show all the response codes. I've verified that the response codes are correct when looking at the raw swagger document @ `/v2/api-docs`, so Im closing this issue.

**Closed by dilipkrish** 2015-05-04 14:29 UTC
Labels: waiting-for-more-info

**Comment by birajchoudhury** [comment] 2015-05-05 07:46
@dilipkrish  - My question was not the one you addressed.

The issue is even with useDefaultResponseMessages(false)
DELETE and POST show 200 Ok in the list of Response Codes, how to remove them ?
When I use useDefaultResponseMessages(false) , I don't want any default response codes. I want to set my own Response codes which are 201 in case of POST and 204 in case of DELETE, but now 200 OK remains in the Response Code list forever.

I just want to know if there is a work-around on this ?

Is this a known issue , and not in priority list to be fixed now ?

Whatever the status is on this please let me know, I want only that much.

I am using the latest SNAPSHOT version.

**Comment by dilipkrish** [comment] 2015-05-05 14:55
@birajchoudhury not sure what you're talking about or even what the problem is. I'm using 2.0.1-SNAPSHOT and if I have the following definition with `useDefaultResponseMessages(false)`

```java

    @ApiOperation(value = "Create a bundle")
    @RequestMapping(value = "/bundle", method = RequestMethod.POST, 
        consumes = { "application/vnd.acme.bundle+json" }, 
        produces = { "application/vnd.acme.bundle+json" })
    @ResponseStatus(value = HttpStatus.CREATED)
    public Bundle create(@RequestBody(required = true) Bundle bundle) {
        return null;
    }
```

and this is what I see
![swagger_ui](https://cloud.githubusercontent.com/assets/73257/7475171/962137cc-f30b-11e4-958d-dac9b98779c1.jpg)

So my guess is that you're missing `@ResponseStatus(value = HttpStatus.CREATED)` in your controller method. There is no way for the library to know what status code to use if you don't specify the status code, in the absence of that it will always default to `200`.

If you're expecting that we always infer `201` status code for `POST` that is not going to happen.

**Comment by ndhar-1** [comment] 2015-08-04 23:12
How to address this problem of default response - 200 OK for POST operation when I am not using Spring framework. I can just use the swagger or jersey annotations and I defining responses with @ApiResponse

**Comment by dilipkrish** [comment] 2015-08-06 02:55
I think using `@ApiResponses` with nested `@ApiResponse` should do the trick

**Comment by ndhar-1** [comment] 2015-08-06 16:33
I am doing that, but doesnt work. see below-

@ApiOperation(value = "Create Schedule", httpMethod = "POST", consumes = "application/json", produces = "application/json")
	@ApiResponses(value = {
			@ApiResponse(code = 201, message = "Created", response = UUID.class),
			@ApiResponse(code = 401, message = "Unauthorized"),
			@ApiResponse(code = 403, message = "Forbidden") })

**Comment by MarkVanVenrooij** [comment] 2015-08-27 11:11
I'm having the same setup as @ndhar-1 and having the same issue that the 200 is still popping up.

**Comment by MarkVanVenrooij** [comment] 2015-08-27 12:13
Actually this was fixed at my end by adding @ResponseStatus(value = HttpStatus.CREATED) annotation as well

**Comment by ndhar-1** [comment] 2015-08-27 16:46
Well this is a Spring framework annotation. What can be a solution for no-Spring setup ?

**Comment by dilipkrish** [comment] 2015-08-28 01:08
@ndhar-1 there is none I think. You could create your own annotation and implement a `OperationBuilderPlugin` plugin. [See here](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/ResponseMessagesReader.java#L81-L82) for an example of how to set it.

**Comment by agustisanchez** [comment] 2017-11-25 08:19
It's apparent springfox relies on Spring REST annotations even when not desired :)
Sometimes, controller methods set the HTTP status dynamically and a static `@ResponseStatus`  annotation is not explicitly set by the developers as it does not make sense in that scenario.

However, apparently, Spring adds a default `@ResponseStatus` anyway under the hood which Springfox eventually exposes in the Swagger doc.

The workaround is to explicitly set a `@ResponseStatus` in your controller method with one of the returned HTTP codes (the one used in the success scenario, for instance) so that the undesired default `@ResponseStatus` does not end up in the Api docs.

**Comment by dilipkrish** [comment] 2017-11-26 15:41
@agustisanchez that is exactly correct. The other alternative is to use the swagger annotations and disable to default response codes.

**Comment by Lubetkin** [comment] 2017-12-03 12:17
Can I remove a Global error response from specific ApiOperation (Not overriding the error response)?

**Comment by dilipkrish** [comment] 2017-12-03 20:40
Not at the moment.

**Comment by introtj** [comment] 2018-02-04 08:25
This is my solution that I added "code = 204" in @ApiOperation.
@ApiOperation(value = "SMS 발송", code = 204, response = MMSRequestDTO.class)
@ApiResponses(value = {
            @ApiResponse(code = 204, message = "문자 발송 완료"),
            @ApiResponse(code = 401, message = "Unauthorized", response = ErrorMessage.class),
            @ApiResponse(code = 500, message = "Interval Server Error", response = ErrorMessage.class)
    })

**Comment by GiovaneFGomes** [comment] 2021-10-08 17:47
> Oi, a única maneira que eu tinha era usar
> 
> ```
> return new Docket(DocumentationType.SWAGGER_2)
>             .useDefaultResponseMessages(false)
> ```
> 
> ao criar a janela de encaixe. Note que não atualizo há algumas semanas, então não sei se ainda não existe outra forma. Desta forma, ele desabilita **todas as** respostas, então você tem que especificá-las para cada método:
> 
> ```
> @ApiResponses(value = {
>         @ApiResponse(code = 200, message = "ACL found"), 
>         @ApiResponse(code = 401, message = "You are not authenticated"), 
>         @ApiResponse(code = 403, message = "You are not authorized to see these ACL"), 
>         @ApiResponse(code = 404, message = "ACL not found")})
> ```
> 
> Não sei se vai te ajudar, mas aqui está


This works for me, thanks bro

**Comment by ShubhamDogra95** [comment] 2021-10-11 17:48
For PUT method  If i want to show 200 status code and remove the 201 code . What should I do for this change to take place in swagger?
