### ISSUE TITLE
Parameter Data Type does not print. 

### ISSUE THREAD

**Issue by pprabhu3430** [springfox/springfox#688] opened 2015-04-17 19:32 UTC
The param data type or return type is not present when either of them is an annotated hibernate entity. 
A simple POJO with getters and setters shows up fine. However something like this does not. 

	@Entity
	public class BaseBills implements java.io.Serializable {

		private static final long serialVersionUID = 7572843412319195892L;
		
		@Id
		private BaseBillsId ID;
		
		@Column(name = "PO_ID")
		private Integer PO_ID = 0;

		public BaseBillsId getID() {
			return ID;
		}
		
		@JsonProperty("ID")
		public void setID(BaseBillsId iD) {
			ID = iD;
		}

		public Integer getPO_ID() {
			return PO_ID;
		}
		
		@JsonProperty("PO_ID")
		public void setPO_ID(Integer pO_ID) {
			PO_ID = pO_ID;
		}

	}

![image](https://cloud.githubusercontent.com/assets/5148405/7209512/3a3f7498-e517-11e4-849c-19c3f4d9cfbc.png)

**Comment by dilipkrish** [comment] 2015-04-18 05:12
@pprabhu3430 what does your request mapping look like on the controller

**Comment by pprabhu3430** [comment] 2015-04-20 13:05
Just a standard controller. Here is the full code of the rest controller method. 

	@RequestMapping(value = "/create", method = RequestMethod.POST)
	@ApiOperation(value = "Create a Bill", notes = "Create a bill with this API. ", position = 1)
    public @ResponseBody Result create(@RequestBody BaseBills bill) {
		billsDAO.create(bill, bill.getID());
        return new Result(true, "Successfully created bill with the following bill_id - " + bill.getID().getBILL_ID());
    }

**Comment by dilipkrish** [comment] 2015-05-03 03:24
@pprabhu3430 could you share you repo perhaps? Its not clear why it would not render any of the properties.

Or you could try 2.0.1 snapshot and turn log level to debug for package `springfox.documentation.schema`

**Comment by dilipkrish** [comment] 2015-05-03 14:14
I'm closing this issue for now. Im unable to reproduce this issue. Feel free to reopen if it doesn't work in 2.0.1

**Closed by dilipkrish** 2015-05-03 14:14 UTC
Labels: investigating
