### ISSUE TITLE
Swagger is not compatible with Spring 4.2.3

### ISSUE THREAD

**Issue by josetesan** [springfox/springfox#1055] opened 2015-11-16 13:08 UTC
I've just updated my spring-boot 1.3.0.RC1 ( also 1.3.0.RELEASE ) app to Spring 4.2.3, and having
```
<dependency>
          <groupId>io.springfox</groupId>
          <artifactId>springfox-swagger2</artifactId>
          <version>2.2.2</version>
      </dependency>
      <dependency>
          <groupId>io.springfox</groupId>
          <artifactId>springfox-swagger-ui</artifactId>
          <version>2.2.2</version>
          <scope>runtime</scope>
      </dependency>
```
in my pom.xml, used in a class
```
@Configuration
@EnableSwagger2
public class SwaggerConfig {
```

makes the application do not boot.

See error log attached :

```
2015-11-16 11:56:18,050 ERROR o.s.b.SpringApplication | Application startup failed 
java.lang.IllegalArgumentException: interface org.springframework.core.annotation.SynthesizedAnnotation is not visible from class loader
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581) ~[na:1.8.0_66]
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[na:1.8.0_66]
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[na:1.8.0_66]
        at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[na:1.8.0_66]
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[na:1.8.0_66]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[na:1.8.0_66]
        at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1404) ~[spring-core-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.core.annotation.AnnotatedElementUtils.findMergedAnnotation(AnnotatedElementUtils.java:405) ~[spring-core-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.method.HandlerMethod.getMethodAnnotation(HandlerMethod.java:234) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at springfox.documentation.spring.web.readers.operation.OperationDeprecatedReader.apply(OperationDeprecatedReader.java:34) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:113) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:79) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.readers.operation.ApiOperationReader$$FastClassBySpringCGLIB$$7c030d50.invoke(<generated>) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at springfox.documentation.spring.web.caching.CachingAspect.cachedValue(CachingAspect.java:86) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.caching.CachingAspect.operationsAndProperties(CachingAspect.java:69) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:654) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at springfox.documentation.spring.web.readers.operation.ApiOperationReader$$EnhancerBySpringCGLIB$$c04784f2.read(<generated>) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:67) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:92) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:62) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:87) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:50) ~[springfox-spring-web-2.2.2.jar:2.2.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:854) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) ~[spring-boot-1.3.0.RC1.jar:1.3.0.RC1]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RC1.jar:1.3.0.RC1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.3.0.RC1.jar:1.3.0.RC1]
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:356) [spring-boot-1.3.0.RC1.jar:1.3.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RC1.jar:1.3.0.RC1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1085) [spring-boot-1.3.0.RC1.jar:1.3.0.RC1]
```

**Comment by dilipkrish** [comment] 2015-11-16 15:05
I suspect its because of the aspectj libraries you've got in the project. This issue might be fixed in 2.2.3-SNAPSHOT. Would you be able to try it and report back?

**Comment by josetesan** [comment] 2015-11-17 09:17
I'm using 
```
2787 [INFO] |  \- org.aspectj:aspectjweaver:jar:1.8.7:compile
2788 [INFO] \- org.aspectj:aspectjrt:jar:1.8.7:compile
```

Are they the right versions ?

**Comment by dilipkrish** [comment] 2015-11-18 03:40
It sure is... Is it working for you in 2.2.3-SNAPSHOT? or is it busted there as well

**Comment by josetesan** [comment] 2015-11-18 17:57
Nope, it does not work yet, same error.
I tried snapshot from today, and got same error :
```
2015-11-18 18:56:09,189 ERROR o.s.b.SpringApplication | Application startup failed 
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: interface org.springframework.core.annotation.SynthesizedAnnotation is not visible from class loader
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:70) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:89) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:69) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:87) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:50) ~[springfox-spring-web-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:854) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.ventura24.nlp.webshop.WebShop.main(WebShop.java:23) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.0.RELEASE.jar:1.3.0.RELEASE]
Caused by: java.lang.IllegalArgumentException: interface org.springframework.core.annotation.SynthesizedAnnotation is not visible from class loader
```

**Comment by RobWin** [comment] 2015-11-19 11:57
Same here.

**Comment by lostirc** [comment] 2015-11-19 13:43
I'm also seeing this

**Comment by danwatt** [comment] 2015-11-20 04:14
Same here, Spring Boot 1.3 / Spring * 4.2.3

**Comment by marcingrzejszczak** [comment] 2015-11-20 21:13
Same in https://github.com/4finance/micro-infra-spring even though we're using some old version of swagger `com.mangofactory:swagger-springmvc:1.0.2`

**Comment by dilipkrish** [comment] 2015-12-02 02:58
Anyone want to try the 2.2.3-SNAPSHOT and see if the problem is fixed?

/c @RobWin @josetesan @lostirc @danwatt @marcingrzejszczak

**Comment by RobWin** [comment] 2015-12-02 05:49
Yes. I can do that today.

**Comment by RobWin** [comment] 2015-12-02 07:59
Same issue in another class
```
aused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: interface org.springframework.core.annotation.SynthesizedAnnotation is not visible from class loader
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57)
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:70)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:89)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:69)
```

**Comment by dilipkrish** [comment] 2015-12-02 10:55
I created a project from scratch using start.spring.io and it works just fine. Wonder whats different

```ascii
+--- io.springfox:springfox-swagger2:2.2.3-SNAPSHOT
|    +--- org.mapstruct:mapstruct:1.0.0.Final
|    +--- io.swagger:swagger-annotations:1.5.4
|    +--- io.swagger:swagger-models:1.5.4
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.5 -> 2.6.3
|    |    +--- org.slf4j:slf4j-api:1.6.3 -> 1.7.13
|    |    \--- io.swagger:swagger-annotations:1.5.4
|    +--- io.springfox:springfox-spi:2.2.3-SNAPSHOT
|    |    \--- io.springfox:springfox-core:2.2.3-SNAPSHOT
|    |         +--- com.google.guava:guava:18.0
|    |         +--- com.fasterxml:classmate:1.2.0
|    |         +--- org.slf4j:slf4j-api:1.7.13
|    |         +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE
|    |         |    +--- org.springframework:spring-beans:4.0.9.RELEASE -> 4.2.3.RELEASE (*)
|    |         |    +--- org.springframework:spring-context:4.0.9.RELEASE -> 4.2.3.RELEASE (*)
|    |         |    +--- org.springframework:spring-aop:4.0.9.RELEASE -> 4.2.3.RELEASE (*)
|    |         |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.13
|    |         +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE
|    |         |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |         |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.13
|    |         \--- org.springframework.hateoas:spring-hateoas:0.18.0.RELEASE -> 0.19.0.RELEASE
|    |              +--- org.springframework:spring-aop:4.1.7.RELEASE -> 4.2.3.RELEASE (*)
|    |              +--- org.springframework:spring-beans:4.1.7.RELEASE -> 4.2.3.RELEASE (*)
|    |              +--- org.springframework:spring-context:4.1.7.RELEASE -> 4.2.3.RELEASE (*)
|    |              +--- org.springframework:spring-core:4.1.7.RELEASE -> 4.2.3.RELEASE
|    |              +--- org.springframework:spring-web:4.1.7.RELEASE -> 4.2.3.RELEASE (*)
|    |              +--- org.springframework:spring-webmvc:4.1.7.RELEASE -> 4.2.3.RELEASE (*)
|    |              \--- org.slf4j:slf4j-api:1.7.12 -> 1.7.13
|    +--- io.springfox:springfox-schema:2.2.3-SNAPSHOT
|    |    +--- io.springfox:springfox-core:2.2.3-SNAPSHOT (*)
|    |    \--- io.springfox:springfox-spi:2.2.3-SNAPSHOT (*)
|    +--- io.springfox:springfox-swagger-common:2.2.3-SNAPSHOT
|    |    +--- io.swagger:swagger-annotations:1.5.4
|    |    +--- io.swagger:swagger-models:1.5.4 (*)
|    |    +--- io.springfox:springfox-spi:2.2.3-SNAPSHOT (*)
|    |    +--- io.springfox:springfox-schema:2.2.3-SNAPSHOT (*)
|    |    +--- io.springfox:springfox-spring-web:2.2.3-SNAPSHOT
|    |    |    +--- com.google.guava:guava:18.0
|    |    |    +--- com.fasterxml:classmate:1.2.0
|    |    |    +--- org.slf4j:slf4j-api:1.7.13
|    |    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    |    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    |    |    +--- org.springframework.hateoas:spring-hateoas:0.18.0.RELEASE -> 0.19.0.RELEASE (*)
|    |    |    +--- io.springfox:springfox-spi:2.2.3-SNAPSHOT (*)
|    |    |    \--- io.springfox:springfox-schema:2.2.3-SNAPSHOT (*)
|    |    +--- com.google.guava:guava:18.0
|    |    +--- com.fasterxml:classmate:1.2.0
|    |    +--- org.slf4j:slf4j-api:1.7.13
|    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    |    \--- org.springframework.hateoas:spring-hateoas:0.18.0.RELEASE -> 0.19.0.RELEASE (*)
|    +--- io.springfox:springfox-spring-web:2.2.3-SNAPSHOT (*)
|    +--- com.google.guava:guava:18.0
|    +--- com.fasterxml:classmate:1.2.0
|    +--- org.slf4j:slf4j-api:1.7.13
|    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    \--- org.springframework.hateoas:spring-hateoas:0.18.0.RELEASE -> 0.19.0.RELEASE (*)
\--- io.springfox:springfox-swagger-ui:2.2.3-SNAPSHOT
     \--- io.springfox:springfox-spring-web:2.2.3-SNAPSHOT (*)
```

**Comment by dilipkrish** [comment] 2015-12-02 10:57
@RobWin do you have the full stacktrace or may be a repo which reproduces the problem?

**Comment by RobWin** [comment] 2015-12-02 11:07
Yes.
https://github.com/Swagger2Markup/spring-swagger2markup-demo/tree/new_springboot

Branch `new_springboot`

**Closed** 2015-12-02 12:15 UTC
Labels: bug

**Comment by dilipkrish** [comment] 2015-12-02 12:17
@RobWin that was super useful... I think we can close this case. The snapshot should be available in a bit.

**Comment by RobWin** [comment] 2015-12-02 12:37
Nice :)

**Comment by RobWin** [comment] 2015-12-02 15:08
Is there a new snapshot available?

**Comment by dilipkrish** [comment] 2015-12-02 15:13
Every commit to master produces a new snapshot build 😇

**Comment by RobWin** [comment] 2015-12-02 15:17
Seems to take a while.

**Comment by dilipkrish** [comment] 2015-12-02 15:20
It has a different mvn coordinate (jfrog OSS). The docs should point u to the right url. (Sorry typing from a mobile phone). U can change it temporarily to check

**Comment by RobWin** [comment] 2015-12-02 15:20
I used http://oss.jfrog.org/artifactory/oss-snapshot-local/

**Comment by dilipkrish** [comment] 2015-12-02 15:25
Yeah yr right... its not synched up yet. I think there seems to be problem with the build

**Comment by dilipkrish** [comment] 2015-12-02 15:30
tried  `gradle ... --refresh-dependencies`?

**Comment by RobWin** [comment] 2015-12-02 15:33
Thx. that did it.
Works now :+1: Thx!

**Comment by josetesan** [comment] 2015-12-08 12:59
With version 2.3.0 just released i can confirm it works !

Great job, guys.
