### ISSUE TITLE
SpringDataRest

### ISSUE THREAD

**Issue by vivekpandian** [springfox/springfox#238] opened 2014-03-20 17:24 UTC
Hi,
It looks like Swagger-Springmvc doesn't support SpringDataRest out of the box. Like to know, if there is any proposal to support SpringDataRest in near future. I feel SpringDataRest support should be fairly straight-forward. 

https://groups.google.com/forum/#!topic/swagger-swaggersocket/f-s7xHKmxgk

Thanks,
Vivek.

**Comment by jhiemer** [comment] 2015-01-01 16:22
@jewellcj I would be interested as well.

**Comment by jxc876** [comment] 2015-01-14 19:14
This functionality would be much appreciated, although I can see the point that @olivergierke makes: Swagger defines a static application-level API while Spring Data Rest tries to be hypermedia (link) driven.

**Comment by dilipkrish** [comment] 2015-01-15 03:29
@jewellcj @jxc876 @ghorwitchsmith  We're getting ready to do just that. There is a WIP in progress [see this issue](https://github.com/martypitt/swagger-springmvc/issues/538).

Currently this library is tied to swagger and we're in the process of teasing out some of that coupling to support more documentation formats, Swagger 2.0, RAML etc. and most importantly documenting services RESTfully leveraging hypermedia. One of the ideas I've been playing around with is to support a hal-"dialect" of the swagger specification. **Feedback and PR's are much appreciated** 

As @olivergierke mentioned the swagger specification is not very different from any other RPC like specifications like the ones that came before it ... aka the much *reviled four letter word WSDL* :smile: 
Another interesting approach to documenting services is taking shape over at @wilkinsona 's [rest documentation project](https://github.com/wilkinsona/spring-restdocs).

**Comment by dilipkrish** [comment] 2015-08-11 03:03
Closing this as a duplicate of #699

**Closed by dilipkrish** 2015-08-11 03:03 UTC
Labels: feature
