### ISSUE TITLE
Repeated requests

### ISSUE THREAD

**Issue by ejain** [springfox/springfox#848] opened 2015-07-15 06:33 UTC
After requesting /swagger-resources (which returns `[{"name":"default","location":"/v2/api-docs","swaggerVersion":"2.0"}]`), I'm seeing dozens of identical requests to `/v2/api-docs`. swagger-ui.html displays fine (no duplicate entries etc), but the unnecessary requests do slow down things a bit...
![network](https://cloud.githubusercontent.com/assets/1323903/8692177/87f00e42-2a80-11e5-8a55-92ca1c0cdbda.png)

**Comment by dilipkrish** [comment] 2015-07-15 11:52
Seems like a bug to me... what browser/version is this happening?

**Comment by cabbonizio** [comment] 2015-07-15 13:11
I have seen this behavior also primarily using Chrome.   

@ejain could you try clearing your browsing data, restart browser and see if same behavior happens?   It seems like those who cut over from one version of Spring Fox (say 2.01 to 2.03 for example) I noticed this.  

@dilipkrish does this ring any bells?

**Comment by ejain** [comment] 2015-07-15 15:39
I'm seeing this with 2.0.3 on both the current versions of Chrome and Firefox. Clearing the browser and restarting doesn't help.

**Comment by dilipkrish** [comment] 2015-07-15 16:33
I verified the :bug:  thanks for reporting

**Comment by cabbonizio** [comment] 2015-07-15 17:02
@ejain arghh......i was hoping that would help you.   I guess it was something else then causing the repeated requests.  

@dilipkrish curious did u find root cause?

**Comment by dilipkrish** [comment] 2015-07-17 03:47
I did some digging into this and it appears to be an issue internal to swagger-ui. Also found something similar in the [swagger-ui/swagger.js](https://github.com/swagger-api/swagger-ui/issues/1429) issues. So I'm going to close it for now until that issue is resolved.

**Closed by dilipkrish** 2015-07-17 03:47 UTC
Labels: bug

**Comment by ejain** [comment] 2015-07-17 17:40
btw I can't reproduce this issue with 2.1.0.

**Comment by dilipkrish** [comment] 2015-07-17 17:47
That is strange!
