### ISSUE TITLE
Succeeded to get the /api-docs data on a Spring project but failed on the other older Spring project with the same config

### ISSUE THREAD

**Issue by choiapril6** [springfox/springfox#923] opened 2015-08-20 02:32 UTC
Before trying to integrate Springfox into a quite large and complex Spring project, I was able to get the /v2/api-docs from a sample project which is way more simple. 

With the exact same configuration, I tried to do on my large project. But it failed to initialize the context. And I guess that's caused by Springfox. 

The errors I got and solutions I tried are:

1) At first, bean creation exception caused due to same bean name. But one of two is not existent at the moment. Failing to find any available solution, I narrowed the range of component scan, actually to just one package.

After that, another error emerged,

2) Annotation parse failed. Below is the exact copy from Eclipse console.

[ERROR] (ContextLoader.java:331) Context initialization failed
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotations(Class.java:3446)

3) Since I couldn't even suspect any reason, I down-versioned Springfox to swagger-springmvc. On this, context initialization worked, but when I requested 
"localhost:8080/v2/api-docs?group=my-api",

 it says 
"NO MAPPING for [/v2/api-docs]" 

I appreciate if anybody could fix this issue. Thanks.

**Comment by dilipkrish** [comment] 2015-08-20 14:21
@choiapril6 What versions of spring/jdk are you using.

Also v1.0.2 (swagger-springmvc) is no longer supported so I think its probably best to continue with 2.2.2 and trying to find the solution.

**Comment by choiapril6** [comment] 2015-08-21 14:46
Thanks for quick reply. I am using:
spring.version: 3.2.8.RELEASE
jdk.version: 1.6
and springfox-swagger2 version 2.2.2.

**Comment by dilipkrish** [comment] 2015-09-10 02:45
Closing this as a duplicate of #921

**Closed by dilipkrish** 2015-09-10 02:45 UTC
Labels: duplicate, question
