### ISSUE TITLE
LocalDate should have format date instead of date-time

### ISSUE THREAD

**Issue by ralfstuckert** [springfox/springfox#1429] opened 2016-08-01 09:08 UTC
Currently LocalDate is represented by `"type":"string", "format":"date-time"` by springfox. But since LocalDate represents (and is converted by spring/jackson to) an ISO-8601 conform date in format YYYY-MM-DD, it should result in `"type": "string","format": "date"` as described in the swagger spec.

**Comment by dilipkrish** [comment] 2016-08-01 14:09
Se [here](https://github.com/springfox/springfox/issues/1021#issuecomment-178626396) for a work around.

**Comment by ralfstuckert** [comment] 2016-08-02 06:27
Thanks, that will help for now :-)

Nevertheless I guess `LocalDate` should translate to `string/date` (`io.swagger.models.properties.DateProperty`)

**Comment by ssevertson** [comment] 2016-08-17 20:00
Duplicate of #1337?

**Comment by dilipkrish** [comment] 2016-09-25 15:23
Closing since its a duplicate of #1337

**Closed by dilipkrish** 2016-09-25 15:23 UTC
Labels: has-workaround, maintenance
