### ISSUE TITLE
Present multipart object attributes as "formData"

### ISSUE THREAD

**Issue by andyRokit** [springfox/springfox#2401] opened 2018-05-07 16:18 UTC
Given the existence of the following endpoint:
```
public class Foo {
    @ApiModelProperty(value = "Bar description", required = true)
    private String bar;
    ...
```

```
@PostMapping(value = "/foo", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public void postFooAsMultiPart(Foo foo) {
    ...
```

If I mark Foo as a `@RequestBody` it will be presented as a single field:

```
"parameters": [
  {
    "in": "body",
    "name": "foo",
    "description": "foo",
    "required": true,
    "schema": {
      "$ref": "#/definitions/Foo"
    }
  }
],
```

If I don't mark Foo as `@RequestBody` its attributes are presented as query fields:

```
"parameters": [
  {
    "name": "bar",
    "in": "query",
    "description": "Bar description",
    "required": true,
    "type": "string"
}
],
```

I would like the presence of a multipart form data header to render the request as:

```
"parameters": [
  {
    "name": "bar",
    "in": "formData",
    "description": "Bar description",
    "required": true,
    "type": "string"
}
],
```

I'm not sure if this is a bug or a feature or if it even makes sense to do!

Notes
- Reported behavior on 2.8.0
- I've posted a [question](https://stackoverflow.com/questions/50177073/spring-swagger-multipart-form) on stackoverflow asking how this should be done, but I'm not optimistic about a positive response (hence this ticket)
- I assume this change would involve `OperationParameterReader.shouldExpand` taking account of the `consumes` header and if multipart, passing data down to `ExpandedParameterBuilder` that would make the `parameterType` dynamic rather than hard-coded to `"query"`.

**Comment by dilipkrish** [comment] 2018-05-08 11:05
Thanks for a reporting. This is a duplicate of #2376

**Comment by andyRokit** [comment] 2018-05-10 08:55
@dilipkrish Just to let you know I opened the PR against the original ticket

**Comment by dilipkrish** [comment] 2018-05-10 23:17
No problem!

**Closed** 2018-06-23 13:29 UTC
Labels: bug, duplicate
