### ISSUE TITLE
@EnableSwagger2 forces microservice to register as UNKNOWN to registry

### ISSUE THREAD

**Issue by martin3361** [springfox/springfox#1542] opened 2016-10-24 12:35 UTC
We are using Springfox Swagger 2.6.0, Spring Boot 1.3.3.RELEASE and Spring Cloud 1.1.2.RELEASE.

Annotated application class with @EnableDiscoveryClient is registered to the registry.

When the @EnableSwagger2 annotation is present, the discovery client (microservice) is registered as UNKNOWN. When the annotation is not present, the discovery client actually registers as what is specified in bootstrap.yml in property 'spring.application.name'.

Thus it is making impossible to call the microservice via the gateway, because it is not registered under its real name.

P.S. Using Swagger 2.5.0 this does not occur.

**Comment by dilipkrish** [comment] 2016-10-24 14:03
Closing this a duplicate of #1532. This should be fixed in 2.6.1

**Closed by dilipkrish** 2016-10-24 14:03 UTC
Labels: bug, duplicate
