### ISSUE TITLE
From two methods in one controller, using same URL and POST vs GET methods, only one is documented.

### ISSUE THREAD

**Issue by batcer** [springfox/springfox#952] opened 2015-09-08 10:04 UTC
I`m currently integrating Springfox-Swagger in our REST API and have an issue when using several methods with the same URL, differing in request method (GET vs POST), in one controller.

Mapping is in interface ISecurityController. Actions are implemented in SecurityController implementation class.

I have two methods, one with @RequestMapping(value = "login", params = {"login","password"},                                         method = RequestMethod.GET), another one with @RequestMapping(value = "login", method = RequestMethod.POST). I also have @RequestMapping(value = "security") on a controller level.

I would expect to see both methods in resulting json file and in my swagger-ui view, but there is only POST method. Annotating both controller with different values in @ApiOperation (value="POST login" vs value="GET login") does not make any difference: I still have only POST method documented.

```
@RequestMapping(value = "security",headers ={"Accept=application/json","Accept=application/v0+json"} )
public interface ISecurityController {
...
    @RequestMapping(value = "login",params = {"login","password"}, 
                                        method = RequestMethod.GET)
    @ResponseBody
    User login(@RequestParam String login, @RequestParam String password, 
                         HttpServletRequest request, HttpServletResponse response);

    @RequestMapping(value = "login", method = RequestMethod.POST)
    @ResponseBody
    User login(@RequestBody String json, HttpServletRequest request, 
                     HttpServletResponse response);
...
```

```
@Controller
public class SecurityController extends BaseController implements ISecurityController {
...
    @Override
    public User login(@RequestBody String json,
                       HttpServletRequest request, HttpServletResponse response) {
        LoginJson login = JsonUtils.getFromJson(json, LoginJson.class, true);
        return this.login(login.getLogin(), login.getPassword(), request, response);
    }

    @Override
    public User activate(@PathVariable String id, @RequestBody String json) {
        LoginJson loginJson = JsonUtils.getFromJson(json, LoginJson.class, true);
        User user = userService.activate(parseID(id), loginJson.getActivation_link());
        JsonWebContext.addMapperView(UserView.SHOW_TOKEN.class);
        return user;
    }
...
```
I'm using springfox-swagger2 and springfox-spring-web from http://mvnrepository.com/ both version 2.2.2, with Spring Framework version 4.1.7.RELEASE.

**Comment by dilipkrish** [comment] 2015-09-08 12:52
This is a duplicate of #750

**Comment by batcer** [comment] 2015-09-08 12:59
Well, not exactly. In #750 both methods are GET, they differ in parameter. Here they differ in method, and then in parameters. Inside Swagger datastructre, method is mapped to URL outside and then to method ("post" or "get") inside, so it is possible to have to different methods on one URL mapping.

**Closed** 2015-12-02 16:48 UTC
Labels: duplicate, question

**Comment by lw1607** [comment] 2016-09-14 08:17
Hi,

I have the same issue: I have 3 services which are using the same url and all parameters are in the path (and there are all the same). The only difference is that the first method has method = RequestMethod.GET, the second has method = RequestMethod.POST and the last has method = RequestMethod.DELETE. Do you know of any workaround? Thanks

**Comment by lw1607** [comment] 2016-09-14 08:20
P.S. I am using springfox 2.5.0

**Comment by dilipkrish** [comment] 2016-09-14 11:17
@lw1607 Yeah there is an open issue #1367 that is similar. Should be fixed in 2.5.0

**Comment by lw1607** [comment] 2016-09-14 16:11
Found a workaround meanwhile (probably not as pretty but it does the job): 

We assume that springfox (springfox-swagger2) has been integrated correctly (without springfox-swagger-ui) and that the url: http://localhost:8080/myapproot/v2/api-docs provide the list of my app services

instead of adding the maven dependency:

    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>

Add maven dependency: 

<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>swagger-ui</artifactId>
	<version>2.2.2</version>
</dependency>

Then as long as the webjars mapping is enabled in the spring config:


    <mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>

Then you can access http://localhost:8080/myapproot/webjars/swagger-ui/2.2.2/index.html#/

In there you can paste the url http://localhost:8080/myapproot/v2/api-docs in the top text field. When clicking on explore it will list everything correctly.

**Comment by lw1607** [comment] 2016-09-14 16:14
Hope it might help for a fix @dilipkrish. In any case thanks for your swift reply and help.

**Comment by chotku795** [comment] 2019-08-26 08:43
paths: /contract/associated/party/lov
i want it as a "associated/party/lov"
