### ISSUE TITLE
Duplicate methods printed . JSON document has duplicates as well. 

### ISSUE THREAD

**Issue by pprabhu3430** [springfox/springfox#630] opened 2015-03-27 21:06 UTC
I have a simple spring MVC app that has a few rest services. Swagger works great and the only thing it appears to do wrong is print each api twice for the same http method. 
I looked at the JSON document it pulls for each API and they have duplicates too. SO I dont think it's the UI that has the bug, but rather the Swagger-spring MVC plugin. 

![image](https://cloud.githubusercontent.com/assets/5148405/6877001/4b8b84e6-d4a3-11e4-9ee6-48ff713be082.png)

This api array contains an object with this "path":"/rest/vendor/create" twice and the same way for others that are repeated. 

  "apis":[  
      {  
         "path":"/rest/vendor/create",
         "description":"create",

My Spring MVC gradle build has this. 

	compile 'com.mangofactory:swagger-springmvc:1.0.0'
	compile 'com.fasterxml.jackson.core:jackson-databind:2.5.0'

Any help is appreciated . Thanks!

**Comment by dilipkrish** [comment] 2015-03-27 21:13
@pprabhu3430 Could you please try with 1.0.2 and report back?

**Comment by pprabhu3430** [comment] 2015-03-27 21:53
I got 1.0.2 and its the same exact issue. Duplicates are seen. 

Also I notice that the response object doesnt correctly populate sometimes. In the below case a List of VendorType is returned. The VendorType is a hibernate entity, not sure if that causes any conflict. Use APIModel annotations doesnt help. When the response is not a hibernate entity, it seems to work fine and shows the response structure correctly. The entity correctly has getters and setters defined for the properties. However they are capital case properties to accomodate a legacy system we have which serializes all JSON object properties to capital case. 

![image](https://cloud.githubusercontent.com/assets/5148405/6877704/e5f1a5dc-d4a9-11e4-8f90-4d38e35ceead.png)

**Comment by pprabhu3430** [comment] 2015-03-31 17:36
Ok I got the latest Swagger UI and the issue doesnt exist anymore. I guess they have a way of removing duplicates if present in the api definition. No idea. Putting this out there in case it helps someone.

**Comment by dilipkrish** [comment] 2015-03-31 18:12
@pprabhu3430 Could you confirm if the dupes exist in the api-docs json?

**Comment by pprabhu3430** [comment] 2015-03-31 18:46
I have a screenshot of the json doc returned for my vendor api. 

![image](https://cloud.githubusercontent.com/assets/5148405/6926481/96dedc2c-d7b4-11e4-8eaf-ea6c5ef218f3.png)

As you can see there are duplicates in the Returned JSON structure.

**Comment by dilipkrish** [comment] 2015-07-24 03:04
@pprabhu3430 any updates on this? I'm closing this issue as not reproducible. Feel free to reopen if its still not fixed

**Closed by dilipkrish** 2015-07-24 03:04 UTC
Labels: bug

**Comment by aamirsheikh** [comment] 2015-08-19 11:43
<artifactId>swagger-springmvc</artifactId>
            <version>0.8.8</version>

I am having this issue and it is returning the same operation multiple itmes
![todel](https://cloud.githubusercontent.com/assets/13539537/9355292/8f0d4dc6-4695-11e5-9a05-1747cf120699.JPG)
Can some one help me how to fix it
