### ISSUE TITLE
Question:  how to use @ApiParam annotation on a parameter defined in an interface?

### ISSUE THREAD

**Issue by taxone** [springfox/springfox#1670] opened 2017-02-10 15:02 UTC
Hi,
I'm using SpringFox 2.6.1. 
I defined an **interface** as follows:

```java
Api(value = "executablesByEvent", description = "the executablesByEvent API")
@RestController
public interface ExecutablesByEventApi {

    @ApiOperation(value = "eseguibili associati ad un evento", notes = "Recupera gli esegubili associati all'evento passato come parametro ", response = Executable.class, responseContainer = "List", tags={ "decrypt", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "gli eseguibili recuperati associati all'evento passato come parametro", response = Executable.class) })
    @RequestMapping(value = "/executablesByEvent",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    public ResponseEntity<Resources<Executable>> executablesByEvent(
        @ApiParam(value = "URL dell'entitiy associata all'evento per il quale recuperare gli eseguibili associati. ", required = true,name = "event") @RequestParam(value = "event", required = true) String event,
        HttpServletRequest request,
        Principal principal);

}
```

This interface is implemented by a Spring annotated with "@Controller".
All of the Swagger annotations are properly processed and visible by Swagger UI; the Rest endpoint operates correctly when it is called by a client.
The only exception is the @ApiParam annotation, in fact it seems that it's ignored. If I try to use the @ApiParam annotation in the method of  the concrete class implementing the interface then the annotation is processed properly.
Is it a bug or is there something wrong in my code?
Thanks in advance.

**Comment by dilipkrish** [comment] 2017-02-11 14:21
It is a bug, however its [been fixed in the snapshot](https://github.com/springfox/springfox/pull/1589), which hasn't been released yet.

**Comment by dilipkrish** [comment] 2017-02-14 03:57
*UPDATE:* this is a duplicate of #1575, This is not fixed yet. However closing this as a duplicate

**Closed** 2017-02-14 03:57 UTC
Labels: bug, duplicate

**Comment by gerosa** [comment] 2017-06-30 18:46
I think this bug didn't go away in the 2.7.0 vesion.

**Comment by dilipkrish** [comment] 2017-07-04 18:10
I think it is probably not fixed too. I meant to annotate the issue but I guess I hadn't. The main reason that we don't traverse method parameter annotations is because it could be pretty expensive depending on how one might use the interface definitions (read multiple inheritance, deep heirarchy, etc.) So as a result, for parameter annotations alone we would expect a custom `ParameterBuilderPlugin` implementation that will traverse the hierarchy or place those annotations alone in the implementation class.
