### ISSUE TITLE
Customizing swagger-ui.html location for groups

### ISSUE THREAD

**Issue by jeanchang22** [springfox/springfox#1355] opened 2016-06-22 23:59 UTC
I want to reopen a previous issue #1080 , The workaround works only when you have only one group of API, when you have multiple APIs, links from drop down will be invalid.

Could you help to fix it? Thanks.

https://github.com/springfox/springfox/commit/0bb481066e3d20e5f6a69101159f0bf44e998091

**Comment by jeanchang22** [comment] 2016-06-23 00:05
I want to reopen a previous issue #1080 , The workaround works only when you have only one group of API, when you have multiple apis, links from drop down will be invalid.

Could you help to fix it? Thanks.

https://github.com/springfox/springfox/commit/0bb481066e3d20e5f6a69101159f0bf44e998091

**Comment by dilipkrish** [comment] 2016-08-25 10:30
This is a duplicate of #1434

**Closed** 2016-09-25 17:21 UTC
Labels: duplicate
