### ISSUE TITLE
Provide custom resource grouping strategy

### ISSUE THREAD

**Issue by smwurster** [springfox/springfox#1039] opened 2015-11-06 14:22 UTC
How can I provide my own resource grouping strategy (i.e. implementation of `ResourceGroupingStrategy`).  There does not seem to be a hook at the `Docket` level.  I tried setting one up as a `@Bean` but it didn't seem to get picked up.  Is there some other mechanism?

:question:

**Comment by dilipkrish** [comment] 2015-11-06 14:54
Its deprecated... why do u need it?

**Comment by smwurster** [comment] 2015-11-06 18:34
Under the older swagger springmvc plugin we used a custom grouping strategy.  I was trying to port that over to springfox.

Does the `tags` concept in `@Api` and `@ApiOperation` effectively replace the need for a custom grouping strategy?  If so, how can I control the text that comes out for each group in the swagger ui?  Right now if I define a class with `@Api(tags="Inventory")`, this comes out as `inventory-controller` in the swagger ui.  I have a routine in a different class that defines `@ApiOperation(tags="Inventory")`, that will show up under its own section called `Inventory: Inventory Controller`.  I want them all under the same section that's just called `Inventory`.  How do I do that?

**Comment by dilipkrish** [comment] 2015-11-07 02:15
Lil bit of background the earlier spec was a 2 step protocol, 
1. you ask for all swagger api listings and get back a bunch of references
2. you use the references and get all the listing definitions

Swagger 2 does not have this idea any more. 

Now where does resource grouping come into play?

It used to be the way that api developers would group apis to belong to an api listing. Since we will not need to do that any longer it is no longer used and hence the deprecation. 

To answer your question, yes, tags are the way going forward. However swagger-ui doesn't support it yet.

**Comment by smwurster** [comment] 2015-11-07 12:18
It looks like editor.swagger.io properly supports tags.  But I can't get springfox to generate a JSON spec file that contains the tags as I want them.  Springfox is generating a tag named `inventory-controller` in the spec file even though I define the API with a tag of `Inventory`.

**Comment by RobWin** [comment] 2015-11-13 08:04
Yes, there seems to be an issue. 
If just specify the API name.

`@Api(value="ContactGroupsExport")`

It results in:

```
"tags": [{
    "name":"contactgroupsexport",
    "description":"ContactGroupsExport"
}]
```

But if I specify a tag as well. It results in: 

`@Api(value="Preferences", tags = "PreferencesBlablalbla")`

```
"tags":[{
    "name":"PreferencesBlablalbla",
    "description":"Preferences"
}]
```

But the problem is, that the path operations still have a tag called `preferences`

```
"paths":
{"/rest/preferences/v1/preferences":{
"get":{
   "tags":["preferences"].
...
}
```

**Comment by smwurster** [comment] 2015-12-02 18:05
Is there a commit that goes with this issue being closed?

**Comment by dilipkrish** [comment] 2015-12-02 18:11
@smwurster there isn't :flushed: ... this was the result of a *lets-close-all-issues-marked-question*. Is this a bug? reopen if it is an issue for sure

**Comment by smwurster** [comment] 2015-12-02 18:18
I don't need to provide my own custom resource grouping, but I do need the ability to better control the tags in the generated JSON spec file.  As noted by myself and @RobWin, the tags aren't coming out as expected.  I guess that's a different issue than needing a custom grouping strategy (although the end result is for the same concept).

**Comment by dilipkrish** [comment] 2015-12-02 18:34
@smwurster I think this may have been fixed ... just not released yet. Would either you or @RobWin mind confirming the expected behavior with 2.2.3-SNAPSHOT?

**Comment by dilipkrish** [comment] 2015-12-02 18:34
It was fixed as part of #919

**Comment by smwurster** [comment] 2015-12-02 18:36
Okay, so it's fixed in 2.3.0, which is pending release?

**Comment by dilipkrish** [comment] 2015-12-02 18:38
Thats what I'm trying to do... close as many issues as I can before release :) but a confirmation that its fixed in the current snapshot (2.2.3-SNAPSHOT) would be great.

**Comment by smwurster** [comment] 2015-12-02 18:39
Unfortunately I won't have time to test this anytime soon.  Hopefully @RobWin has the opportunity.

**Comment by dilipkrish** [comment] 2015-12-02 19:19
Im going to close this for now and release 2.3 and we can re-open it if it still doesn't work after release. Cool?

**Closed by dilipkrish** 2015-12-02 19:19 UTC
Labels: bug

**Comment by RobWin** [comment] 2015-12-02 22:21
I can test that tomorrow.

**Comment by RobWin** [comment] 2015-12-03 07:19
Works as expected now. :+1:  Thx.

`@Api(value = "/pets", tags = "Pets", description = "Operations about pets")` results in

"tags":[{"name":"Pets","description":"Operations about pets"}]

and the tag is added tp the paths

```
"paths": {"/pets":
{"post":
{"tags":["Pets"],
..
}}
```

**Comment by RobWin** [comment] 2015-12-03 07:20
In Swagger2Markup I can group the Paths by Tags now:

![image](https://cloud.githubusercontent.com/assets/5815046/11554260/ba02343e-9996-11e5-9e4b-a141404718c3.png)

**Comment by dilipkrish** [comment] 2015-12-03 13:21
yaaay! :tada:

**Comment by dilipkrish** [comment] 2015-12-03 13:22
Thanks for checking @RobWin :bow:

**Comment by RobWin** [comment] 2015-12-03 13:46
You are welcome
