### ISSUE TITLE
position of @ApiOperation is not recognized

### ISSUE THREAD

**Issue by heapifyman** [springfox/springfox#610] opened 2015-03-12 15:39 UTC
I specified the `position` parameter in all `@ApiOperation` annotations in my Controller, but the operations are listed in a different order in the generated swagger-ui.

Am I missing something?

**Comment by dilipkrish** [comment] 2015-03-12 17:09
@heapifyman You can change the ordering by providing your own ordering logic using [apiDescriptionOrdering](https://github.com/martypitt/swagger-springmvc/blob/master/swagger-springmvc/src/main/java/com/mangofactory/swagger/plugin/SwaggerSpringMvcPlugin.java#L354).

**Comment by heapifyman** [comment] 2015-03-12 22:10
That does not seem to be working. I just tried with the following:
```java
.apiDescriptionOrdering(new Ordering<ApiDescription>() {
    @Override
    public int compare(ApiDescription left, ApiDescription right) {
        return left.getDescription().compareTo(right.getDescription());
    }
});
```

If I am not mistaken that should order the descriptions by method names of the controller?
However, that is not what I am get to see in the browser. What am I missing?

**Comment by yetti4** [comment] 2015-03-30 10:17
I encounter the same issue. The expected behavior would be that the `@ApiOperation` annotations get sorted in ascending order by `position` attribute. Would be nice to have this fixed in 1.x branch if not too much work.

**Comment by jfiala** [comment] 2015-04-09 12:00
I'm facing the same with the latest 1.x version 1.0.2.
Additionally, also the @Api - position attribute seems to be ignored, the controllers are always listed in alphabetical order.
This is also not working in version 0.8.8.

**Closed** 2015-04-30 00:55 UTC
Labels: question

**Comment by anishgopalan** [comment] 2017-03-24 05:20
Is the issue still open? I'm see this in 2.x also.

**Comment by dilipkrish** [comment] 2017-03-24 09:06
Its not open and the position is deprecated.

**Comment by anishgopalan** [comment] 2017-03-24 13:23
Okay , thanks for the update.

**Comment by fanjianhang** [comment] 2018-04-13 02:39
@dilipkrish Hi, if i want to order apis, what should i do?

**Comment by dilipkrish** [comment] 2018-04-13 11:12
@fanjianhang Currently it is ordered by path

**Comment by fanjianhang** [comment] 2018-04-18 01:43
@dilipkrish Thanks, i recommend it can order by position or some smart parameter

**Comment by jinyahuan** [comment] 2019-08-24 04:34
I also encountered the same problem.
And found an extended solution, I hope to help you, and may submit a PR later.
Version 2.7.0 is work.
https://github.com/springfox/springfox/issues/732#issuecomment-524518542
