### ISSUE TITLE
How do I eliminate duplicate API operations in  documentaion generated by swagger-springmvc?

### ISSUE THREAD

**Issue by swaggerhelp** [springfox/springfox#655] opened 2015-04-09 01:55 UTC
The API document generated by swagger-ui (assembly/api-docs ) has the operations repeated multiple times. 

The dependency I am using
<dependency>
	    <groupId>com.mangofactory</groupId>
	    <artifactId>swagger-springmvc</artifactId>
	    <version>1.0.2</version>
</dependency>

Thanks

**Comment by dilipkrish** [comment] 2015-04-09 02:10
@swaggerhelp Could you please share how you've configured your application. 

Ideally we'd like to see relevant configuration web.xml/ spring context files/ java configuration. Specially in this case, without that information its a little hard to provide any suggestions definitively.

* See [these guidelines](https://github.com/springfox/springfox/wiki/Issue-Submission) for how to submit an issue.

**Comment by swaggerhelp** [comment] 2015-04-09 04:25
In applicationContext.xml file added the below configuration
<mvc:annotation-driven /> 
<bean class="com.mangofactory.swagger.configuration.SpringSwaggerConfig" />

**Comment by adrianbk** [comment] 2015-04-09 05:52
I suspect that your context is being loaded twice.
This [post explains whats happening](http://stackoverflow.com/questions/26254720/why-two-instances-of-spring-bean-controllers-are-created-in-a-spring-mvc-applica?answertab=votes#tab-top)

**Comment by swaggerhelp** [comment] 2015-04-09 09:25
I checked and there is only DispatcherServlet and no ContextLoaderListener. The context is only loaded once.

**Comment by dilipkrish** [comment] 2015-04-09 14:57
@swaggerhelp could you share your repo? if not atleast create a minimal project with the configuration that reproduces the issue?

**Comment by dilipkrish** [comment] 2015-04-11 01:55
Closing this as its is a duplicate of #630

**Closed by dilipkrish** 2015-04-11 01:55 UTC
Labels: waiting-for-more-info
