### ISSUE TITLE
Iterable<T> documented as empty object instead of array

### ISSUE THREAD

**Issue by rantibi** [springfox/springfox#3022] opened 2019-06-11 17:10 UTC
I was trying to create object with a method that return `Iterable<T> ` and it documented as an empty object instead of T[]. I wish not changing it to List just for documentation.

Example:
```
@Data
public class SimplePojo {

    public Iterable<SimpleInnerPojo> getInnerPojos() {
        return Lists.newArrayList(new SimpleInnerPojo(), new SimpleInnerPojo());
    }

    @Data
    public class SimpleInnerPojo {
        private String a;
    }
}
```

```
@RestController
@RequestMapping(path = "v1/simple_controller")
@Slf4j
public class SimpleController {

    @RequestMapping(path = "/", method = RequestMethod.GET)
    public SimplePojo get() {
        return new SimplePojo();
    }
}
```

Swagger UI shows:
```
{
  "innerPojos": {}
}
```

Instead of:
```
{
  "innerPojos": [
    {
      "a": "string"
    }
  ]
}
```

**Comment by affanshahid** [comment] 2020-07-08 05:50
Having the same issue

**Comment by dilipkrish** [comment] 2020-07-12 23:13
The reason Iterables aren't supported out of the box is cos we dont know the concrete type It represents

**Comment by dilipkrish** [comment] 2020-07-12 23:13
duplicate of #3371

**Closed** 2020-07-12 23:13 UTC
Labels: has-workaround

**Comment by erizzo** [comment] 2022-06-06 22:42
> The reason Iterables aren't supported out of the box is cos we dont know the concrete type It represents

I'm missing something. How is that different than `Collection<>`, which does work as expected right out of the box?
