### ISSUE TITLE
swagger 1.2 group no longer works with 2.7.0

### ISSUE THREAD

**Issue by mathieuales** [springfox/springfox#2024] opened 2017-09-07 07:54 UTC
Hi !

I was trying to upgrade from 2.6.1 to 2.7.0, but it appears defining groups doesn't work anymore using swagger 1.2 (everything is ok with swagger 2): 

`org.springframework.web.bind.MissingPathVariableException: Missing URI template variable 'swaggerGroup' for method parameter of type String`

```java
@Configuration
@EnableSwagger
public class SwaggerConfiguration {

	@Bean
	public Docket publicSwaggerApiDocs(@Value("${swagger.enabled}") boolean enabled, @Value("${swagger.host}") String swaggerHost,
			@Value("${swagger.basePath}") String swaggerBasePath, @Value("${version}") String apiVersion) {
		Docket docket = new Docket(DocumentationType.SWAGGER_12).groupName("public").select().apis(publicRestControllers()).build()
				.apiInfo(publicApiInfo(apiVersion)).pathProvider(pathProvider(swaggerBasePath)).enable(enabled);
		return docket;
	}
       ...
```

**Comment by dilipkrish** [comment] 2017-09-14 01:30
@mathieuales Swagger 1.2 is barely requested and supported. There is another issue I believe thats a duplicate of this. I'll investigate but no promises.

**Comment by dilipkrish** [comment] 2017-12-07 01:42
@mathieuales I looked at this. This is a bug in swagger-ui. So my suggestion to you is to use swagger-ui web jar version 2.6.1 along with 2.7.0 swagger library.

**Closed by dilipkrish** 2017-12-07 01:42 UTC
Labels: in progress, question, wontfix
