### ISSUE TITLE
Feature Request: Upgrade swagger2markup version to v1.0.0

### ISSUE THREAD

**Issue by fayndee** [springfox/springfox#1299] opened 2016-05-04 13:20 UTC
Is there any plan to upgrade swagger2markup version from 0.9.2 to 1.0.0?

Swagger 2.0 added `operationId` to uniquely identify an API operation, which is also supported in swagger2markup-1.0.0. Currently the latest version of springfox-staticdocs (v2.4.0) only supports swagger2markup-0.9.2. It would be nice to have the latest features of swagger2markup supported as well.

**Comment by dilipkrish** [comment] 2016-05-04 17:33
We welcome PRs! :)

**Comment by dilipkrish** [comment] 2016-06-01 20:58
@RobWin looks like a lot has changed since s2m went 1.0 😕   Could point me in the right direction? (or perhaps upgrade the library)
```java
        Swagger2MarkupConverter
                .fromString(swaggerJson)
                .withMarkupLanguage(markupLanguage)
                .withExamples(examplesFolderPath).build() //< -- whats the equivalent of this?
                .intoFolder(outputDir);
```

**Comment by dilipkrish** [comment] 2016-06-02 14:16
This requires JDK 8 so pushing this out

**Comment by dilipkrish** [comment] 2016-10-26 01:15
Closing as a duplicate of #1497

**Closed by dilipkrish** 2016-10-26 01:15 UTC
Labels: duplicate, feature
