### ISSUE TITLE
springfox.js requires swagger-ui.html to be the entry point

### ISSUE THREAD

**Issue by mongofish** [springfox/springfox#794] opened 2015-06-15 19:28 UTC
In previous version of springfox-swagger-ui (2.0.0), you could customize the entry point for documentation by creating a controller for swagger-ui.html, as shown here:
https://github.com/springfox/springfox-demos/blob/master/boot-swagger/src/main/java/springfoxdemo/boot/swagger/web/HomeController.java

On head, `baseUrl` function in `springfox.js` requires swagger-ui.html in the url, making this impossible.

**Comment by jcogilvie** [comment] 2015-06-26 17:00
+1, this is an annoying regression because dropping in an updated webjar will break previously-working doc if you have it configured in this manner.

**Comment by dilipkrish** [comment] 2015-06-26 18:06
You could simply use a `redirect:/swagger-ui.html`  instead.

**Comment by dilipkrish** [comment] 2015-06-26 20:21
Updated the demo example to show how its done. [See here](https://github.com/springfox/springfox-demos/commit/13a1eb4db5dadf6408c39a73bf3dc7fd3cd0685e)

**Comment by dilipkrish** [comment] 2015-08-11 02:56
Closing this as this has a work around

**Closed by dilipkrish** 2015-08-11 02:56 UTC
Labels: has-workaround, wontfix

**Comment by jcogilvie** [comment] 2015-08-11 03:10
This is particularly painful if you are using springfox as a high-level maven dependency inherited by lots of projects.  If the parent upgrades springfox, every end-service has to change a controller.  In my case, this was in the tens to hundreds of projects.

**Comment by dilipkrish** [comment] 2015-08-11 03:22
True! however being a library it is not a generalization (the `/` (root) always redirecting to swagger-ui.html) that everyone is going to like being foisted on.

Open to suggestions, of course.

**Comment by jcogilvie** [comment] 2015-08-11 03:28
The problem with the current implementation is that the client page requires swagger-ui.html to be present in the page URL.  One couldn't actually rename the page, or it would break, so I think that's kind of inflexible/being forced upon developers.  So you can't actually use anything *other than* a redirect to swagger-ui.html, wherever you put it.  

I'm a server-side developer, mostly, and this is a client-side problem, so my ability to provide suggestions is limited.  If it were a server problem I'd say an environment variable passed on the command line or something, but we really don't have that option here... =/

**Comment by dilipkrish** [comment] 2015-08-11 03:43
Just playing devils advocate here, it should be fairly straightforward for you to create a small library internally that does this redirection and have this "home" controller register itself automatically with spring no? 

At the end of the day Its the same thing as you're expectation of this library is, I would think. Or atleast the same amount of work as including this library.

**Comment by jcogilvie** [comment] 2015-08-11 03:47
It's more complicated because at the top level everything is in
<dependencyManagement> which requires consumers to opt in to consuming such
a library. They've already opted into springfox this way, but they got
broken by the change that required this, hence the regression label.

In any case I no longer work there, but I do think this should be fixed to
not depend on the file name in the url! =)
