### ISSUE TITLE
Swagger-UI requests /api-docs ~180 times

### ISSUE THREAD

**Issue by timothysoehnlin** [springfox/springfox#809] opened 2015-06-22 22:09 UTC
When setting up swagger-ui with a spring boot application (groovy based), the swagger-ui seems to make around 180 requests to /api-docs.  All requests are identical, but it seems to request all of them, and wait for all them to resolve before initializing the UI.  

Not certain if the issue is with springfox or swagger.  I've used swagger before without issue, but this is my first foray into springfox's implementation.

**Comment by dilipkrish** [comment] 2015-06-22 22:15
Not really sure. A lil bit of background would help. What browser are u using? What does your docket/configuration look like? If you have a repo that demonstrates this that would be awesome

**Comment by timothysoehnlin** [comment] 2015-06-22 22:18
The repo is private, so unable to share that.  I'm using chrome.  The setup I have is basically what was in the springfox spring boot ui setup, with the slight change to the api selector only looking at a specific base package:

     return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage(pkg))
                .paths(PathSelectors.any())
                .build()
                .pathMapping("/")
                .directModelSubstitute(LocalDate.class, String)
                .genericModelSubstitutes(ResponseEntity)
                .alternateTypeRules(
                newRule(typeResolver.resolve(DeferredResult,
                        typeResolver.resolve(ResponseEntity, WildcardType)),
                        typeResolver.resolve(WildcardType)))
                .useDefaultResponseMessages(false)
                .globalResponseMessage(RequestMethod.GET,
                newArrayList(new ResponseMessageBuilder()
                        .code(500)
                        .message("500 message")
                        .responseModel(new ModelRef("Error"))
                        .build()))

**Comment by timothysoehnlin** [comment] 2015-06-22 22:29
As a note, I am running version 2.0.2 of the entire setup (springfox ui/swagger2) and 1.5.0 of the swagger models.

**Comment by dilipkrish** [comment] 2015-06-22 22:36
How many apidocs do you have in the drop down in swagger-ui?

**Comment by timothysoehnlin** [comment] 2015-06-22 22:40
There is only one item in the drop down.  The number of endpoints also
exposed is far less than 180.  It almost seems like some timing issue and
that it continues to request until some limit is hit.  Not 100% certain.

**Comment by dilipkrish** [comment] 2015-06-22 23:12
Try removing the `.pathmapping("/")`

**Comment by timothysoehnlin** [comment] 2015-06-23 10:44
That seems to have had no effect.  I've debugged the code even further, and I believe I found the culprit, but no idea how to fix it.

For some of my endpoints, there is a 500 response that is being captured (and subsequently resolved after loading of the API).  The endpoint does not throw any exceptions as far as I can tell, and so I'm not entirely  certain where this $ref is coming from.  

The structure for the response section of the listing is as such:

    { 
        "500" : {
             "description" : "500 error message",
             "schema" : {
                  "$ref" : "#/definitions/Error"
              }
        }
    }

**Comment by timothysoehnlin** [comment] 2015-06-23 11:10
So I have identified the offending code:

    .globalResponseMessage(RequestMethod.GET,
            newArrayList(new ResponseMessageBuilder()
                    .code(500)
                    .message("500 message")
                    .responseModel(new ModelRef("Error"))
                    .build()))

This was in the [springfox spring boot sample setup](http://springfox.github.io/springfox/docs/snapshot/#springfox-swagger2-with-spring-boot).  This added a defined error response to all GET methods.  For some reason the model ref is generating '#/definitions/Error' which is causing a reload of the /api-docs endpoint every time it wants to resolve the '$ref' for 'Error'.

From the sample config page, regarding the 

    ModelRef("Error")

It states

    …​and indicate that it will use the response model Error (which will be defined elsewhere)  

By not having this defined, this seems to break down the expected behavior, and causes swagger to request the /api-docs every time it sees the '#/definitions/Error' $ref.

**Comment by dilipkrish** [comment] 2015-06-24 15:03
I'm not able to reproduce this error. May be you could fork the spring boot sample and help reproduce this problem? Closing this issue for now, feel free to reopen

**Closed by dilipkrish** 2015-06-24 15:03 UTC
Labels: not-reproducable

**Comment by architkansal** [comment] 2017-07-05 05:40
i am getting the exact same error. Is there some way i can fix it? I can't find any steps to follow in above discussion. I have ModelRef("Error") in my config file, which takes me to ModelRef.class in springfox.documentation.schema.
