### ISSUE TITLE
NPE when 2 dockets are used and only one of them has a groupName

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#856] opened 2015-07-17 16:09 UTC
Seen on v2.1.0 (was not happening on 2.0.3)

Config to reproduce:
```java
    @Bean
    public Docket fullApi() {
        return new Docket(DocumentationType.SWAGGER_2)
        .select()
        .paths(paths())
        .build()
        ...

    @Bean
    public Docket publicApi() {
        return new Docket(DocumentationType.SWAGGER_2)
        .groupName("public")
        .select()
        .paths(paths())
        .build()
        ...
```
The NPE happens in springfox.documentation.spi.service.contexts.Orderings::byPluginName()
```java
public static Comparator<? super DocumentationPlugin> byPluginName() {
    return new Comparator<DocumentationPlugin>() {
      @Override
      public int compare(DocumentationPlugin first, DocumentationPlugin second) {
        return first.getGroupName().compareTo(second.getGroupName());
      }
    };
  }
```
because compareTo() is not null-safe and second.getGroupName() is null.

Stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
	at java.lang.String.compareTo(String.java:1142)
	at springfox.documentation.spi.service.contexts.Orderings$10.compare(Orderings.java:136)
	at springfox.documentation.spi.service.contexts.Orderings$10.compare(Orderings.java:133)
	at com.google.common.collect.CompoundOrdering.compare(CompoundOrdering.java:43)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
	at java.util.TimSort.sort(TimSort.java:216)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.google.common.collect.Ordering.sortedCopy(Ordering.java:809)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:82)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:51)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
```

**Comment by kevinconaway** [comment] 2015-07-17 16:16
Discussing this in #855

**Comment by dilipkrish** [comment] 2015-07-17 16:39
Closing this as its a duplicate of #855

**Closed by dilipkrish** 2015-07-17 16:39 UTC
