### ISSUE TITLE
swagger-ui refresh

### ISSUE THREAD

**Issue by Robert-Leggett** [springfox/springfox#715] opened 2015-04-29 05:20 UTC
Once you select an endpoint e.g. http://localhost:8080/restful/swagger-ui.html#!/admin-controller/grantMembershipUsingPOST and then press F5 the page reloads and loads the petstore example rather then project selected.

**Comment by hestad** [comment] 2015-04-29 10:39
Duplicate of #713

**Comment by dilipkrish** [comment] 2015-04-30 00:44
Closing as its a duplicate

**Closed by dilipkrish** 2015-04-30 00:44 UTC
Labels: duplicate
