### ISSUE TITLE
Is it possible to disable globalResponseMessage configuration partially.

### ISSUE THREAD

**Issue by dohoon-oh** [springfox/springfox#2023] opened 2017-09-07 03:52 UTC
Is it possible to disable globalResponseMessage configuration partially.

This is a question.

I'm using v2.7.0 in my SpringBoot project.
So I disabled default response message and configure global responses like the followings :

```
@Bean
public Docket defaultDoc() {
    	return new Docket(DocumentationType.SWAGGER_2)
       		.groupName("default")
       		.select()
       		.apis(bases())
       		.paths(defaultPaths())
       		.build()
       		.apiInfo(getApiInfo())
       		.useDefaultResponseMessages(false)
       		.directModelSubstitute(LocalDate.class, java.util.Date.class)
       		.directModelSubstitute(LocalDateTime.class, java.util.Date.class)
       		.globalResponseMessage(RequestMethod.GET, 
          		Lists.newArrayList(
				new ResponseMessageBuilder().code(204).message("There is no content.").build(),
				new ResponseMessageBuilder().code(405).message("Parameter is invalid.").build(),
				new ResponseMessageBuilder().code(500).message("Failed to process request").build()
            		)
            	);
    }
```

It works well, but one of restful APIs does not use 405 response because there is no parameter for the API. So I hope to hide 405 response at that API, but there is no way to hide global response message by either @ApiResponses or @ApiResponse.

Is it possible to hide one or more responses defined in globalResponseMessage configuration?

**Comment by dilipkrish** [comment] 2017-09-14 01:31
This is currently not possible. However I think there is an issue to support that. Don't know if I'll be able to get to it given the huge backlog :) Thanks for reporting

**Comment by dilipkrish** [comment] 2018-01-03 05:34
Closing as a duplicate of #1910

**Closed** 2018-01-03 05:35 UTC
Labels: current, duplicate, feature
