### ISSUE TITLE
API Model / Model Schema pulling wrong Object of same name from different package

### ISSUE THREAD

**Issue by jakepharr2** [springfox/springfox#1252] opened 2016-04-07 17:08 UTC
Encountered issue where Swagger is generating incorrect API documentation for an Object containing another Object in the same package, but the docs generated refer to the Object that has the same name, but is in another package. Simplified example below:

version 2.4.0

Bug report
Java code example

```
package com.bar.foo.abc.somepackage

@JsonIgnoreProperties(ignoreUnknown = true)
public class Body {
	private String name;
	private long id;
	private Foo foo;
}



package com.bar.foo.abc.somepackage

@JsonIgnoreProperties(ignoreUnknown = true)
public class Foo {
	private String bar;
}

package com.bar.foo.abc.someotherpackage

@JsonIgnoreProperties(ignoreUnknown = true)
public class Foo {
	private String someString;
	private boolean ok;
}

```
Swagger-UI output:

```
Body {
	name (String, optional),
	id (long, optional),
	foo(foo, optional),
}
Foo {
	someString (string, optional),
	ok (boolean, optional)
}
```

Expected output:

```
Body {
	name (String, optional),
	id (long, optional),
	foo(foo, optional),
}
Foo {
	bar (string, optional)
}

```

**Comment by dilipkrish** [comment] 2016-04-07 17:10
This is a duplicate of #182

**Closed by dilipkrish** 2016-04-07 17:10 UTC
Labels: duplicate

**Comment by jakepharr2** [comment] 2016-04-07 19:08
My bad. Thanks.
