### ISSUE TITLE
Bug report: ApiImplicitParam and primitive types breaks in 3.0.0

### ISSUE THREAD

**Issue by sigand** [springfox/springfox#3388] opened 2020-07-14 10:30 UTC
implementation "io.springfox:springfox-boot-starter:3.0.0"

With the following kinds of annotation  usage

`@ApiImplicitParam(name = "name", paramType = "query", dataType = "int")`
`@ApiImplicitParam(name = "name", paramType = "query", dataType = "String")`

Documentation for ApiImplicitParam for dataType states "This can be the class name or a primitive."

OperationImplicitParameterReader(line 167) logs warnings with 
`Unable to interpret the implicit parameter configuration with dataType: int, dataTypeClass: class java.lang.Void `
after `Class.forName(param.dataType());` fails with ClassNotFoundException

It consistently fails with primitive types, though a fully qualified class name solves the issue

The same seems to be happening also with @ApiParam, though without any log entries. Parameter then defaults to object

**Comment by dilipkrish** [comment] 2020-07-14 11:39
This is by design. While we use the annotations we rely on the correctness of the values. It's valid to expect primitives to work, but that is not how it is setup. I believe this behavior is also documented.

**Comment by sigand** [comment] 2020-07-14 11:45
Then  the documentation should be updated to remove the part where it says ** or a primitive.**

**Comment by dilipkrish** [comment] 2020-07-14 12:25
This is an oversight when upgrading to a newer model generation machinery. Thanks for reporting.

**Comment by dilipkrish** [comment] 2020-07-14 20:52
Just to clarify, the annotations dont belong to this project, if you're referring to the javadocs. This [is the documentation](http://springfox.github.io/springfox/docs/current/#overriding-property-datatypes) I was referring to

**Comment by dilipkrish** [comment] 2020-07-15 02:17
Fixed via https://github.com/springfox/springfox/commit/3cd0f7ccccc26b79c60851fbb04fca95d2d7ea33

**Closed by dilipkrish** 2020-07-15 02:17 UTC
Labels: bug
