### ISSUE TITLE
@ApiParam(example = "...") not working

### ISSUE THREAD

**Issue by ketulvinayshah** [springfox/springfox#1172] opened 2016-02-10 18:57 UTC
```java
    private static final String template = "Hello, %s!";

    @RequestMapping(value = "/greeting", method = RequestMethod.GET)
    @ApiOperation(value = "Greetings For User")
    public Greeting greeting(@RequestParam(value="name") 
                             @ApiParam(example = "Swagger") String name) {
        return new Greeting(counter.incrementAndGet(),
                String.format(template, name));
    }
```
------------------------------Output----------------------------------

```json
{
    "basePath": "/",
    "definitions": {},
    "host": "localhost:8080",
    "info": {},
    "paths": {
        "/error": {},
        "/greeting": {
            "get": {
                "consumes": [],
                "operationId": "greetingUsingGET",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name",
                        "required": false,
                        "type": "string"
                    }
                ],
                "produces": [],
                "responses": {},
                "summary": "Greetings For User",
                "tags": []
            }
        }
    },
    "swagger": "2.0",
    "tags": []
}
```

**Comment by ketulvinayshah** [comment] 2016-02-10 19:02
@dilipkrish - Can you please help? I need to provide examples of sensible params for my API

**Comment by dilipkrish** [comment] 2016-02-10 22:29
@ketulvinayshah Yeah this isn't supported yet. Closing this as a duplicate of #853

**Closed by dilipkrish** 2016-02-10 22:29 UTC
