### ISSUE TITLE
Springfox creates model ends with suffix _1

### ISSUE THREAD

**Issue by jyeoniii** [springfox/springfox#3243] opened 2020-01-31 04:58 UTC
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
3.0.0-SNAPSHOT, springfox-core-3.0.0-20200106.122158-51

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [x] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful. 

---

Hello, I am using springfox 3.0.0-SNAPSHOT with spring webflux.
I've found that the swagger generates the model ends with suffix _1, _2... like below in some cases.
![screenshot](https://user-images.githubusercontent.com/23377267/73513105-81335c80-442f-11ea-926f-511c65950543.png)
(I've seen #3014 also has similar issue. But this this is not the case when using JPA and the issue still exists even after the fixed PR get merged. 

The case I met was when using `org.springframework.data.domain.Page` and it seems `getPageable()` does matter. 
```
default Pageable getPageable() {
	return PageRequest.of(getNumber(), getSize(), getSort());
}
```
Here's the sample repository where I reproduce the issue (https://github.com/jyeoniii/swagger-webflux-sample)
Could you take a look at it?

**Comment by jyeoniii** [comment] 2020-01-31 08:17
Also, I have an additional question. While debugging it, I saw the `registerType()` and `registerUniqueType()` method in `UniqueTypeNameAdapter`. What makes the difference between them?

**Comment by MaksimOrlov** [comment] 2020-02-05 15:38
@jyeoniii, `registerType()` will register type, that it the same as we found before,  `registerUniqueType()` will make type name unique, if we haven't faced that type before.

**Comment by MaksimOrlov** [comment] 2020-02-05 15:39
Duplicate of #3014

**Comment by MaksimOrlov** [comment] 2020-02-08 22:08
Here is the PR #3247 to fix this issue.

**Closed** 2020-02-24 12:27 UTC
Labels: duplicate

**Comment by MaksimOrlov** [comment] 2020-02-24 13:36
PR with fixes has been merged.

And I'll be grateful for your feedback, if the issue was gone. 
Otherwise feel free to reopen the issue.
