### ISSUE TITLE
Request:Changing the endpoint swagger-ui.html

### ISSUE THREAD

**Issue by igorng** [springfox/springfox#1188] opened 2016-02-24 22:06 UTC
Hello,

thanks  fr the great work.

It would be nice to be able to change the endpoint served when using swagger-ui (swagger-ui.html) trhoug a property config or something like that.

Thanks

**Comment by dilipkrish** [comment] 2016-02-25 05:11
Closing this as a duplicate of #1080

**Closed by dilipkrish** 2016-02-25 05:11 UTC

**Comment by emreaydin52** [comment] 2020-03-19 11:59
You refer to this page from the duplicate one and refer to the original @dilipkrish. This issue is not still resolved.
