### ISSUE TITLE
Slow Startup - Spring Boot

### ISSUE THREAD

**Issue by bryantp** [springfox/springfox#811] opened 2015-06-23 14:00 UTC
I am experiencing very slow document generation related to SpringFox in Spring Boot. It takes around 30 minutes to complete, and generally stays stuck at these kind of lines:

    09:54:51.244 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method home was welcome-controller

and then slowly goes through the rest of the controllers. My controllers are all in the **com.my.app.controllers** package. Here is my Swagger Config file:

```
@EnableSwagger2
@Configuration
public class SwaggerConfig {

    @Bean
    public Docket customImplementation(){
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("test-app")
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(not(regex("/error/.*")))
                .build()
                .securitySchemes(newArrayList(getBasicAuthCredentials()));
    }

    private BasicAuth getBasicAuthCredentials(){
        return new BasicAuth("superuser");
    }
}
```

and my application entry point

```
@Configuration
@ComponentScan(basePackages = "com.my.app")
@EnableAutoConfiguration
@EnableScheduling
@EnableAsync
public class Main extends SpringBootServletInitializer {

    private static Logger logger = LogManager.getLogger(Main.class);

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(Main.class);
    }

}
```

I also noticed that it is going through a particular method multiple times:

```
09:57:42.721 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.724 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.727 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.729 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.731 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.733 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.736 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
09:57:42.738 [RMI TCP Connection(3)-127.0.0.1] INFO  springfox.documentation.swagger.web.ClassOrApiAnnotationResourceGrouping 69 - Group for method user was tenancy-controller
```

This is my first time using Swagger and SpringFox. Thanks for any help!

**Comment by dilipkrish** [comment] 2015-06-23 14:27
@bryantp Thanks for reporting this is already in the works to be fixed. Closing this as a duplicate of #806

**Closed by dilipkrish** 2015-06-23 14:27 UTC
Labels: bug

**Comment by bryantp** [comment] 2015-06-23 14:37
Thanks for the quick response! Does SpringFox support disabling Doc Generation on startup/runtime? I will just have it generate the documentation on maven build instead.

**Comment by dilipkrish** [comment] 2015-06-23 16:43
Have you looked at https://github.com/RobWin/swagger2markup by @RobWin 👌🏼

**Comment by RobWin** [comment] 2015-06-23 17:25
If you need help, then join the Gitter channel. I can tell you how to use springfox only at unit test / build time.

**Comment by bryantp** [comment] 2015-06-23 17:54
I shall hop on the Gitter. Thanks guys.

**Comment by mjallday** [comment] 2015-08-18 20:28
In case anyone stumbles across this and wants to know what @RobWin's pro tip was that he alludes to:

> Hey @RobWin. I hear you can tell me how to use springfox only at unit test / build time. springfox/springfox#811 
>
> RobWin 10:03
> Hi, yes. Just add a Spring @Profile to your Springfox's Spring JavaConfig and use the Profile only in your unit test
> Or move the Springfox JavaConfig into src/test/java and use a ContextConfiguration
> Have a look at https://github.com/Swagger2Markup/spring-swagger2markup-demo/blob/master/src/test/java/io/github/robwin/swagger2markup/petstore/Swagger2MarkupTest.java

**Comment by dilipkrish** [comment] 2015-08-19 01:16
@mjallday :+1:
