### ISSUE TITLE
List of genericModelSubstitutes

### ISSUE THREAD

**Issue by rlogiacco** [springfox/springfox#616] opened 2015-03-14 22:28 UTC
In my controller I have a return value of type `List<Resource<MyClass>>`, where `Resource` is configured for generic model substitution.
I want to have the documentation reporting a list of `MyClass`, but the docs report a list of `Resource`: what am I missing?

**Comment by dilipkrish** [comment] 2015-03-19 04:04
Is this not working? Have you created a generic model substittute for ```Resource```?

**Comment by dilipkrish** [comment] 2015-04-04 00:42
@rlogiacco Explanation of how to fix this is in #526. Closing this issue

**Closed by dilipkrish** 2015-04-04 00:42 UTC
Labels: waiting-for-more-info

**Comment by rlogiacco** [comment] 2015-04-04 11:06
As stated in my last post on #526 that works in case of Collection<Model>, but when you have a List<Substitute<Model>> (with Substitute registered for generics substitution) it doesn't work.
The problem relies into the substitution model search which is applied once instead of being repeated through.
I can post a sample case and a possible fix if you wish as I've fixed this for my particular case.

**Comment by dilipkrish** [comment] 2015-04-04 19:21
@rlogiacco you're **100% correct** that it will not work for the case where you have a rule to replace ```Resource<T>``` with ```T``` and another rule that replaces ```ResponseEntity<T>``` with ```T``` and you're expecting that ```ResponseEntity<Resource<T>>``` to be replaced with ```T```.

This is by design. We would rather rely on the library user telling us how to replace a given type explicitly than be intelligent and getting it mostly correct; more on that in a bit. In the above example we prefer that the library user tell us that when you see a ```ResponseEntity<Resource<T>>``` please replace that with a T.

The reason I say mostly correct is that, currently we do a one pass breadth first search and replace. While it can get it right for most cases, it may falter if you have a more specific rule defined. Say you wanted to replace ```Resource<Pet>``` to ```Resource<Dog>``` and the rules you had in place were
- Replace ```ResponseEntity<T>``` with ```T```
- Replace ```Resource<T>``` with ```T```d
- Replace ```Resource<Pet>``` to ```Resource<Dog>``` 

How would you think its replaced if we had the following situation? ```ResponseEntity<Resource<Map<String, Resource<Pet>>>``` and would the answer be different if we did a breadth first replace, vs a depth first replace? would it be different if we had a *n pass* replacement?  Now we have to think about the order of rules and rule priorities. The order in which rules are defined suddenly would matter. 

So, to keep things simple, rather than solve the problem generically we rely on the framework user to tell us how to replace something in their situation **explicitly**. Hope that clarifies why I'd like to push back on this. 

If you think we can improve that workflow, we'd love to hear it.
