### ISSUE TITLE
[Question]I got a error message while getting Swagger UI

### ISSUE THREAD

**Issue by haohll1984** [springfox/springfox#2685] opened 2018-09-15 03:25 UTC
I'm getting the following output on a GET from my swagger page:
`java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_172]
	at java.lang.Long.parseLong(Long.java:601) ~[na:1.8.0_172]
	at java.lang.Long.valueOf(Long.java:803) ~[na:1.8.0_172]
	at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:412) ~[swagger-models-1.5.20.jar:1.5.20]
	`
while I set a custom example to ApiResponse like below:
` @ApiResponse(examples = @io.swagger.annotations.Example(value = @ExampleProperty("[]")),
                    code = 200, message = "OK")`

so what should I do if I want to change the example values of Response?

**Comment by dilipkrish** [comment] 2018-09-15 16:07
This is a duplicate of #2620

**Closed by dilipkrish** 2018-09-15 16:07 UTC
Labels: duplicate
