### ISSUE TITLE
Models with different packages are not represented uniquely in the generated swagger document

### ISSUE THREAD

**Issue by tenstriker** [springfox/springfox#1008] opened 2015-10-14 18:53 UTC
I have two version of same POST API. One is written in Java and another one in scala. They both have a request parameter called 'DataRequest' but one is java and one is in scala. i.e. com.mycompany.java.DataRequest and com.mycompany.scala.DataRequest. However in swagger I only see scala version of DataRequest in body parameter. If I remove scala based controller from swagger 'paths' then I do see java version of DataRequest. I read about this issue in spec but I can't find them again and can someone explain how to resolve that?

**Comment by dilipkrish** [comment] 2015-10-15 01:47
@tenstriker this is an annoying problem I don't think it has anything to do with the spec as much as the tooling around it. Unfortunate when I say tooling it includes SpringFox. We could solve this problem by adding a fully namespace qualified name, but we don't always want that either :confused: We only want it when there are two models with the same *Class* name.

**Comment by tenstriker** [comment] 2015-10-19 17:53
When you say " We only want it when there are two models with the same Class name. " I think that is what my case is . Two model DataRequest with same name and different fqn.

**Comment by GlennVanSchil** [comment] 2016-02-10 10:43
+1 I need this feature as well

**Comment by dilipkrish** [comment] 2016-02-28 21:16
Closing this a a duplicate of #182

**Closed by dilipkrish** 2016-02-28 21:16 UTC
Labels: feature
