### ISSUE TITLE
Regression in v2.5.0: generic REST parameters in Spring MVC

### ISSUE THREAD

**Issue by alex-konkov** [springfox/springfox#1360] opened 2016-06-26 10:16 UTC
After updating to v2.5.0 the Swagger UI crashes with error in JS console:
`client.js:60 Uncaught TypeError: Cannot read property 'type' of undefined`

This happens if any method has generic parameters, e.g. as follows:
`public void someMethod(@RequestParam MultiValueMap<String, String> params) { ... }`

Before v2.5.0 Swagger UI was able to work with such generic parameters well, so it's apparently a regression.

**Comment by dilipkrish** [comment] 2016-06-26 13:41
I've added an [issue in the swagger-ui project](https://github.com/swagger-api/swagger-ui/issues/2241).

**Comment by dilipkrish** [comment] 2016-06-26 13:43
closing this as a duplicate of #1353

**Closed by dilipkrish** 2016-06-26 13:43 UTC
Labels: duplicate, wontfix
