### ISSUE TITLE
How to write a custom ApiListingScannerPlugin?

### ISSUE THREAD

**Issue by indrabasak** [springfox/springfox#1797] opened 2017-05-02 17:30 UTC
Using `springfox 2.6.1`

I wrote a custom `ApiListingScannerPlugin` extension. My example plugin is similar to [Bug1767ListingScanner.java](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/main/java/springfox/test/contract/swagger/Bug1767ListingScanner.java).

It's not getting picked up by `DocumentationPluginsManager`. I wrote other types of springfox plugins and they work fine. What am I doing wrong here?

Here is my example code:
```java
@Component
@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER + 1003)
@Slf4j
public class ExampleApiListingScanner implements ApiListingScannerPlugin {

    @Override
    public List<ApiDescription> apply(DocumentationContext context) {
        List<ApiDescription> descps = new ArrayList<>();
        descps.add(createApiDescription());

        return descps;
    }

    @Override
    public boolean supports(DocumentationType documentationType) {
        return true;
    }

    private ApiDescription createApiDescription() {
        ApiDescription desc = new ApiDescription(
                "/elephants/children",
                "This is an AP Listing Scanner example ",
                Arrays.asList(createOperation()),
                false);

        return desc;
    }

    private Operation createOperation() {
        ParameterBuilder paramBldr = new ParameterBuilder();
        paramBldr.description("search by child's name")
                .type(new TypeResolver().resolve(String.class))
                .name("name")
                .parameterType("query")
                .parameterAccess("access")
                .required(true)
                .modelRef(new ModelRef("string"));
        Parameter param = paramBldr.build();

        OperationBuilder bldr =
                new OperationBuilder(new CachingOperationNameGenerator());
        bldr.authorizations(new ArrayList())
                .codegenMethodNameStem("readChildrenGET")
                .method(HttpMethod.GET)
                .notes("This is a dynamic method to fetch elephant children")
                .parameters(Arrays.asList(param));

        Operation op = bldr.build();

        return op;
    }
}
```

**Comment by dilipkrish** [comment] 2017-05-02 17:32
This is a duplicate of #1767

**Closed by dilipkrish** 2017-05-02 17:32 UTC
