### ISSUE TITLE
cannot override basepath in swaggerfox 3.0

### ISSUE THREAD

**Issue by thomasmey** [springfox/springfox#3493] opened 2020-08-13 13:04 UTC
as i don't know how to re-open an already closed issue:
https://github.com/springfox/springfox/issues/2817

**Comment by dilipkrish** [comment] 2020-08-16 00:39
You can override it today, however it may have unintended consequences, I believe this is a duplicate of #3445 which I hope to add better usability around in 3.0.1.

**Comment by mikesmithson** [comment] 2020-08-26 13:26
I am having an issue of not even seeing a basepath when I have specified a basepath that is not '/'. Is this something that is a feature or a bug?

**Comment by dilipkrish** [comment] 2020-09-05 14:23
Its an issue that some folks have reported and it is true that it is always @ `/` since 3.0.0. Follow the above issue for a fix

**Closed** 2020-12-18 16:58 UTC
Labels: duplicate, question, wontfix
