### ISSUE TITLE
Feature Request: Please add support for spring-webflux (spring boot 2.0 / spring 5)

### ISSUE THREAD

**Issue by bastman** [springfox/springfox#1809] opened 2017-05-10 04:56 UTC
I was lately playing around with spring-webflux, the new reactive microframework by spring 5.

I tried to integrate springfox swagger & swagger-ui into a webflux application, but it failed.
It looks like there are hardcoded dependencies to spring mvc.

(see: https://github.com/bastman/skeleton-springboot-webflux-kotlin )

Are there any plans to integrate with webflux? 
Spring boot 2.0 - including webflux is close to the first RC release. I would love to have springfox swagger working with that.

Thanks.

**Comment by dilipkrish** [comment] 2017-05-18 05:50
Yes there is definitely plans to support it. Closing this a duplicate of #1773

**Closed** 2017-05-18 05:51 UTC
Labels: duplicate
