### ISSUE TITLE
Setting jackson.serialization.wrap_root_value=true in application.properties, crash swagger UI

### ISSUE THREAD

**Issue by daliborn** [springfox/springfox#2157] opened 2017-12-19 14:48 UTC
using:
springfox-swagger2 and springfox-swagger-ui - springfox.version 2.7.0 
and spring boot 1.5.9.RELEASE 

when you set jackson.serialization.wrap_root_value=true in application.properties, it crashes UI. 

Error is:
"Unexpected token u in JSON at position 0" chrome developer tools in springfox.js (line 27) 
 ` jsonEditor: JSON.parse(data.jsonEditor) || false,`

It seems that  UiConfiguration.java class is returned with json wrapper, which causes JS exception and crash of UI.

**Comment by dilipkrish** [comment] 2017-12-19 15:30
That is not currently supported. Closing this as a duplicate of #597

**Closed by dilipkrish** 2017-12-19 15:30 UTC
Labels: duplicate
