### ISSUE TITLE
Documentation not generated in latest versions of springfox with spring 3.x

### ISSUE THREAD

**Issue by adam150785** [springfox/springfox#921] opened 2015-08-18 11:41 UTC
Whilst integrating springfox with our SpringMVC application I had problems using the latest versions of springfox.

These are the versions and problems encountered:

**v2.2.2-2.1.2**
Exception thrown when loading war in tomcat:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'apiOperationReader' defined in URL [jar:file:/usr/local/apache-tomcat-7.0.42/webapps/ers-external-service/WEB-INF/lib/springfox-spring-web-2.1.2.jar!/springfox/documentation/spring/web/readers/operation/ApiOperationReader.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class springfox.documentation.spring.web.readers.operation.ApiOperationReader]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:912) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:855) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:770) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:803) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:731) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    ... 33 common frames omitted
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class springfox.documentation.spring.web.readers.operation.ApiOperationReader]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
    at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:217) ~[spring-aop-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:111) ~[spring-aop-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:477) ~[spring-aop-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:362) ~[spring-aop-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:322) ~[spring-aop-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1518) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    ... 43 common frames omitted
Caused by: java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
    at org.springframework.cglib.proxy.Enhancer.emitConstructors(Enhancer.java:721) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:499) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.cglib.proxy.Enhancer.create(Enhancer.java:285) ~[spring-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205) ~[spring-aop-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    ... 50 common frames omitted

**v2.1.1-2.0.3**
It appears that springfox never finishes initialising and therefore I never see "Servlet '[service-name]' configured successfully".
Accessing the documentation URL ([service-name]/v2/api-docs) results in an empty page in the browser.
Last lines in the log are:
[localhost-startStop-13] DEBUG s.d.s.w.r.o.OperationResponseClassReader - Setting spring response class to:Appointment
[localhost-startStop-13] INFO  s.d.s.w.ClassOrApiAnnotationResourceGrouping - Group for method createAppointmentRequest was referral
[localhost-startStop-13] DEBUG s.d.s.r.o.OperationAuthReader - Authorization count 1 for method createAppointmentRequest
[localhost-startStop-13] DEBUG s.d.s.r.o.SwaggerOperationResponseClassReader - Setting response class to:Appointment

**v2.0.2**
Works correctly but startup time is increased due to heavy debug logging from springfox (presumably already resolved in later version).

**v2.0.1**
Works.

**Question**
Ideally it would be great if we could use the latest version of springfox to take advantage of new features and bug fixes. I included issues with earlier versions just for context.

How do we solve the 'IllegalArgumentException: Superclass has no null constructors but no arguments were given' issue with the latest version?

Please let me know any other details you require to help me solve the problem.

Many thanks,

Adam.

**Comment by dilipkrish** [comment] 2015-08-18 12:25
@adam150785 first off, thanks for the detailed issue :metal: 

I suspect your having these issues because you don't have the latest aspectj aop version. Esply since you're on a very old version of spring, I'm not really sure what the exact steps are to fix the problem. 

Is it possible to share a repo with the issue reproduced (may be with a fork of the springfox-demo) so I can help diagnose?

**Comment by adam150785** [comment] 2015-08-18 13:01
Thanks for the quick response @dilipkrish and the pointers.

I can see that the aspectjrt dependency from springfox-swagger2:2.2.2 is being managed to 1.7.2 from 1.8.6. I guess this could be the issue if there is an API breaking change between 1.7.2 and 1.8.6.

Was the aspectj springfox dependency changed between v2.1.1 and 2.1.2?

It's quite a complex application so creating a reproduction forked from springfox-demo would be difficult without knowing the underlying cause.

I'll try to investigate further.

**Comment by dilipkrish** [comment] 2015-08-19 01:19
@adam150785 Thanks! Would be awesome if you report back your findings. I suspect a combination of spring upgrade and aspectj dependencies revved to the latest version will fix your problems

**Comment by dilipkrish** [comment] 2015-09-10 02:31
- [ ] will need to try and adjust any spring dependencies that depend on spring 4

**Comment by adam150785** [comment] 2015-09-10 14:37
@dilipkrish Are you suggesting there is a workaround for my issue?

I have no option of upgrading Spring as a dependent project uses v3.2.7.RELEASE and there are currently no plans to upgrade it. Therefore I'm currently stuck on springfox v2.0.2.

Any help is most appreciated.

**Comment by dilipkrish** [comment] 2015-10-23 23:39
Fixed via 39ba45f6edbaf919761937145948d46d0a26c277

**Closed by dilipkrish** 2015-10-23 23:39 UTC
Labels: maintenance

**Comment by adam150785** [comment] 2015-10-26 09:24
Hi @dilipkrish,

Given that this is now marked as closed does that mean I should be able to use the next release of springfox with my current setup (i.e. Spring 3.2.7.RELEASE)?

If so that would be fantastic!

When is the next release due?

Thanks,

Adam.

**Comment by dilipkrish** [comment] 2015-10-26 15:32
Its not been tested and not officially supported, however what this means is that we're not depending on the aspectj dependencies which introduced problems. There is still a dependency on spring-plugin which depends on spring 4.x but you might be fine using spring 3.x.

Would be awesome if you could report back your findings.

**Comment by adam150785** [comment] 2015-10-26 15:45
Yeah I will give it a go.

What version can I test this in?

**Comment by dilipkrish** [comment] 2015-10-26 15:47
Its available as a 2.2.3-SNAPSHOT from the jcenter oss repository

**Comment by Abdennebi** [comment] 2015-11-23 12:24
Hi, 

I've tested the 2.2.3-SNAPSHOT and it's getting worse. It's depends on a Spring 4 class (org.springframework.core.DefaultParameterNameDiscoverer).

Please, can you tell us if Spring 3 is still supported and if not can you clearly state on the springfox home page that it does no more support Spring 3 (i hope not)

Here an excerpt of the exception : 

```
java.lang.NoClassDefFoundError: org/springframework/core/DefaultParameterNameDiscoverer
	at springfox.documentation.spring.web.readers.parameter.ParameterNameReader.<init>(ParameterNameReader.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)```

**Comment by adam150785** [comment] 2015-11-26 17:51
Another vote for Spring 3 support! We could very much like to upgrade to the latest version.
