### ISSUE TITLE
 swagger-springmvc doesn't support @RepositoryRestResource

### ISSUE THREAD

**Issue by timothysparg** [springfox/springfox#1052] opened 2015-11-16 11:26 UTC
Potentially a duplicate of https://github.com/springfox/springfox/issues/445 which has since been closed,
although I didn't see any resolution to this question.

It would be very cool if Springfox could document the API that @RepositoryRestResource exposes.

**Comment by dilipkrish** [comment] 2015-11-16 15:03
Actually https://github.com/springfox/springfox/issues/699 is probably what you're looking for

**Comment by dilipkrish** [comment] 2015-11-16 15:03
Closing this as a duplicate of #699

**Closed by dilipkrish** 2015-11-16 15:03 UTC
Labels: duplicate
