### ISSUE TITLE
@JsonValue is not supported

### ISSUE THREAD

**Issue by fedotxxl** [springfox/springfox#2373] opened 2018-04-21 12:09 UTC
Dependency - 'io.springfox:springfox-swagger2:2.8.0'

Here is my resource:

```
@RestController
@RequestMapping("/cars/")
public class TestCarResource {

    @GetMapping("/{carId}")
    public Car get(@PathVariable Car.Id carId) {
        return new Car(carId, "car with id " + carId.toString());
    }

    @Getter
    @AllArgsConstructor
    public static class Car {

        private Id id;
        private String name;

        public static class Id {
            private String id;

            @JsonCreator
            public Id(String id) {
                this.id = id;
            }

            @JsonValue
            public String getId() {
                return id;
            }

            @Override
            public String toString() {
                return id;
            }
        }
    }

}
```

`Car.Id` should be displayed in swagger config as `String`. Instead it's object.

Expected:

```
"definitions":{  
   "Car":{  
      "type":"object",
      "properties":{  
         "id": {
           "type": "string"
         },
         "name":{  
            "type":"string"
         }
      },
      "title":"Car"
   }
}
```

Real:

``` 
"definitions":{  
   "Car":{  
      "type":"object",
      "properties":{  
         "id":{  
            "$ref":"#/definitions/Id"
         },
         "name":{  
            "type":"string"
         }
      },
      "title":"Car"
   }
}
```

**Comment by dilipkrish** [comment] 2018-04-21 12:11
The easiest way to support this is to have an alternate type rule to map `Id` => `String`

**Comment by theemathas** [comment] 2018-09-06 01:13
This seems to be a duplicate of #1871.

By the way, I don't understand how to use an alternate type rule to do this. I've been attempting to use the `directModelSubstitute` method of `Docket`. However, the example value is null instead of a string, and I don't know how to set the example value for this.

**Comment by dilipkrish** [comment] 2018-09-06 02:26
There is no way to have an example for the absence of something.

**Comment by theemathas** [comment] 2018-09-06 02:27
I don’t understand what you mean. By “example” I mean “example json”.

**Comment by theemathas** [comment] 2018-09-06 17:59
In case that wasn't clear, I meant that I was trying to do [this](https://swagger.io/docs/specification/2-0/adding-examples/) on my `Id` type, which has a `@JsonValue` method, which was worked around by using `directModelSubstitute`.

**Comment by dilipkrish** [comment] 2018-09-16 01:59
Adding an `@ApiParam` annotation with example doesnt help?

**Closed** 2020-07-08 15:49 UTC
Labels: feature, has-workaround, wontfix
