### ISSUE TITLE
Changing inferred url

### ISSUE THREAD

**Issue by prafful13** [springfox/springfox#3468] opened 2020-08-01 18:23 UTC
- [X ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
Latest - 3.0.0
What kind of issue is this?

 - [ X] Question. Is this a question about how to do a certain thing? 
So I am trying to change the inferred url to use https as my service is served over https protocal. However currently it is using http and thus giving a 

Code | Details
-- | --
Undocumented | TypeError: Failed to fetch

error whenever trying out a api call from swagger ui.
Can someone help with how to get around it and make the APIs being called via https instead of http?

**Comment by dilipkrish** [comment] 2020-08-03 21:56
Thats weird if its inferring http when you've deployed it over https. Could you describe how this is setup?

Possible duplicate of #3104

**Comment by iboich** [comment] 2020-08-04 12:34
The same issue for me when requesting from swagger-ui client.
![image](https://user-images.githubusercontent.com/56725646/89293254-47edda80-d666-11ea-97f2-1ad6c725a7b8.png)
![image](https://user-images.githubusercontent.com/56725646/89293952-728c6300-d667-11ea-91c0-5d7c88096e6d.png)

```
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
```

Server with spring is deployed with HTTP protocol but is accessed via the proxy with HTTPS. So, I supposed need to take into account such fact, when generating servers URL protocol. 
With direct HTTP access swagger-ui HTTP client works fine.

**Comment by minhnguyenvan95** [comment] 2020-08-21 08:47
up

**Comment by dilipkrish** [comment] 2020-08-24 17:11
You're not using the x-forward headers in the API gateway, which is why you're seeing this issue.

**Comment by minhnguyenvan95** [comment] 2020-08-27 06:08
> You're not using the x-forward headers in the API gateway, which is why you're seeing this issue.

Could you please tell me which x-forward should I use ?

**Comment by dilipkrish** [comment] 2020-09-04 18:57
The [X-Forward-Proto](https://stackoverflow.com/q/19084340) would be my guess

**Closed** 2020-12-17 20:15 UTC
Labels: question, wontfix

**Comment by rootwhois** [comment] 2022-08-19 02:38
Below is my temporary solution:
```java
@OpenAPIDefinition(servers = {
        @Server(url = "/", description = "Default Server URL"),
        @Server(url = "https://example.com/", description = "Prev Server URL")})
@SpringBootApplication
public class Application {
    // ...
}
```
