### ISSUE TITLE
Duplicate class names in different packages get squashed in ControllerDocumentation - modelMap

### ISSUE THREAD

**Issue by mbazos** [springfox/springfox#182] opened 2013-12-04 18:58 UTC
I haven't yet made a fix for this yet but our team encountered this issue and I believe it's fairly easy to fix but wanted to get feedback from you on how to go about this.  

Example of the issue given the following controller method:

```
    public void sampleMethod3(com.mangofactory.swagger.spring.sample.duplicate.Pet petOne, com.mangofactory.swagger.spring.sample.Pet petTwo) {
    }
```

Notice that petOne and petTwo are different classes but have the same class name.  When the ControllerDocumnetation modelMap is being populated it uses a friendly class name as the key so it would be "Pet" in this instance.  With "Pet" being the same key in the model map they will overwrite each other.

Ways I was thinking to go about fixing this:
1.  Just add in the package name...so friendly names will now be fully qualified (Not so friendly names)
2.  Add configuration into SwaggerConfiguration that would trigger friendly/fully qualified names

I am really not sure which one to do...friendly names are nice but people might end up not realizing this is happening so it's almost safer to have fully qualified.

Not sure if you need a reason of why this is important but here is it:
1.  Service versioning - having multiple version of client model object could cause these collision to happen over time
2.  Services that return subsets of a canonical model - some data might be expensive or unnecessary to return in this case service A could return petOne (superset) and service B could return petTwo (subset of petOne).

Let me know what you think and if I have time I don't mind working on this fix as it will benefit our team.

**Comment by donovanmuller** [comment] 2015-08-18 08:34
I have a similar situation except that this is happening on the response class as well.
We have some generated JAXB classes which unfortunately share the same top level class. Even though the classes are fully qualified, springfox seems to pick one and use that everywhere.

Example below:

```
@ApiOperation(value = "Save something")
public blah.blah.Document create(@RequestBody foo.bar.Document thingy) {
  ...
  return new foo.bar.Document();
}
```

The Swagger docs will only contain one representation of `Document`...

**Comment by dilipkrish** [comment] 2015-08-18 12:17
Yeah this needs to be fixed.

**Comment by stephenhibbert** [comment] 2015-08-20 14:17
I'm also having the same issue. A fix would be very much appreciated!

**Comment by mbazos** [comment] 2015-08-25 00:36
If I have some time I might work on this.  I recently upgraded our apps from swagger-springmvc to springfox and I am really liking the re-organization and re-packaging of the libraries.

I am going to be out of the country and won't be back until the last week in September, I will make sure to check here before I start any work on this.

**Comment by dilipkrish** [comment] 2015-08-26 12:42
@mbazos :metal: would be much appreciated! 

However, since this feature affects the core, I would like to collaborate on how you plan to approach this before you work on the PR. Just want to make sure its in-line with the direction we want to take this library.

Let me know if I can answer any questions.

**Comment by nikitsenka** [comment] 2015-12-07 05:40
Could you please provide some aprox estimations when the issue will be fixed?

**Comment by dilipkrish** [comment] 2015-12-18 03:28
ping @mbazos!

**Comment by mbazos** [comment] 2015-12-23 22:29
Yes been very busy with life and work. Currently on break for the holidays will try to get this done before the new year.

**Comment by dilipkrish** [comment] 2015-12-24 14:51
Not a problem... was just pinging to see if you still had plans to help with this feature. It will be much appreciated ... Thanks!

**Comment by mbazos** [comment] 2015-12-28 16:35
@dilipkrish It's been a while since I have looked at this code and our discussion above references the old version of swagger-springmvc before you worked on the major refactor.  Anyway I forked the repo and got my local workstation all up and running.

Just wanted to check a few things:
So I think what needs to change is [DefaultTypeNameProvider](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/DefaultTypeNameProvider.java), is this correct?  Right now it's returning the class simple name which will conflict if more than one class have the same name.

**Comment by dilipkrish** [comment] 2015-12-30 12:25
I believe thats sounds correct but haven't dug in recently to tell u without spelunking. Off hand I know that there is also [TypeNameExtractor](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/TypeNameExtractor.java) that uses the TypeNameProviders plugins. 

I thought I'd just chime in with a few expectations. 
- It would be good to verify that your solution will work with swagger-codegen
- I would feature toggle this feature with a flag in the docket similar to [the enableUrlTemplating flag](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L393-L397) ***and mark with an `@Incubating` annotation***.
- Implement it in such a way that it falls back to current behavior if it doesn't find two models with the same name; similar to how we do [operation](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationNicknameIntoUniqueIdReader.java#L43) [unique ids](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/builders/OperationBuilder.java#L265) using some kind of caching technique [like here](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/operation/CachingOperationNameGenerator.java)

I'll report back if I find anything different or interesting. Thanks for helping out!

**Comment by mbazos** [comment] 2016-01-13 01:46
@dilipkrish just getting comfortable with the project and I have to be honest, I am trying to setup the things you mentioned above and I am partially there but I am having a hard time understanding how everything is connected.

I think I know the code changes I need to make in DefaultModelProvider but I am having a hard time understanding what I need to do to setup the plugin so I can make the decision of when to use this new behavior or not. I am a little confused about the operation/unique ids examples you sent me.

is there an irc chat or something that some of the devs use?

**Comment by dilipkrish** [comment] 2016-01-13 02:15
This works -> [![Join the chat at https://gitter.im/springfox/springfox](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/springfox/springfox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

I dont blame you ... its a lot of stuff :)

Plugins are just regular spring beans, the only thing is they have an [additional contract](https://github.com/spring-projects/spring-plugin)  that allow the plugins to be partitioned/ filtered and queried by documentation type (swagger 1.2 or swagger 2.0). 

To get familiar with how the different components work together see [this architecture diagram](http://springfox.github.io/springfox/docs/current/#architecture). 

Plugins are ordered and have priorities. First the `springfox-spring-web` plugins are applied then the `springfox-swagger2` plugins are applied. 

Plugins layer information on the the builders they represent, for e.g. these are all the [available schema plugins](https://github.com/springfox/springfox/tree/master/springfox-spi/src/main/java/springfox/documentation/spi/schema) in the `springfox-spi` module. [Model](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/schema/ModelBuilderPlugin.java) builder plugin gets passed in a [model context](https://github.com/springfox/springfox/blob/master/springfox-spi/src/main/java/springfox/documentation/spi/schema/ModelBuilderPlugin.java#L33) which gives access to the [`ModelBuilder`](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/builders/ModelBuilder.java) that is used to build the model.

**Comment by mbazos** [comment] 2016-01-18 15:03
@dilipkrish I committed and initial push here [mbazos - springfox][https://github.com/mbazos/springfox] but I am just not sure if I am going in the right direction.  Basically what I am doing is creating a new plugin for the "Id" provider the default will use the class getSimpleName() and the new one will use the class name as I believe this will cause different models to be in the modelMap regardless of the the model name (I believe this is correct based on debugging and looking through the code).

When you get a chance or if there is someone else that can help with suggestions can you please take a look to make sure I am not way off target.

**Comment by dilipkrish** [comment] 2016-01-18 16:13
Ill take a look at annotate! thanks!

**Comment by vignesharunachalam** [comment] 2016-02-24 20:58
@dilipkrish - I have a similar issue where I have 2 classes with the same names, but in different packages, but swagger-ui does not show up the correct structure. Is there anyway I can qualified which class to use as part of the swagger-ui?

**Comment by ssrini** [comment] 2016-02-26 06:20
I have the same issue with Responses.  Multiple APIs return different objects with the same name, for e.g. User.  User is present with different attributes in different packages used for the response.

The generated docs are all pointing to a single User class and incorrect.

Is a fix in the pipeline?  Is there a workaround while we wait for a fix?

Thanks

**Comment by WydD** [comment] 2016-03-02 12:02
@vignesharunachalam I had the same issue lately. Until a clear solution arises, you can always go around the problem by annotating at least one of your model with `@ApiModel` and use a unique name (e.g. LegacyPet for instance)

**Comment by sandeepb2003** [comment] 2016-05-17 21:28
I am facing same issue. Is there a workaround till we have a solution

**Comment by Chinna-SearsHomeServices** [comment] 2016-09-28 18:45
hi, Is there any workaround for this issue. I have versioned REST api and having same class in different versioned package. It would be great if you have any workaround.

**Comment by dilipkrish** [comment] 2016-09-29 03:00
@Chinna-SHS The easiest for now is to use the `@ApiModel` attribute and set different values on the two.

e.g.

```java
package v1;
@ApiModel("V1Model")
class ModelX {}

package v2;
@ApiModel("V2Model")
class ModelX {}

```

**Comment by patrickbray** [comment] 2016-11-27 21:54
I have run into this as well. Any updates on progress around this is a fix still targeted for 2.7.0? Is there anything we can do to help out with a fix?

**Comment by dilipkrish** [comment] 2016-12-07 13:51
@patrickbray This is still targeted for 2.7.0 but it has a workaround as described above

**Comment by damianChapman** [comment] 2017-05-12 08:02
I have tried the workaround for this issue and it doesn't work. i.e. Setting different names for the models in the @ApiModel annotation. I am using 2.4.0 of springfox-swagger2. Is there something else that I need to do to get this issue resolved?

**Comment by rajatkasliwal** [comment] 2017-08-15 21:12
We are facing the same issue and it is causing a lot of confusion to our clients. Any update on when this will be fixed or if it's already fixed ? 

Thanks!

**Comment by dilipkrish** [comment] 2017-08-22 03:52
@rajatkasliwal It is not fixed currently. It is still open.

**Comment by vikramsetty** [comment] 2018-04-09 15:47
Hi Dilipkrish, You had plans of fixing this in 2.7.0 . 
Any update about this as even 2.8.0 is released now.

**Comment by vikramsetty** [comment] 2018-04-10 05:41
Thanks

**Comment by jrichmond4** [comment] 2018-10-04 20:30
I upgraded to 2.9.2 and am still seeing this issue

**Comment by dilipkrish** [comment] 2018-11-08 13:00
@jrichmond4 this is closed because it is part of #2056

**Comment by sLite** [comment] 2019-02-11 16:27
@dilipkrish I've checked that PR and @MaksimOrlov said that he is almost done.
Is this still planned only for 3.0.0 like you mentioned some time ago or will it be available in some 2.9.X version?

Nasty thing is, we also use swagger-codegen for typescript and it generates only the one class definition that is exposed by springfox. This only matches the actual return type of one of the controllers, for the other controllers we get typescript code that doesn't match the actual payload structure.

This is also a silent failure because springfox doesn't complain, and swagger-codegen doesn't know that something is wrong, because it only reads the api-docs. So we have to manually keep modelnames unique all across our codebase which is not that easy ;)

Best regards and thanks!

**Comment by MaksimOrlov** [comment] 2019-05-28 12:29
Branch with model enhancement support has been merged to master and now available in 2.9.2-snapshot version. I would be grateful for feedback of this functionality.

**Comment by sLite** [comment] 2019-05-28 12:33
Hi, that's awesome!
Is there some kind of documentation on what has changed and how to use / migrate to it?

**Comment by MaksimOrlov** [comment] 2019-05-28 12:37
@sLite, just switch to latest *snapshot* version.

**Comment by MaksimOrlov** [comment] 2019-05-28 12:39
Same class names will be produced with indexes. F.e. if there is
```
fiirst.packegr.Pet;
second.packege.Pet;
```
that will be produces as ***Pet*** and ***Pet_1***

**Comment by benjvoigt** [comment] 2019-07-12 13:01
@MaksimOrlov I observed that the numbering is not consistent between application startups. I have 3 models in 3 different packages which always get a varying number assigned. Is this due to the scan order? Can this be fixed at all? For documentation it's not a big deal but we're planning to generate client source code from the generated docs and if naming keeps changing between deployments the generated source code will change even tho' the DTO hasn't been modified.

**Comment by MaksimOrlov** [comment] 2019-07-12 13:30
@benjvoigt, numbering must be stable from run to run. If you observing numbering that being changed during a few runs, that is issue. It would be great if you make example, that reproduce problem, then I will be able to fix.

**Comment by benjvoigt** [comment] 2019-07-12 22:07
@MaksimOrlov There you go: https://github.com/benjvoigt/springfox-naming-demo
The repo uses lombok, so make sure annotation processing is enabled on compiling.

This would be my result for the first run:
**/v1/mystatus-one --> Health_1
/v2/mystatus-two --> Health
/v3/mystatus-three --> Health_2**
```
{
    "swagger": "2.0",
    "info": {
        "description": "demo-service API definitions",
        "version": "1.0",
        "title": "demo-service",
        "termsOfService": "termsOfServiceURL",
        "contact": {
            "name": "Demo",
            "url": "https://www.example.com/"
        },
        "license": {}
    },
    "host": "localhost:8080",
    "basePath": "/",
    "tags": [
        {
            "name": "controller",
            "description": "Controller"
        }
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/v1/mystatus-one": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Get current service status",
                "operationId": "getServiceStatusUsingGET_1",
                "parameters": [
                    {
                        "name": "X-Authorization-Token",
                        "in": "header",
                        "description": "Authorization Token",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Health_1"
                        }
                    }
                },
                "security": [
                    {
                        "api_token_sec_key": []
                    }
                ],
                "deprecated": false
            }
        },
        "/v2/mystatus-two": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Get current service status",
                "operationId": "getServiceStatusUsingGET",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "X-Authorization-Token",
                        "in": "header",
                        "description": "Authorization Token",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Health"
                        }
                    }
                },
                "security": [
                    {
                        "api_token_sec_key": []
                    }
                ],
                "deprecated": false
            }
        },
        "/v3/mystatus-three": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Get current service status",
                "operationId": "getServiceStatusUsingGET_2",
                "parameters": [
                    {
                        "name": "X-Authorization-Token",
                        "in": "header",
                        "description": "Authorization Token",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Health_2"
                        }
                    }
                },
                "security": [
                    {
                        "api_token_sec_key": []
                    }
                ],
                "deprecated": false
            }
        }
    },
    "securityDefinitions": {
        "api_token_sec_key": {
            "type": "apiKey",
            "name": "X-API-Token",
            "in": "header"
        }
    },
    "definitions": {
        "Health": {
            "type": "object",
            "required": [
                "id",
                "otherId"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id"
                },
                "otherId": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id of the other"
                }
            },
            "title": "Health"
        },
        "Health_1": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id"
                }
            },
            "title": "Health_1"
        },
        "Health_2": {
            "type": "object",
            "required": [
                "id",
                "otherId",
                "thirdId"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id"
                },
                "otherId": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id of the other"
                },
                "thirdId": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id of the third"
                }
            },
            "title": "Health_2"
        }
    }
}
```

And the second run: 
**/v1/mystatus-one -->Health_2
/v2/mystatus-two --> Health_1
/v3/mystatus-three --> Health**
```
{
    "swagger": "2.0",
    "info": {
        "description": "demo-service API definitions",
        "version": "1.0",
        "title": "demo-service",
        "termsOfService": "termsOfServiceURL",
        "contact": {
            "name": "Demo",
            "url": "https://www.example.com/"
        },
        "license": {}
    },
    "host": "localhost:8080",
    "basePath": "/",
    "tags": [
        {
            "name": "controller",
            "description": "Controller"
        }
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/v1/mystatus-one": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Get current service status",
                "operationId": "getServiceStatusUsingGET_2",
                "parameters": [
                    {
                        "name": "X-Authorization-Token",
                        "in": "header",
                        "description": "Authorization Token",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Health_2"
                        }
                    }
                },
                "security": [
                    {
                        "api_token_sec_key": []
                    }
                ],
                "deprecated": false
            }
        },
        "/v2/mystatus-two": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Get current service status",
                "operationId": "getServiceStatusUsingGET_1",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "X-Authorization-Token",
                        "in": "header",
                        "description": "Authorization Token",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Health_1"
                        }
                    }
                },
                "security": [
                    {
                        "api_token_sec_key": []
                    }
                ],
                "deprecated": false
            }
        },
        "/v3/mystatus-three": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Get current service status",
                "operationId": "getServiceStatusUsingGET",
                "parameters": [
                    {
                        "name": "X-Authorization-Token",
                        "in": "header",
                        "description": "Authorization Token",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Health"
                        }
                    }
                },
                "security": [
                    {
                        "api_token_sec_key": []
                    }
                ],
                "deprecated": false
            }
        }
    },
    "securityDefinitions": {
        "api_token_sec_key": {
            "type": "apiKey",
            "name": "X-API-Token",
            "in": "header"
        }
    },
    "definitions": {
        "Health": {
            "type": "object",
            "required": [
                "id",
                "otherId",
                "thirdId"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id"
                },
                "otherId": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id of the other"
                },
                "thirdId": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id of the third"
                }
            },
            "title": "Health"
        },
        "Health_1": {
            "type": "object",
            "required": [
                "id",
                "otherId"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id"
                },
                "otherId": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id of the other"
                }
            },
            "title": "Health_1"
        },
        "Health_2": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ade02824-32ba-4157-8122-807a48b13268",
                    "description": "Unique id"
                }
            },
            "title": "Health_2"
        }
    }
}
```

**Comment by MaksimOrlov** [comment] 2019-07-15 18:07
@benjvoigt, thanks, will look it in a next few days.

**Comment by robertsearle** [comment] 2019-07-16 17:51
I am not a spring fox developer. Just interested in getting this solved.

If you are looking for a solution, you could get the full package string plus class name string and then call the hashcode function to get a number. Not a nice number but could solve your problem most of the time. It would also be scan order independent.

Just a thought and option.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MaksimOrlov** [comment] 2019-07-16 18:13
@robertsearle, the `hasCode()` function is not reliable. Hashes can collide, could be two same numbers for different strings. I think the better approach is to use full method signature.

**Comment by duke-cliff** [comment] 2019-11-26 18:53
@dilipkrish Why the ticket is marked as solved? What's the solution to use `full name/package name` instead of `simple name` for the model?

**Comment by duke-cliff** [comment] 2019-11-26 18:54
Sorry, saw it was marked as solved in the release notes but not in the actual ticket

**Comment by MaksimOrlov** [comment] 2020-01-07 21:17
@robertsearle, @benjvoigt , the fix has been merged to master branch. Could you, please, provide a feedback for 3.0.0-SNAPSHOT, if the issue was fixed or not ?

**Comment by benjvoigt** [comment] 2020-01-08 08:40
@MaksimOrlov numbering appears to be stable between runs now, ty. I tested with multiple endpoints and also with nested models as return value.

**Closed** 2020-07-08 03:04 UTC
Labels: feature, wontfix

**Comment by ande13** [comment] 2021-04-15 14:26
For java, you can use the following workaround

@Primary
@Component
public class SwaggerApiModelTypeNameProvider extends ApiModelTypeNameProvider {

    private final Map<String, Pair<String, String>> classNames = new ConcurrentHashMap<>();

    @Override
    public String nameFor(Class<?> type) {
        ApiModel annotation = AnnotationUtils.findAnnotation(type, ApiModel.class);
        String defaultTypeName = type.getTypeName().replace(type.getPackageName() + ".", "");

        defaultTypeName = annotation != null ? Optional.ofNullable(Strings.emptyToNull(annotation.value())).orElse(defaultTypeName) : defaultTypeName;

        Pair<String, String> classPackagePair = classNames.get(defaultTypeName);
        if(classPackagePair != null) {
            if(!classPackagePair.getValue().equalsIgnoreCase(type.getPackageName())) {
                defaultTypeName = "_" + defaultTypeName;
            }
        }
        classNames.put(defaultTypeName, Pair.of(type.getTypeName(), type.getPackageName()));

        return defaultTypeName;

    }
}

You can modify it if needed :)

**Comment by OleBilleAtBS** [comment] 2021-05-04 10:15
Is this issue closed?  I'm having this issue with 3.0.0

**Comment by bestarshad** [comment] 2021-05-30 07:54
please refer the files in repo for the fix


same class name issue fix in open api swagger it will generate schema request response as per java annotation naming convention against the java variables. it will not create schema request response as per java variables it will follow schema annotation

[github](https://github.com/bestarshad/openapiswaggerfix)

**Comment by xak2000** [comment] 2022-01-27 17:19
@MaksimOrlov Just tried 3.0.0 and the issue is still not fixed.

Maybe because in my case the difference is not a package name, but an outer class name:

```
package my.package.dto;

public class User {
  private Location location;

  public static class Location {
    private String name;
  }
}
```

And:
```
package my.package.dto;

public class Car {
  private Location location;

  public static class Location {
    private Long id;
    private String address;
  }
}
```

Only one `Location` model is present in the generated docs. So, one of `User` or `Car` has incorrect model for `location` property.

**Comment by SievaFliesAlone** [comment] 2022-03-21 20:58
This helped me:

```
TypeNameResolver.std.setUseFqn(true);
```

**Comment by jyeonjyan** [comment] 2023-01-16 08:40
> @vignesharunachalam I had the same issue lately. Until a clear solution arises, you can always go around the problem by annotating at least one of your model with `@ApiModel` and use a unique name (e.g. LegacyPet for instance)

This solution solved my problem the fastest.
My situation for example..

```kotlin
- com.example.domain.dto.foo.Foo.Create
- com.example.domain.dto.bar.Bar.Create

package com.example.domain.dto.foo
@ApiModel("FooCreate")
data class Create(){}

package com.example.domain.dto.bar
@ApiModel("BarCreate")
data class Create(){}
```

**Comment by jyeonjyan** [comment] 2023-01-16 08:45
@dilipkrish 
First of all, thank you for your hard work.
So, is this issue resolved or won't fix?

**Comment by Tvaroh** [comment] 2024-03-12 06:43
For newest swagger annotations this helps:
```scala
@Schema(name = "CustomName")
```

**Comment by yupnano** [comment] 2024-04-12 07:56
ten years passed 😭
