### ISSUE TITLE
Methods not documented

### ISSUE THREAD

**Issue by TheSneak** [springfox/springfox#949] opened 2015-09-02 16:47 UTC
I have a controller with four methods. Two of these methods use the same request mapping but one requires a request param:

    String mapValue = "/customers/{cId}/po";
    @RequestMapping(value = mapValue, method = RequestMethod.GET)
    ResponseEntity<Collection<PurchaseOrder>> index(@PathVariable String cId) {
        //do work and return list of POs
    }

    @RequestMapping(value =mapValue, method = RequestMethod.GET, params = {"tag"})
    ResponseEntity<PurchaseOrder> findPOByTag(@PathVariable String cId, @RequestParam(value = "tag", required = true) String tag) {
        //do work and return single PO
    }

Only one or the other of these two methods will show up in the resulting documentation.

**Comment by dilipkrish** [comment] 2015-09-02 17:43
@TheSneak this is a known limitation of swagger-spec. This is a duplicate of #750. There is a work around for it but, swagger-ui won't play nice with it. I have a [PR](https://github.com/swagger-api/swagger-js/pull/541) which address that issue. Would be great if you vote up the PR and the [underlying issue](https://github.com/swagger-api/swagger-spec/issues/291)

**Closed** 2015-11-17 02:21 UTC
Labels: can-use-for-docs, duplicate, question
