### ISSUE TITLE
Support alternate type resolution for @ModelAttribute annotated model fields

### ISSUE THREAD

**Issue by ejain** [springfox/springfox#969] opened 2015-09-10 22:21 UTC
Given a class used as a `@ModelAttribute` like:

    public class Query {
      @ApiModelProperty("some items")
      private List<UUID> items;
      ...
    }

The Swagger spec SpringFox generates has this:

    {
      "name": "items",
      "in": "query",
      "description": "some items",
      "required": false,
      "type": "ref"
    }

Expected:

    {
      "name": "items",
      "in": "query",
      "description": "some items",
      "required": false,
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid",
      }
    }

**Comment by dilipkrish** [comment] 2015-09-11 04:11
I think this is fixed in the latest snapshot. This is a duplicate of #929

**Comment by ejain** [comment] 2015-12-05 18:03
Looks like this is still broken in 2.3.0.

**Comment by dilipkrish** [comment] 2015-12-05 19:30
Non scalar types are not supported for model attributes. Also it seems like it might be a good idea to support alternate type rules for model attributes as well. 

Long winded way of saying yes this still broken.

**Closed** 2016-02-09 02:33 UTC
Labels: feature
