### ISSUE TITLE
Swagger JSON generated by SpringFox shows 'Consumes' for GET and DELETE operations

### ISSUE THREAD

**Issue by dcp65** [springfox/springfox#1781] opened 2017-04-20 11:18 UTC
I am using SpringFox to generate a Swagger UI and static doc from a Spring REST application. 

Is there any way to stop SpringFox from adding a 'consumes' section to the generated Swagger for GET operations? As I understand it, GETs should not include a body, so they don't consume anything.

You can see this in the springfox-demos where the 'findPetsByStatusUsingGET' operation includes a 'consumes':

```/api/pet/findByStatus": {
      "get": {
        "tags": [
          "pet-controller"
        ],
        "summary": "Finds Pets by status",
        "description": "Multiple status values can be provided with comma seperated strings",
        "operationId": "findPetsByStatusUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
```

The same thing applies to DELETE operations:

```
       "delete": {
        "tags": [
          "pet-store-resource"
        ],
        "summary": "Delete purchase order by ID",
        "description": "For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors",
        "operationId": "deleteOrderUsingDELETE",
        "consumes": [
          "application/json"
        ],
```

**Comment by dilipkrish** [comment] 2017-04-20 13:35
NOTE: that this only true for media types that support payload. For example this doesnt apply to `application/x-www-form-urlencoded` and `multipart/form-data`.

**Comment by dilipkrish** [comment] 2017-07-09 17:11
This is not valid in all uses cases ☝️so closing as won't-fix

**Comment by NewBirth** [comment] 2017-09-18 15:29
I'm using springfox 2.7.0 and facing the same issue.

      {
      "swagger":"2.0",
      "info":{},
      "paths":
      "/api/v1/...":{
      	"get": {
      		"summary":"...",
      		"operationId":"getSmthWithGET",
      		"consumes":[
      			"application/json"
      		],
      		"produces":[
      			"application/json",
      		"application/json;charset=UTF-8"
      		]
      	     }
          }
      }

Based on swagger.json I'm generating API pdf with swagger2markup, which results in having 'Consumes
• application/json' for every GET and DELETE operation.

Will it be fixed one day?
Is there any workaround?
Thanks in advance.

**Comment by dilipkrish** [comment] 2017-09-27 02:27
That seems reasonable... let me see if there is a workaround

**Comment by toni-lopez** [comment] 2017-10-25 09:01
Hi here!
We are facing the same issue and it forced us to have an ugly hack in our code.
Is there an ETA for this issue? Happy to collaborate if necessary 😄

**Comment by dilipkrish** [comment] 2017-10-26 12:01
@toni-lopez would certainly appreciate your help. ETA is as soon as I have some bandwidth to work on it. Currently looking to support OAS 3.0 at a minimum

**Closed** 2017-11-30 11:23 UTC
Labels: bug, in progress

**Comment by GRajaMca** [comment] 2018-10-01 06:53
@dilipkrish , i knew the as the per the documentation swagger does not support this, but at least if you provide some work around to solve this issue (typeerror: failed to execute 'fetch' on 'window': request with get/head method cannot have body. in swagger). Note this issues are mainly happen only for spring boot actuator alone. thanks in advance.

**Comment by naveed-butt** [comment] 2019-02-19 12:44
I am having the same issue. I am on .Net Core 2.2 using Web API and having the same problem. consumes is showing following for me...
```
paths": {
    "/api/Search": {
      "get": {
        "tags": [
          "Search"
        ],
        "operationId": "SearchCars",
        "consumes": [
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "input",
            "in": "body",
            "required": false,
            "schema": {
              "$ref": "#/definitions/CarSearchInputDTO"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/CarSearchResultDTO"
              }
            }
          }
        }
      }
    }
  },
```

**Comment by naveed-butt** [comment] 2019-02-20 06:06
I think the problem is with expecting an object in get request params... Once, I switch to POST for this method, it started working fine, or even if I break the object into indiviual param fields, it works fine as well :)
