### ISSUE TITLE
swagger-ui.html parsing error

### ISSUE THREAD

**Issue by Robert-Leggett** [springfox/springfox#712] opened 2015-04-28 00:15 UTC
Hi,

I am not able to get springfox-swagger-ui to work on a spring mvc restful api, the springfox-swagger2 is functional and producing json but when trying the start the web application it fails with a parsing error for swagger-ui.html.

I have created a thread on stackoverflow.

http://stackoverflow.com/questions/29897685/not-able-to-get-springfox-swagger-ui-working-with-spring-mvc

**Comment by adrianbk** [comment] 2015-04-28 00:55
Closing as duplicate of: https://github.com/springfox/springfox-demos/issues/1

**Closed by adrianbk** 2015-04-28 00:55 UTC

**Comment by Robert-Leggett** [comment] 2015-04-28 03:51
@adrianbk thank you, you were right about the context config location, i have now corrected the code and fixed the issue I was having.

thanks
