### ISSUE TITLE
springfox-boot-starter:3.0.0  'position' attribute of '@ApiModelProperty' has stopped working.

### ISSUE THREAD

**Issue by mastar3104** [springfox/springfox#3416] opened 2020-07-16 06:19 UTC
It is described in this comment.
https://github.com/springfox/springfox/issues/3070#issuecomment-655580882

But, I created the issue because the this issue is close.

**Comment by sigand** [comment] 2020-07-16 08:14
Duplicate of https://github.com/springfox/springfox/issues/3391

**Comment by dilipkrish** [comment] 2020-07-16 12:03
Closing this a duplicate of #3391

**Closed by dilipkrish** 2020-07-16 12:03 UTC
