### ISSUE TITLE
@ApiParam is defaulted to require = false when used with a @PathVariable

### ISSUE THREAD

**Issue by tomb50** [springfox/springfox#945] opened 2015-08-31 13:13 UTC
Hi,

I am encountering the issue described in https://github.com/springfox/springfox/issues/217 with v 2.2.2, I've also checked 2.0.2 and it is there also.

Thanks
Tom

**Comment by dilipkrish** [comment] 2015-08-31 14:48
@tomb50 I think this is working as designed. 

`@PathVariable`s are always marked as required. 
`@ApiParam` is an optional annotation to describe additional meta-information like description etc.
`@ApiParam#required()` is [defaulted to false](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java#L77), unless you set it to true. 

Springfox uses plugins to layer information. There are a set of plugins that are spring specific that apply the inferred values on to the internal service models. The swagger annotation related metadata is layered on top of the spring-mvc descriptions. By definition, plugins don't know and should not know about each other or previously inferred values (in your case *required* attribute).

So if you choose to augment the definitions with `@ApiParam` then you need to be explicit and set the value to true.

**Comment by tomb50** [comment] 2015-08-31 15:58
Hi @dilipkrish

Thanks for the swift response. Having to set them explicitly to required makes sense in that case. I just saw that there had been commit for this issue in the past and so presumed that that there was a regression.

https://github.com/agentgonzo/swaggerspringmvc/commit/582dd9ac9a3f1f450b3dc77ebcee58ab31d596e6

Thanks
Tom

**Comment by tomb50** [comment] 2015-08-31 16:01
Sorry, i got confused, that was on a forked branch! never mind.

Thanks again

**Comment by dilipkrish** [comment] 2015-08-31 17:00
@tomb50 np! I think that commit was from the time this project was called swagger-springmvc!

**Comment by cbornet** [comment] 2015-09-08 10:12
@dilipkrish Do you know why ApiParam has default values ?

**Comment by dilipkrish** [comment] 2015-09-08 12:50
Because the annotations have default values defined

**Closed** 2015-11-17 02:21 UTC
Labels: can-use-for-docs, question
