### ISSUE TITLE
About single parameter in application/json request case

### ISSUE THREAD

**Issue by zhugw** [springfox/springfox#1073] opened 2015-11-29 08:16 UTC
Does exist more elegant manner to process single parameter in swagger ui? 
Background: front-end want all post/put request consistently use application/json to commit data, so if one Api only need single parameter, e.g. 
```
public Result<?> cancelOrder(
      @ApiParam(value = "Order ID", required = true) @PathVariable long orderId,
      @ApiParam(value = "User ID", required = true) @RequestBody int userId) 
```
in this case the ui effect is
![screenshot from 2015-11-29 16 01 23](https://cloud.githubusercontent.com/assets/4953871/11456029/cfa08696-96b3-11e5-9ea6-7c4a6c224ce9.png)
but I want this effect
![screenshot from 2015-11-29 16 12 04](https://cloud.githubusercontent.com/assets/4953871/11456031/f9042f4c-96b3-11e5-82ff-37eb87b96456.png)
I feel this effect is more clear to front-end user. So I have to create a special DTO Object , 
```
 @Data
  static class OrderCancelForm {
    int userId;
  }
```
Of course I could create some common DTO Object for single parameter or two parameters, e.g.
```
class CommonSingleValueForm{
    Object value;
}
```
but I want know if exist some more convenience and elegant manner for this requirement?

**Comment by dilipkrish** [comment] 2015-12-02 03:38
@zhugw What version of the sofware are you using? Im not able to reproduce this issue in `2.2.3-SNAPSHOT`

**Comment by zhugw** [comment] 2015-12-02 06:19
```
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>2.2.2</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.2.2</version>
			</dependency>
```

**Comment by dilipkrish** [comment] 2016-01-03 01:59
@zhugw Is this problem fixed in 2.3.0. Not able to reproduce this issue

**Comment by zhugw** [comment] 2016-01-03 04:14
Fixed what? 
I only found Data Type is not undefined but show real type and still have to create a DTO to include this single parameter to achieve my effect that is a json body, see below
```
public ResponseEntity<?> deleteReservation(@PathVariable long id, @RequestBody int userId){...}
```
ui interface
![screenshot from 2016-01-03 12 12 09](https://cloud.githubusercontent.com/assets/4953871/12077218/4616df30-b213-11e5-8622-7a1d299d14d8.png)

I want is do not need to create a additional dto object.

**Comment by dilipkrish** [comment] 2016-01-03 04:52
@zhugw I may have misunderstood your request. Well I don't see a way to do what you're expecting to achieve without creating a DTO. 

So just to be clear, the bug that it was showing up as `undefined` is what was fixed. You might be able to achieve what your expecting to achieve using a `Map` perhaps instead of a DTO.

**Closed** 2016-01-04 03:04 UTC
Labels: question
