### ISSUE TITLE
Enum array is parsed as a string array in a request param.

### ISSUE THREAD

**Issue by RobWin** [springfox/springfox#718] opened 2015-04-30 15:03 UTC
Hi,

I have a following RequestParam `filterBy` which is a Enum array.

```
public enum ContactField {
    COMPANY,
    TITLE;
}

```
@RequestParam(value = "filterBy", required = false) ContactField[] filterBys,
```

The ContactField[] is mapped to a string array.

```
                 {
                    "name": "filterBy",
                    "in": "query",
                    "description": "filterBys",
                    "required": false,
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "collectionFormat": "csv"
                },
```

**Comment by dilipkrish** [comment] 2015-04-30 16:17
Closing this as its a duplicate of #664 
It should've rendered the alowable values in the items object, which its not doing. More detailed explanation of why this is happening over in the other issue.

**Closed by dilipkrish** 2015-04-30 16:17 UTC
Labels: duplicate
