### ISSUE TITLE
Bean Validation annotations ignored

### ISSUE THREAD

**Issue by miguelfgar** [springfox/springfox#987] opened 2015-09-25 11:45 UTC
Hi guys,

According to Swagger release notes they support Bean Validation annotations (JSR-303) since v. 1.5.0.
I tried to make this work with Springfox with Spring Boot but the annotations in my model (bean) are ignored. The JSON file that swagger produces has not the corresponding information (about fields size, required or not, etc..).

I have checked the Swagger code and I have found the place where they "apply" (read and proccess) the Bean Validation annotations (package "javax.validations.constraints"). It is in the following class  (ModelResolver), in the method "applyBeanValidatorAnnotations":

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java

In the release notes we can see that JSR303 is supported since 1.5.0: 
https://github.com/swagger-api/swagger-core/releases/tag/v1.5.0

The questions are: Should this work? Am I missing something? Is this supported by Springfox? 
Is there a possibility that  this ModelResolver is skipped? I see this is in swagger-core maven module which I would say SpringFox project does not add as a dependency...

If this is not supported could you point me in the right direction to implement it and maybe even contribute?

Thanks so much!

**Comment by dilipkrish** [comment] 2015-09-29 01:48
This library does not use `swagger-core`, so any advertised support of bean validation is not applicable here.

> The questions are: Should this work? 

No, but there are extensibility hooks to support it. Just that I don't have the bandwidth to maintain it.

> Am I missing something? Is this supported by Springfox? 

Yes, this feature is not supported by springfox.

> Is there a possibility that this ModelResolver is skipped? I see this is in swagger-core maven module which I would say SpringFox project does not add as a dependency...

That is a true statement. We don't have any depdenency on swagger-core other than its models and annotations.

> If this is not supported could you point me in the right direction to implement it and maybe even contribute?

See notes in #356. Would love a PR to support this feature. 

Closing this as its a duplicate of #356.

**Closed by dilipkrish** 2015-09-29 01:48 UTC
Labels: duplicate

**Comment by miguelfgar** [comment] 2015-10-15 16:09
Thanks dilipkrish for your detailed answer.

Please, could you explain me a how to add a hook so I can implement the extension to process JSR-303? I tried to find some info in the reference documentation in the "5.8 Extensibility" section but it's not complete yet.

If you could point me in the right direction I will try to implement this and contribute.
Thanks so much!

**Comment by dilipkrish** [comment] 2015-10-15 16:14
That's awesome. Let me put something together

**Comment by jfiala** [comment] 2015-11-10 23:01
Supporting "@NotNull" for a Model Property it is quite easy.
Simply add the following component (make sure to include its package in @ComponentScan):

@Component
public class MyModelPropertyBuilderPlugin implements ModelPropertyBuilderPlugin {

	@Override
	public boolean supports(DocumentationType delimiter) {
		// we simply support all documentationTypes!
		return true;
	}

	@Override
	public void apply(ModelPropertyContext context) {
		ModelPropertyBuilder mybuilder = context.getBuilder();
		
		Optional<BeanPropertyDefinition> beanPropDef = context.getBeanPropertyDefinition();
		BeanPropertyDefinition beanDef = beanPropDef.get();
                // get the field so we can check its annotations
		AnnotatedField field = beanDef.getField();
		if (field!=null) {
                        // if @NotNull is present, we make this field required!
			NotNull myNotNull = field.getAnnotation(NotNull.class);
			if (myNotNull!=null) {
				mybuilder.required(true);
			}
		}
		
	}


}

**Comment by jfiala** [comment] 2015-11-11 11:12
For support for Min/Max you have to add :
``` java
// add support for @Min/@Max
			Min myMin = field.getAnnotation(Min.class);
			Max myMax = field.getAnnotation(Max.class);
			AllowableValues myvalues = null;
			if (myMin!=null && myMax!=null) {
				myvalues = new AllowableRangeValues(Long.toString(myMin.value()), Long.toString(myMax.value()));
			} else if (myMin!=null) {
				// use Max value until "infinity" works 
				myvalues = new AllowableRangeValues(Long.toString(myMin.value()), Double.toString(Double.MAX_VALUE));
			} else if (myMax!=null) {
				// use Min value until "infinity" works 
				myvalues = new AllowableRangeValues(Double.toString(Double.MIN_VALUE), Long.toString(myMax.value()));
			}
			
			if (myvalues!=null) {
				System.out.println("myvalues: " + myvalues);
				mybuilder.allowableValues(myvalues);
				
			}

```

I used Double.MIN_VALUE/MAX_VALUE as the word "infinity" isn't working currently (java.lang.NumberFormatException: For input string: "infinity").

**Comment by JitendraSwagger** [comment] 2015-12-01 19:34
Hi jfiala, i have implemented the #356 validation as you have mentioned above. @NotNull is working but how should i test the @size annotation while viewing the swagger api docs. appreciate your help on it pls

**Comment by jfiala** [comment] 2016-01-30 20:49
Basic JSR-303 support including @NotNull, @Min, @Max and finally @Size is added in PR  #1159

**Comment by jfiala** [comment] 2016-01-30 20:50
Please let me know if I also should add support for the @Email (resolving to type "string").

**Comment by hgtran** [comment] 2016-02-01 13:54
@NotNull, @Min, @Max worked but not @Size for me

**Comment by jfiala** [comment] 2016-02-01 14:10
e.g.
``` java

    @Size(max=100)
    private String email;

    @Size(min= 5, max= 250)
    private String lastname;
   
    @Size(min=10)
    private String location;
    
   
```

should result in the following Swagger spec API docs:
```
email":
{

    "type": "string",
    "maxLength": ​100

},
"lastname": 
{

    "type": "string",
    "minLength": ​5,
    "maxLength": ​250

},
"location": 
{

    "type": "string",
    "minLength": ​10,
    "maxLength": ​2147483647

},

``` 
(works for me locally)

**Comment by hgtran** [comment] 2016-02-01 14:53
Thx, it works for me now. Just update to the last springfox-swagger2 (2.3.1)

**Comment by JcacMing** [comment] 2016-12-15 12:20
@dilipkrish  can you help me about validator of swagger2.0
