### ISSUE TITLE
Slow loading of UI on spec with many endpoints

### ISSUE THREAD

**Issue by danilobonilla** [springfox/springfox#875] opened 2015-07-22 12:47 UTC
I've gotten springfox-swagger2/springfox-swagger-ui 2.1.1  up and running on an app with many API endpoints and have noticed that the swagger-ui interface can take up to 5 minutes to load once i hit the swagger-ui.html. 

I've noticed on the browser network activity that the swagger-ui is hitting the /v2/api-docs roughly 1200 times and that doesn't seem right. 

Setting up caching for swagger doesn't seem to buy much time either. This is too long a time to wait for the interface to load. Is there something I might've misconfigured?

**Comment by dilipkrish** [comment] 2015-07-22 13:18
Could you try it with 2.1.2? Also another thing to try is to blow away your browser cache and try again. 

It may be an issue with swagger-ui

**Comment by danilobonilla** [comment] 2015-07-22 13:21
Sure thing, will try with 2.1.2

**Comment by dilipkrish** [comment] 2015-07-24 01:16
Closing this as its a duplicate of #848

**Closed by dilipkrish** 2015-07-24 01:16 UTC
Labels: duplicate
