### ISSUE TITLE
Keep property on response, but hide from request

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#895] opened 2015-08-05 11:50 UTC
Suppose a case where I have an Object that I use both for request and response from a Controller.
There is a field "String name"; it's sort of read-only. You can obtain it from response, but not pass it from request. 

Is there a way in springfox to "hide" it from request; but make it part of the response at the same time?
The only thing that comes to my mind is @ApiImplicitParams - but that is super ugly.

**Comment by dilipkrish** [comment] 2015-08-06 02:50
Currently this is not possible :cry: The request/response models are currently isomorphic. I'll chalk that as a :+1:  for the feature request.

**Comment by MaksimOrlov** [comment] 2016-08-29 21:35
Hi, from version 2.6 for @ModelAttribute annotated parameters it is possible to use @ApiParam(hidden=true) annotation at the class level property. That will hide parameter from request, but parameter will be remained at the response. More details #1382.

@ApiModelProperty(hidden=true) will hide property at both request and response regardless the annotation type (@ModelAttribute or @RequestBody)

**Comment by yaoshenghong** [comment] 2017-01-19 08:37
@MaksimOrlov Hi, I use v2.6.1 and add @ApiParam(hidden=true)  on the id property, but it still appears in the request Example Value.
![base](https://cloud.githubusercontent.com/assets/18024481/22099206/57c06038-de65-11e6-95b3-d519bb2a3151.png)
![value](https://cloud.githubusercontent.com/assets/18024481/22099207/57ccfc44-de65-11e6-8365-477eddd883e3.png)

**Comment by MaksimOrlov** [comment] 2017-01-19 10:54
Hi, @yaoshenghong!

It looks like your class **BaseEntity** was used as _@RequestBody_ parameter. 

Could you, please, provide your controllr's code?

_@ApiParam(hidden=true)_, as i mentioned before, works **ONLY** with _@ModelAtribut_e parameters. 

In case of _@RequestBody_ you should use _@ApiModelProperty(hidden=true)_

**Comment by yaoshenghong** [comment] 2017-01-20 02:46
@MaksimOrlov  Thanks for the reply!  Of course, I used  @RequestBody .

@ApiOperation(value = "add patient", notes = "add patient")
@PostMapping
@ResponseStatus(HttpStatus.CREATED)
public void add(@RequestBody Patient patient) {	
		patientService.add(patient);
}

As you say, @ApiModelProperty(hidden=true) will hide property at both request and response. I dont want to hide at the reponse, it will be perfect if @ApiParam(hidden=true) supports @RequestBody. 
Any way,  @ApiModelProperty(hidden=true) has to meet the requirements，thank you very much!

**Comment by MaksimOrlov** [comment] 2017-01-20 13:35
@yaoshenghong

If _@ApiParam(hidden=true)_ supports _@RequestBody_ then it will support it at both request and respond **inseparably**. So, the solution here is to use two different object, first for request, second for response. 

The _@JsonView_ feature, unfortunately, is still being under work....

**Comment by JcacMing** [comment] 2017-09-05 12:58
@MaksimOrlov @apiparam(hidden=true), as i mentioned before, works ONLY with @modelatribute parameters.In case of @requestbody you should use @apimodelproperty(hidden=true)

but paremeter Still appear
![image](https://user-images.githubusercontent.com/24521657/30062164-c2b58474-927c-11e7-907e-d47d7d2de7dd.png)
![image](https://user-images.githubusercontent.com/24521657/30062192-d3cbf0e0-927c-11e7-873b-e7edd77e751b.png)
![image](https://user-images.githubusercontent.com/24521657/30062210-ef8cc0a2-927c-11e7-8fa1-de1addc5323a.png)

**Comment by MaksimOrlov** [comment] 2017-09-05 13:15
@JcacMing unfortunately, it doesn't work in this way....

You annotated a whole _list_ with **_@ApiParam_**. Instead should annotate each property in **GdsMetaField** type, that you don't want to see in the documentation, with **_@ApiParam_**

Or as a better solution add **GdsMetaField**  type to _ignorable_ types, if _all fields_ should be ignored.

Annotations on a List level are ignored in case of @ModelAttribute, because each property _is treated as_ a single parameter.

**Comment by MaksimOrlov** [comment] 2017-09-05 14:05
I looked throw the current version of code, and it seems like that @apiingnore and ignorable types are NOT applied to the nested types. So, the **ONLY** way, is to annotate each property.

**Comment by JcacMing** [comment] 2017-09-06 02:14
@MaksimOrlov thank you the problem is solved

**Comment by JcacMing** [comment] 2017-09-06 02:25
@MaksimOrlov I suddenly thought there was still a problem, I used it（GdsMetaField ） in other position, but it did not need to be hidden, I would like to still need to solve the nested types of hidden problems

**Comment by MaksimOrlov** [comment] 2017-09-06 15:12
@JcacMing, there is no easy way to solve your problem at the current moment.....

There is one workaround with @apiimplicitparams and you can use it with @apiparam(hidden=true)

So, if you use one Class with the lot of endpoints but you need to hide some properties depending on method, then the only way is to hide some property at the all endpoints and then add it by @apiimplicitparams at the few specific endpoints.

**Comment by JcacMing** [comment] 2017-09-08 02:28
@MaksimOrlov I agree with your point of view, thank you very much for your answer

**Comment by dilipkrish** [comment] 2018-11-28 10:30
@rajsid1 Its tagged that but it hasn't been implemented. This was closed in lieu of #2056

**Comment by MaksimOrlov** [comment] 2019-05-28 12:31
PR #2056 has been merged to master and I would be grateful for feedback of this functionality.

**Comment by IncPlusPlus** [comment] 2019-08-11 19:52
@wind57, could #2816 be related to your issue? I think you could just use `@ApiModelProperty(readOnly = true)` for the time being until the properties of the `accessMode` field are respected by Springfox.

**Comment by XFNeo** [comment] 2019-12-12 10:56
@dilipkrish Is the issue fixed?
What annotation should I use to hide field from request body, but keep it for response?

**Comment by anandvarkeyphilips** [comment] 2020-01-21 09:32
> @dilipkrish Is the issue fixed?
> What annotation should I use to hide field from request body, but keep it for response?

`@ApiModelProperty(readOnly =true)`
is deprecated and
`@ApiModelProperty(accessMode = ApiModelProperty.AccessMode.READ_ONLY)`
is not working..

**Comment by gRizzlyGR** [comment] 2020-04-21 21:47
I've solved this way.

I have an ID field that is part of the User model. 

In the Swagger I want to show the ID in the GET response, but hide it in the POST request, since it's auto-generated by the server:

```java
public class User {
    private Integer id;
    private String name;

    public void setId(Integer Id) {
        this.id = id;
    }

    // It's important to put this annotation on the getter
    // and not on the field itself
	@ApiModelProperty(example = "1", value = "Id", dataType = "java.lang.Integer", readOnly = true)
    public Integer getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
```

I've subclassed User and hid the ID field "overriding" the getter. Actually the logic is the same, we just need to override the annotation.
```java
public class NoIdUser extends User {

    // In this way, the field is hidden for the controllers
    // that use this class
	@ApiModelProperty(hidden = true)
	@Override
	public Integer getId() {
		return super.getId();
	}
}
```

In the controller then I use the User POJO for the GET, and the NoIdUser POJO for the POST.
```java
    // Here we use a NoIdUser object.
	@PostMapping("/users")
	public ResponseEntity<String> addUser(@Valid @RequestBody NoIdUser user) {
        // logic for creation
	}

    // Other handlers

    // Here we return a list of User objects
    @GetMapping("/users")
    public List<User> getUsers(
        @RequestParam(value = "id") Integer id,
        @RequestParam(value = "name") String name) {

        // logic for retrieval
	}
```

HTH

**Comment by MaksimOrlov** [comment] 2020-04-22 09:16
Hi @gRizzlyGR.

With 3.0.0-SNAPSHOT version you can use `@JsonView` or `@JsonIgnore` on getter.

**Comment by dilipkrish** [comment] 2020-07-13 05:06
This is now available in 3.0.0

**Closed by dilipkrish** 2020-07-13 05:06 UTC
Labels: feature, help-wanted, in progress

**Comment by paulmarcelinbejan** [comment] 2020-07-16 07:42
> 
> 
> I've solved this way.
> 
> I have an ID field that is part of the User model.
> 
> In the Swagger I want to show the ID in the GET response, but hide it in the POST request, since it's auto-generated by the server:
> 
> ```java
> public class User {
>     private Integer id;
>     private String name;
> 
>     public void setId(Integer Id) {
>         this.id = id;
>     }
> 
>     // It's important to put this annotation on the getter
>     // and not on the field itself
> 	@ApiModelProperty(example = "1", value = "Id", dataType = "java.lang.Integer", readOnly = true)
>     public Integer getId() {
>         return id;
>     }
> 
>     public void setName(String name) {
>         this.name = name;
>     }
> 
>     public String getName() {
>         return name;
>     }
> }
> ```
> 
> I've subclassed User and hid the ID field "overriding" the getter. Actually the logic is the same, we just need to override the annotation.
> 
> ```java
> public class NoIdUser extends User {
> 
>     // In this way, the field is hidden for the controllers
>     // that use this class
> 	@ApiModelProperty(hidden = true)
> 	@Override
> 	public Integer getId() {
> 		return super.getId();
> 	}
> }
> ```
> 
> In the controller then I use the User POJO for the GET, and the NoIdUser POJO for the POST.
> 
> ```java
> // Here we use a NoIdUser object.
> @PostMapping("/users")
> public ResponseEntity<String> addUser(@Valid @RequestBody NoIdUser user) {
>     // logic for creation
> }
> 
> // Other handlers
> 
> // Here we return a list of User objects
> @GetMapping("/users")
> public List<User> getUsers(
>     @RequestParam(value = "id") Integer id,
>     @RequestParam(value = "name") String name) {
> 
>     // logic for retrieval
> }
> ```
> 
> HTH

The problem has not been resolved, since I use Lombok and I don't have the getter methods
I need something that I can use on the field and not on the getter.

**Comment by dilipkrish** [comment] 2020-07-16 12:05
You can use @ApiModelProperty on fields @paulmarcelinbejan
