### ISSUE TITLE
Please Help me !  SWAGER2.9.2 with spring boot2.06 not work .

### ISSUE THREAD

**Issue by nadjin** [springfox/springfox#2789] opened 2018-11-19 02:57 UTC
I'd tried a lot of ways ...  I don't know why? 

===================This is the problem===================
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation; but it does not exist. Its class, org.springframework.data.repository.support.Repositories, is available from the following locations:

    jar:file:/D:/program%20files/gradle-4.9/caches/modules-2/files-2.1/org.springframework.data/spring-data-commons/2.0.11.RELEASE/273e5cd5d6e772b5c4208b12771ed48647b2b9bb/spring-data-commons-2.0.11.RELEASE.jar!/org/springframework/data/repository/support/Repositories.class

It was loaded from the following location:

    file:/D:/program%20files/gradle-4.9/caches/modules-2/files-2.1/org.springframework.data/spring-data-commons/2.0.11.RELEASE/273e5cd5d6e772b5c4208b12771ed48647b2b9bb/spring-data-commons-2.0.11.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.data.repository.support.Repositories

Disconnected from the target VM, address: '127.0.0.1:54726', transport: 'socket'

Process finished with exit code 1

<br/><br/><br/><br/>
===================This is gradle config.===================

`buildscript {
	ext {
		springBootVersion = '2.0.6.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
//	maven { url "http://192.168.1.67/repository/maven/" }
//	maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
	mavenCentral()
}
ext {
	springCloudVersion = 'Finchley.SR1'
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
	compile('org.springframework.boot:spring-boot-starter-data-rest')
//	compile('io.springfox:springfox-data-rest:2.9.2-SNAPSHOT')
//	compile('io.springfox:springfox-swagger2:2.9.2-SNAPSHOT')
//	compile('io.springfox:springfox-swagger-ui:2.9.2-SNAPSHOT')
	compile('io.springfox:springfox-data-rest:2.9.2')
	compile('io.springfox:springfox-swagger2:2.9.2')
	compile('io.springfox:springfox-swagger-ui:2.9.2')
	compile('com.h2database:h2:1.4.196')
//	compile("org.springframework.data:spring-data-rest-webmvc:3.1.2.RELEASE")
//	compile group: 'org.springframework.data', name: 'spring-data-commons', version: '2.1.1.RELEASE'
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

bootRun{
	jvmArgs = ["-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"]
}
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}`

Thank u .

**Comment by carlislefox** [comment] 2018-11-22 18:37
Hey buddy,

From what I can gather (as I am in the same boat as you) Spring boot 2.0 (and onwards) isn't supported yet, we are waiting for the release of Swagger-UI 3.

**Comment by dilipkrish** [comment] 2018-11-28 10:15
This is a duplicate of #2345

**Closed** 2020-07-08 13:20 UTC
Labels: duplicate, question, wontfix
