### ISSUE TITLE
@ApiIgnore // @ApiParam(hiddent=true) doesn't remove parameter from the api-docs

### ISSUE THREAD

**Issue by kent2171** [springfox/springfox#1438] opened 2016-08-04 13:01 UTC
- swagger-ui version - io.springfox:springfox-swagger-ui:2.5.0
- swagger-core - io.springfox:springfox-swagger2:2.5.0

@ApiIgnore || @ApiParam(hidden = true) doesn't remove parameter from the api-docs response.
Workaround is to set classes, that are need to be ignored, in configuration (.ignoredParameterTypes(Pageable.class)), by I think that it's not a best aproach.

I read though the docs and couldn't understand why it's not working

An example of method configuration
```java
@ApiOperation(value = "Lists all available items, response is paginated")
    @ApiResponses(value = {
        @ApiResponse(
            code = 200,
            message = "Success",
            response = ItemDTO.class,
            responseContainer = "List"
        )
    })
    @ApiImplicitParams({
        @ApiImplicitParam(
            name = "page", dataType = "integer", paramType = "query",
            value = "results page you want to retrieve (0..N)"
        ),
        @ApiImplicitParam(
            name = "size", dataType = "integer", paramType = "query",
            value = "number of records per page"
        ),
        @ApiImplicitParam(
            name = "sort", dataType = "string", paramType = "query",
            value = "sorting criteria in the format: property(asc|desc), " +
                "default sort order is ascending, " +
                "multiple sort criteria are supported"
        )
    })
    @RequestMapping(
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_UTF8_VALUE
    )
    @ResponseStatus(HttpStatus.OK)
    public List<?> getList(
        @AuthenticationPrincipal
        UserPrincipal principal,
        @ApiParam(value = "types of the items, that need to be retrieved", allowMultiple = true)
        @RequestParam(name = "type", required = false)
        List<ItemTypeDTO> types,
        @ApiParam(value = "states of the items, that need to be retrieved", allowMultiple = true)
        @RequestParam(name = "state", required = false)
        List<ItemStateDTO> states,
        @ApiParam("the date on which the item shouldn't be expired")
        @RequestParam(name = "dueDate", required = false)
        Long dueDate,
        @ApiIgnore
        @ApiParam(hidden = true)
        Pageable pageRequest) {
            return Collections.emptyList();
        }
```

**Comment by dilipkrish** [comment] 2016-08-05 00:50
@kent2171 Its a regression in 2.5.0. Added `ApiIgnore.class` to the list of ignorableTypes in your docket and it should be fine. this is a duplicate of #1346

**Closed** 2016-09-25 17:21 UTC
Labels: duplicate

**Comment by krisso-b** [comment] 2017-06-09 13:21
We had the same issue.
The fix was easy - we were missing setters in our code.

**Comment by Kev1nDwx** [comment] 2018-01-17 06:51
like very mch

**Comment by rahulaga** [comment] 2018-09-24 23:56
I am on 2.7.0 and this still does not work. However using `@ApiModelProperty(hidden = true)` works.

**Comment by dilipkrish** [comment] 2018-11-12 01:45
@rahulaga you need to move to 2.9.2
