### ISSUE TITLE
dataType="file" is not working in springfox 2.4.0

### ISSUE THREAD

**Issue by HDBandit** [springfox/springfox#1285] opened 2016-04-25 19:18 UTC
This @ApiImplicitParam(dataType = "file", name = "image1", required = true, paramType = "form") is working in version 2.2.2, but if I migrate to the last version (2.4.0) , it doesn't recognize the parameter image1 like a file.

**Comment by dilipkrish** [comment] 2016-04-25 20:40
If you use a Multipart file it should just work

**Comment by HDBandit** [comment] 2016-04-25 20:45
Hi,

Yes I am using multipart_file...but it doesn't work. Conguring the version
2.2.2 it works.

My request mapping consumer a multipart fie, method POST...

If you say that it works, maybe I am doing something wrong, but with
version 2.2.2 all is fine.

Thank you very much.

2016-04-25 22:41 GMT+02:00 Dilip Krishnan <notifications@github.com>:

**Comment by dilipkrish** [comment] 2016-04-25 20:47
Could you share your request mapping? Also try removing the `ApiImplicitParam` annotation

**Comment by HDBandit** [comment] 2016-04-25 21:11
Here you are my request mapping, I am using spring annotations

@RequestMapping(value = "/{userId}/exchange", method = RequestMethod.POST,
consumes = MediaType.MULTIPART_FORM_DATA_VALUE)


and I am using

@ApiImplicitParams (value = {

       @ApiImplicitParam(dataType = "file", name = "image2", required = true,
paramType = "form")

}

2016-04-25 22:47 GMT+02:00 Dilip Krishnan <notifications@github.com>:

**Comment by maksimu** [comment] 2016-04-26 18:38
same here, just switched from Springfox 2.3.x to 2.4.0 and this code stopped producing file picker:

```java
@ApiParam(required = true) @RequestPart MultipartFile document)
```

This issue is similar to https://github.com/springfox/springfox/issues/588

**Comment by dilipkrish** [comment] 2016-04-29 15:17
I think this may be a regression, let me investigate

**Comment by HDBandit** [comment] 2016-04-29 16:02
Hi again,

In fact, I achieved to resolve my issue. Instead of use MongoTemplate and
Criteria class to create the query, I used the mongo repository with the
method declaration:

GeoResults<ExchangeLocation> findByLocationNear(Point point, Distance min,
Distance max);

And with my attribute Point location annotated with @GeoSpatialIndexed(type
= GeoSpatialIndexType.GEO_2DSPHERE)

I thought that the two ways were the same, but it seems I was wrong. In
fact if you copy the same code that you show in your screencast it works.
My mistake was to use MongoTemplate, I don't know why.

Thank you so much for your answer.

Have a nice day.
Gerard

2016-04-29 17:17 GMT+02:00 Dilip Krishnan <notifications@github.com>:

**Comment by dilipkrish** [comment] 2016-05-27 23:32
Seems to be fixed in 2.4.1-SNAPSHOT. Can one of you confirm?

**Comment by dilipkrish** [comment] 2016-06-02 00:58
Closing this as it appears to be fixed! Please reopen if it doesn't work post _2.5.0_

**Closed by dilipkrish** 2016-06-02 00:58 UTC
Labels: bug

**Comment by jrahahli** [comment] 2017-03-11 00:24
This functionality is broken in 2.7.0-SNAPSHOT, but works in 2.6.1

**Comment by dilipkrish** [comment] 2017-03-16 01:44
@ghost Yes it had to be changed to use "__file" in order to not collide with a library defining a class that is file as well.
