### ISSUE TITLE
Error creating bean with name 'apiDescriptionReader' since no args were given (spring 3.2.x)

### ISSUE THREAD

**Issue by choiapril6** [springfox/springfox#927] opened 2015-08-24 07:16 UTC
Error creating bean with name 'apiOperationReader' too.

springfox v2.2.0, spring v3.2.8 used.

Any solution?

I'd appreciate your answer so much.

**Comment by dilipkrish** [comment] 2015-08-26 14:23
@choiapril6 did you resolve your issue. I think one thing I would try with the following set up
springfox 2.2.2
spring 3.2.8

- update your dependency on aspectj weaver to **org.aspectj:aspectjweaver:1.8.6**

See  if that fixes your problem. Also could you share you BeanCreationException stack trace?

**Comment by choiapril6** [comment] 2015-08-26 15:45
Yes i did. I just down-versioned springfox dependency to 2.0.1. On this, it worked, finally. I need to figure out how springfox does this to start developing my api documentation system, though. I think I have to try your solution too on a new branch to use springfox 2.2.2. I appreciate it. I will give you some feedback after trying. Thank you.

**Comment by dilipkrish** [comment] 2015-08-26 15:54
👍🏼 please do share your findings as I suspect there will be quite a few with a similar problem.

**Comment by dilipkrish** [comment] 2015-09-10 02:35
Closing this a duplicate of #921

**Closed by dilipkrish** 2015-09-10 02:35 UTC
Labels: bug, duplicate
