### ISSUE TITLE
spring boot 3.0.x swagger doesn't work

### ISSUE THREAD

**Issue by MBasdas** [springfox/springfox#4049] opened 2023-01-19 10:00 UTC
Hi I am using spring boot 3.0.x latest version and Java 17. 

When I add this dependencies on the 2.7.x spring boot project its work fine without any configuration..

But when I use this dependencies on the 3.0.x spring boot version it doesn't work.

<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.14</version>
</dependency>,

<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
     <version>3.0.0</version>
</dependency>,

<dependency>
          <groupId>io.springfox</groupId>
           <artifactId>springfox-boot-starter</artifactId>
          <version>3.0.0</version>
</dependency>

I made a configuration like this;

@EnableSwagger2
@Configuration
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.example.demo"))
                .paths(PathSelectors.any())
                .build();
    }

}

When I use this configuration the project doesn't start because of @EnableSwagger2 and I need to add this dependency on the project

<dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>

After this dependency the project is starting but I can't reach to

localhost:8080/swagger-ui.html
localhost:8080/swagger-ui/
localhost:8080/swagger-ui/index.html
localhost:8080/swagger-ui/swagger-ui.html

All of them show me Whitelabel page. 

My restful apis are work fine.

Why I cant use swagger without configuration on spring boot 3.0.x ?
Or if i need to make any configuration what is it?

**Comment by strazdinsg** [comment] 2023-01-30 13:07
Duplicate of #3983

**Closed as completed** 2023-01-30 13:52 UTC
