### ISSUE TITLE
@ApiParam not working in interface

### ISSUE THREAD

**Issue by piyushj90** [springfox/springfox#2239] opened 2018-02-08 11:29 UTC
I have added @ApiParam annotation in interface method, but it is not working. Please let me know, if it is fixed in v2.8.0.
Below is code sample:
`@ApiOperation(value = "Find")
ResponseDto find(@ApiParam(value = "Filter Criteria", required = true) String filterCriteria,      HttpServletResponse response);`

I am using springfox v2.8.0

**Comment by dilipkrish** [comment] 2018-02-09 11:23
@piyushj90 It is not fixed #1575

**Comment by 3t-dev** [comment] 2018-08-04 03:55
Could you try to add more `@RequestParam` annotation, like as `@ApiOperation(value = "Find") ResponseDto find(@ApiParam(value = "Filter Criteria", required = true) @RequestParam() String filterCriteria, HttpServletResponse response);`?
It works for me.

**Comment by lafangyuan** [comment] 2018-09-05 01:02
so which version solves this bug?

**Comment by astral-keks** [comment] 2018-09-19 15:26
the issue is still reproducible for springfox-swagger2:2.9.2

**Comment by dilipkrish** [comment] 2018-11-12 02:09
It isnt fixed yet please track #1575

**Comment by dilipkrish** [comment] 2020-07-13 03:52
Closing as duplicate of #1575

**Closed by dilipkrish** 2020-07-13 03:52 UTC
Labels: bug, duplicate
