### ISSUE TITLE
springfox-swagger2 doesn't respect ApiModelProperty#position

### ISSUE THREAD

**Issue by olkulyk** [springfox/springfox#766] opened 2015-05-30 19:19 UTC
When using springfox-swagger2:2.0.0, properties in the model are always ordered in alphabetical order.
Specifying [ApiModelProperty.position](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiModelProperty.java#L84) doesn't change the ordering.

I've created a small project to demonstrate the issue. Properties for `Entity` model are not ordered.

##How to reproduce
1. Clone https://github.com/olkulyk/springfox-swagger-property-ordering
2. run via `mvn spring-boot:run`
3. In the browser open `http://localhost:8080/v2/api-docs?group=entity-api` and find Entity definition. It will be smth like
```
Entity: {
    required: [
        "id",
        "status"
    ],
    properties: {
        comment: {
            type: "string",
            description: "comment description"
        },
        description: {
            type: "string",
            description: "description"
        },
        id: {
            type: "integer",
            format: "int32",
            description: "id description"
        },
        status: {
            type: "string",
            description: "status description"
        }
    }
}
```

Expected order according to [model definition](https://github.com/olkulyk/springfox-swagger-property-ordering/blob/master/src/main/java/demo/domain/Entity.java) is `id, status, description, comment`

**Comment by dilipkrish** [comment] 2015-08-11 02:57
This should now be fixed in 2.1.2

**Comment by sbuettner** [comment] 2015-11-04 08:33
Seems to be still an issue.

**Comment by tmalini** [comment] 2015-12-15 05:43
This issue exists in 2.3.0. Could this be fixed?

**Comment by dilipkrish** [comment] 2015-12-15 05:54
This cannot be fixed anymore that it has been. :) the problem is that the
properties are a hashmap and by definition they don't have a sort order.

**Comment by sbuettner** [comment] 2015-12-15 09:46
Just curious: Couldnt you just sort the properties by their `position` property in the rendering process?

**Comment by dilipkrish** [comment] 2015-12-15 13:55
Ah sorry my bad! I kept seeing *postion* but reading *name*. It is currently sorted by *name*. I'll reopen

**Comment by dilipkrish** [comment] 2015-12-15 14:02
Actually I remember why it wasn't possible beyond sorting on name. The problem here is that the `swagger-core` data structures [don't support it](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/mappers/ModelMapper.java#L74-L81).

**Closed by dilipkrish** 2015-12-15 14:02 UTC
Labels: feature

**Comment by sbuettner** [comment] 2015-12-15 14:23
Since you already use a collection type that supports sorting with `TreeMap` you could simply pass a comparator that sorts its values using the `Property.getPosition()` method.

**Comment by dilipkrish** [comment] 2015-12-15 14:55
Actually the [comparator on the TreeMap](http://docs.oracle.com/javase/7/docs/api/java/util/TreeMap.html#TreeMap(java.util.Comparator))  is only for the keys, so that won't work.

**Comment by sbuettner** [comment] 2015-12-15 15:01
Since you already got the Property Map you could lookup the Property by its key or do the comparison upfront and insert the keys into a `LinkedHashMap`.

**Comment by dilipkrish** [comment] 2015-12-15 15:03
PR?

**Comment by sbuettner** [comment] 2015-12-15 18:28
Sure, i will try to figure it out.
