### ISSUE TITLE
The Swagger 2.0 spec documentation for refactor/538/spike-to-seperate-models-and-dtos branch is out-of-date

### ISSUE THREAD

**Issue by who** [springfox/springfox#633] opened 2015-03-30 17:02 UTC
As I understand it, the **refactor/538/spike-to-seperate-models-and-dtos** branch will address compatibility with the Swagger 2.0 spec.  However, the documentation for getting up and running isn't available yet.

The Swagger 1.x documentation in the master branch for the `@EnableSwagger` strategy is great; it can be followed to get up and running in short order.  It would be great to see this quality of doc as it pertains to the **refactor/538/spike-to-seperate-models-and-dtos** branch.

**Comment by dilipkrish** [comment] 2015-03-30 17:21
@who working on that. Documentation is sparse because we want to polish the Apis before publishing some thing releasable. However I have started working on the transition documentation. Should be up today.

**Comment by dilipkrish** [comment] 2015-03-30 20:52
Closing this as its a duplicate of  #531. More documentation to come, but please share your experiences with the early 2.0.0 stuff so that we can improve the documentation

**Closed by dilipkrish** 2015-03-30 20:52 UTC
