### ISSUE TITLE
Class Support for @ApiImplicitParam

### ISSUE THREAD

**Issue by jimhooker2002** [springfox/springfox#1535] opened 2016-10-20 13:08 UTC
This is essentially a re-open of issue https://github.com/springfox/springfox/issues/468

My use case looks like this:

@ApiImplicitParams(@ApiImplicitParam(dataType = "Session", name = "session", paramType = "body"))
public Session patch(@PathVariable long id, HttpServletRequest session) {

I need the HttpServletRequest so that I can call getInputStream() on it. I need the raw JSON so that I can feed it through https://github.com/daveclayton/json-patch. The JSON once deserialized into a model object is no good to me (once deserialized I can't tell which parts of the model are defaults and which parts got set as part of the original JSON).

So, I need a HTTPServletRequest as the input to my controller method, but I'd like to document the real data type in the Swagger UI.

Currently only base types are supported here: https://github.com/springfox/springfox/blob/ff512629f1adf4ef146f367efa29c0c3b3664b7c/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationImplicitParameterReader.java#L83

If this method allowed the class name to be passed through i.e. support for more than just base types then the Swagger docs would be generated showing the correct model.  The Swagger docs for this annotation mention that a class name is also permissible.

I can't see any work-around currently. For now my HttpServletRequest params have only a name specified and the data-type is set merely to object (not very helpful).

Here's is a suggested fix: https://github.com/springfox/springfox/pull/1529

**Comment by dilipkrish** [comment] 2016-10-20 16:40
Still wondering about the fix. While your use case is certainly legit, but it opens up an issue that the wire representation *may not* match the swagger representation. There is no good way to check that its consistent. 

The code you've highlighted (and proposed a fix for), is working as expected if you look at it, you are expecting a string in the body (stream of bytes) and it is represented as a string in swagger. The problem is how do we also note that the string is actually a json representation of a typed object. 

There is definitely opportunity to improve this, just not sure what it is. Open to ideas.

**Comment by dilipkrish** [comment] 2016-10-25 18:38
Fixed via #1529

**Closed by dilipkrish** 2016-10-25 18:38 UTC
Labels: feature
