### ISSUE TITLE
Springfox-UI not showing custom examples

### ISSUE THREAD

**Issue by SledgeHammer01** [springfox/springfox#3163] opened 2019-10-25 21:27 UTC
springfox-swagger2 2.9.2
springfox-swagger-ui 2.9.2

Controller method looks like this:

	@ApiOperation(value="Creates a customer.")
	@ApiResponses(value={
		@ApiResponse(code=200, message="OK"),
		@ApiResponse(code=401, message="Unauthorized")
	})
	@PreAuthorize("#oauth2.hasScope('Any')")
	@RequestMapping(value="/customers", method=RequestMethod.POST, consumes="application/json", produces="application/json")
	public Customer createCustomer(@ApiParam(value="New customer to create.", required=true, examples=@Example(value=@ExampleProperty(mediaType="application/json", value = "{'firstName': 'John', id: 0, lastName='Smith'}"))) @RequestBody Customer customer) {
		return customer;
	}

When I look at the swagger page, the example is shown as:

{   "firstName": "string",   "id": 0,   "lastName": "string" }

I've also tried \" instead of ' in the example json... same issue. Also tried ApiImplicitParam... same issue.

.json looks like this:

      "post": {
        "tags": [ "Customer" ],
        "summary": "Creates a customer.",
        "operationId": "createCustomerUsingPOST",
        "consumes": [ "application/json" ],
        "produces": [ "application/json" ],
        "parameters": [
          {
            "in": "body",
            "name": "customer",
            "description": "New customer to create.",
            "required": true,
            "schema": { "$ref": "#/definitions/Customer" },
            "x-examples": { "application/json": "{'firstName': 'John', id: 0, lastName='Smith'}" }
          }
        ],

NOTE: This is on the "Example Value" tab... the "Model" tab shows the values from the model specified with @ApiModelProperty(notes="Id of the customer.", required=true, value="1").

**Comment by SledgeHammer01** [comment] 2019-10-25 21:28
FYI, also have the same issue on @ApiResponse examples not getting rendered.

**Comment by ogerardin** [comment] 2019-11-07 15:35
Duplicate of https://github.com/springfox/springfox/issues/3037 ?

**Closed** 2020-07-08 05:05 UTC
Labels: wontfix
