### ISSUE TITLE
Springfox randomly throwing  java.lang.IllegalStateException

### ISSUE THREAD

**Issue by gigecogary** [springfox/springfox#3211] opened 2019-12-16 21:06 UTC
I'm getting a random behaviour. On application start I'm randomly getting 

```
2019-12-16 16:00:07.403  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: agencyAgentsUsingGET_1
2019-12-16 16:00:08.185  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: insuranceCompanyOrdersUsingGET_1
2019-12-16 16:00:08.583  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: invoiceOrdersUsingGET_1
2019-12-16 16:00:09.685  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: orderEmailLogsUsingGET_1
2019-12-16 16:00:09.942  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: orderMobileExpensesUsingGET_1
2019-12-16 16:00:10.045  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: orderServiceItemsUsingGET_1
2019-12-16 16:00:10.900  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userAgentOrdersUsingGET_1
2019-12-16 16:00:10.901  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userAgentOrdersUsingDELETE_1
2019-12-16 16:00:11.075  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userClientOrdersUsingGET_1
2019-12-16 16:00:11.076  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userClientOrdersUsingDELETE_1
2019-12-16 16:00:11.191  INFO 29847 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userMobileExpensesUsingGET_1
2019-12-16 16:00:11.374 ERROR 29847 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Unable to scan documentation context default

java.lang.IllegalStateException: Ambiguous models equality when conditions is empty.
	at springfox.documentation.spring.web.scanners.ApiModelReader.checkCondition(ApiModelReader.java:655) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeConditions(ApiModelReader.java:537) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:236) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeNodes(ApiModelReader.java:262) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:209) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:149) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:144) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:69) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.scanDocumentation(AbstractDocumentationPluginsBootstrapper.java:97) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:83) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:94) ~[springfox-spring-web-3.0.0-20190808.104142-38.jar:null]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at net.gigeco.GigecoApplication.main(GigecoApplication.java:17) ~[classes/:na]
```

But sometimes I see that it goes through fine:
```
2019-12-16 16:02:42.189  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: agencyAgentsUsingGET_1
2019-12-16 16:02:42.929  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: insuranceCompanyOrdersUsingGET_1
2019-12-16 16:02:43.127  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: invoiceOrdersUsingGET_1
2019-12-16 16:02:44.492  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: orderEmailLogsUsingGET_1
2019-12-16 16:02:44.748  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: orderMobileExpensesUsingGET_1
2019-12-16 16:02:44.855  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: orderServiceItemsUsingGET_1
2019-12-16 16:02:46.030  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userAgentOrdersUsingGET_1
2019-12-16 16:02:46.032  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userAgentOrdersUsingDELETE_1
2019-12-16 16:02:46.203  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userClientOrdersUsingGET_1
2019-12-16 16:02:46.204  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userClientOrdersUsingDELETE_1
2019-12-16 16:02:46.311  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: userMobileExpensesUsingGET_1
2019-12-16 16:02:46.332  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: handleUsingGET_1
2019-12-16 16:02:46.334  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: handleUsingGET_2
2019-12-16 16:02:46.335  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: handleUsingGET_3
2019-12-16 16:02:46.336  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: handleUsingGET_4
2019-12-16 16:02:46.338  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: handleUsingGET_5
2019-12-16 16:02:46.339  INFO 29971 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: handleUsingGET_6
```

I noticed that it started failed at around  "Generating unique operation named: handleUsingGET_1"

How do I fix this?

I'm using 
```

 <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-spring-webmvc</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
 <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-data-rest</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>io.swagger</groupId>
                    <artifactId>swagger-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.swagger</groupId>
                    <artifactId>swagger-models</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by MaksimOrlov** [comment] 2019-12-18 03:08
Duplicate of #2345

**Comment by MaksimOrlov** [comment] 2020-02-08 22:09
Here is the PR #3247 to fix this issue.

**Closed** 2020-02-24 12:27 UTC
Labels: duplicate

**Comment by MaksimOrlov** [comment] 2020-02-24 13:37
PR with fixes has been merged.

And I'll be grateful for your feedback, if the issue was gone. 
Otherwise feel free to reopen the issue.
