### ISSUE TITLE
/v2/api-docs page fails with 404 error

### ISSUE THREAD

**Issue by sushiesharma** [springfox/springfox#2808] opened 2018-12-06 16:50 UTC
version: 3.0.0-SNAPSHOT

/v2/api-docs page fails with 404 error

 Swagger.json was available on https://host:port/context/v2/api-docs a week ago but since a week , getting 404 on the specified URL.

Snapshot of build.gradle
![image](https://user-images.githubusercontent.com/33965118/49598264-3e214a80-f94c-11e8-8f7f-fbca4aa9766f.png)

Snapshot of Browser error
![image](https://user-images.githubusercontent.com/33965118/49598618-06ff6900-f94d-11e8-813a-752dac963fde.png)

Error log on console
2018-12-06 11:44:43.471  WARN 8120 --- [ctor-http-nio-4] s.d.s.web.Swagger2ControllerWebFlux      : Unable to find specification for group default

Please help as it is affecting project delivery.

**Comment by VandanaJagadeesh** [comment] 2018-12-06 16:52
+1

**Comment by guillermolam** [comment] 2018-12-06 17:34
+1

**Comment by ybanda** [comment] 2018-12-06 18:00
I think its the same issue as in #2802

**Comment by amutsch** [comment] 2018-12-11 17:06
@sushiesharma 

I tested this on a microservice using as I already had that setup.  
implementation("io.springfox:springfox-swagger-ui:${swaggerVersion}")
    implementation("io.springfox:springfox-swagger2:${swaggerVersion}")
    implementation("io.springfox:springfox-data-rest:${swaggerVersion}")

the v2 context and swagger ui came up without issues.

A snapshot project in active development is not a recommended import to a project as snapshot should imply changing without notice. 

Are there other logs during the startup process that may indicate a problem?  
Is your project available on github to clone?
Do you see the api docs properly posting with a log entry like:
2018-12-11 10:55:39.147  INFO 18832 --- [           main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2ControllerWebMvc.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]

**Comment by dilipkrish** [comment] 2018-12-17 11:17
@amutsch thanks for helping!

**Comment by sharmasushma** [comment] 2018-12-26 22:53
Something was clashing with Consul dependency. Everything is working fine , after I removed below dependency from build.gradle

'org.springframework.cloud:spring-cloud-starter-consul-all:2.0.0.RELEASE'

Thank you for your efforts.

**Comment by thiagokuch** [comment] 2018-12-28 11:43
I used the spring-cloud-starter-consul-config instead of spring-cloud-starter-consul-all and the problem isn't happens. But when I use the spring-cloud-starter-stream-kafka (that has the spring-integration in its dependencies) the problem happens. Do you have some workaround to this?

**Comment by vagneroliveirars** [comment] 2018-12-28 12:00
+1

**Comment by predrag-viceic** [comment] 2019-03-18 15:32
Hello,

Quick note to inform that I have had the same problem, and in order to solve it, I had to remove (unused) org.springframework.batch:spring-batch-integration from the build.

I suspect that this issue is somehow related to spring integration.

**Comment by archmagece** [comment] 2019-05-10 08:43
Maybe.. I found solution.

### Conclusion First - append this
```
implementation 'io.springfox:springfox-spring-integration-webflux:3.0.0-SNAPSHOT'
implementation('org.springframework.integration:spring-integration-webflux')
```

### You may use this now...
```
implementation('org.springframework.boot:spring-boot-starter-webflux')
implementation('org.springframework.cloud:spring-cloud-starter-stream-kafka')

implementation 'io.springfox:springfox-swagger2:3.0.0-SNAPSHOT'
implementation 'io.springfox:springfox-swagger-ui:3.0.0-SNAPSHOT'
implementation 'io.springfox:springfox-spring-webflux:3.0.0-SNAPSHOT'
```

**Comment by hc-codersatlas** [comment] 2019-08-07 04:46
Isn't this because springfox still depends on an old release of spring-plugin-metadata?

**Comment by dilipkrish** [comment] 2019-08-08 10:53
@hc-codersatlas Can you elaborate? Is that a bug that you know off?

**Comment by hc-codersatlas** [comment] 2019-08-12 13:40
@dilipkrish the latest Spring that I've tried uses releases >1.2.0 for Spring plugin metadata and Spring plugin core. These new versions aren't working with Springfox. Have you tested with these versions?

**Comment by dilipkrish** [comment] 2019-08-16 10:55
This is a duplicate of another issue regarding spring plugin version thanks @hc-codersatlas or clarifying.

**Closed** 2020-07-08 07:30 UTC
Labels: duplicate, question, wontfix
