### ISSUE TITLE
Spring data rest Expected response != Actual response

### ISSUE THREAD

**Issue by imduffy15** [springfox/springfox#1879] opened 2017-06-22 13:00 UTC
Version: 2.7.0

Spring fox seems to be expecting a different returned object for the hateoas resources than what is really returned.

Example:

Expected: 

```json
{
  "embedded": [
    {
      "active": true,
      "name": "string",
      "language": "string"
    }
  ],
  "links": [
    {
      "href": "string",
      "rel": "string",
      "templated": true
    }
  ]
}
```

actual:

```json
{
  "_embedded": {
    "people": [
      {
        "name": "Billy bob",
        "active": true,
        "language": "en"
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:9000/api/people{?page,size,sort}",
      "templated": true
    },
    "profile": {
      "href": "http://localhost:9000/api/profile/people"
    }
  },
  "page": {
    "size": 2147483647,
    "total_elements": 1,
    "total_pages": 1,
    "number": 0
  }
}
```

Note:

 - `embedded` vs `_embedded`
 - `links` vs `_links`
 - `_embedded` as an object containing resources names that are arrays
 - No paging information, optional maybe?

**Comment by dilipkrish** [comment] 2017-07-04 20:33
Let me think about a good solution for this...

**Comment by dilipkrish** [comment] 2017-12-05 02:12
Closing of duplicate of #1927

**Closed by dilipkrish** 2017-12-05 02:12 UTC
Labels: duplicate, in progress
