### ISSUE TITLE
Schema error: path parameters should not have additional property allowEmptyValue

### ISSUE THREAD

**Issue by agusevas** [springfox/springfox#2419] opened 2018-05-14 15:30 UTC
- [x] What version of the library are you using? 
2.9

What kind of issue is this?
 - [x ] Bug report. 
The online Swagger editor shows the following errors:

> Schema error at paths['/cart/coupons/{couponId}'].delete.parameters[0]
> should NOT have additional properties
> additionalProperty: type, allowEmptyValue, format, name, in, description, required

Generated Swagger definition:
```
parameters:
        - name: couponId
          in: path
          description: The coupon id
          required: true
          type: string
          allowEmptyValue: false
          format: uuid
```

The Java code:
```
@DeleteMapping("/coupons/{couponId}")
public CartTO deleteCoupon(@PathVariable @ApiParam(value = "The coupon id", required = true) UUID couponId) {
        return cartService.deleteCoupon(couponId);
    }
```

according to the Swagger Specification the `allowEmptyValue` should be generated only for `query` or `formData` parameters. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject for more information.

**Comment by dilipkrish** [comment] 2018-05-31 01:42
Thanks for reporting this is a bug. The work around is to not annotate with `ApiParam`

**Comment by darkprokoba** [comment] 2018-06-19 15:13
Any chance this gets fixed in a near release?

**Comment by dilipkrish** [comment] 2018-06-19 23:31
This is by design. Its unfortunate that allowEmptyValue is not defaulted to null (try-state boolean). But springfox assumes that if you use the swagger annotations, you know what you're doing. So if it uses the defaults, its your responsibility to set the non-default value you prefer.

Having said that I'll see what I can do.

**Comment by darkprokoba** [comment] 2018-06-20 10:48
>  I'll see what I can do.
Thanks!

> its your responsibility to set the non-default value you prefer.
I've read the code and I don't see how to tell it not to emit the allowEmptyValue attribute for a path param, besides not using the @ApiParam annotation at all.

Can you clarify if @ApiParam is supported for path parameters?

**Comment by dilipkrish** [comment] 2018-06-21 11:27
ApiParam is supported for path parameters. What is happening is that you have it annotating your coupon id parameter and the allowEmptyValue is not set. So it uses the default annotation value which is false. 

You need to set the `allowEmptyValue=false` in your annotation.

**Comment by patrickbray** [comment] 2018-06-21 22:04
In my experience even setting `allowEmptyValue=false` in the annotation outputs this in the swagger which is considered non valid (for path parameters) by the swagger parser let me try create a basic test case for this.

**Closed** 2018-06-23 11:43 UTC
Labels: bug, has-workaround
