### ISSUE TITLE
Custom endpoint not working

### ISSUE THREAD

**Issue by raderio** [springfox/springfox#1550] opened 2016-10-27 07:34 UTC
```
compile group: "io.springfox", name: "springfox-swagger2", version: "2.6.0"
compile group: "io.springfox", name: "springfox-swagger-ui", version: "2.6.0"
```

```
@Configuration
@EnableSwagger2
public class SwaggerConfiguration {

    @Bean
    public Docket swagger() {
        ApiInfo apiInfo = new ApiInfo(
                "My REST API",
                "Some custom description of API.",
                "API TOS",
                "Terms of service",
                new Contact("name", "url", "email"),
                "License of API",
                "API license URL");

        Docket docket = new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo)
                .select()
                .build();

        return docket;
    }
}
```
application.propeties
`
springfox.documentation.swagger.v2.path=/appi`

**Comment by dilipkrish** [comment] 2016-10-27 14:04
Closing as duplicate of #1532. This should be fixed in 2.6.1 which should be out today

**Closed by dilipkrish** 2016-10-27 14:04 UTC
Labels: bug, duplicate

**Comment by raderio** [comment] 2016-10-31 08:44
Hi. When it will out? https://mvnrepository.com/artifact/io.springfox/springfox-swagger2

**Comment by dilipkrish** [comment] 2016-10-31 16:05
It should be out in the next couple days
