### ISSUE TITLE
Swagger-UI with webjar in spring boot does not point to right host

### ISSUE THREAD

**Issue by panshul007** [springfox/springfox#606] opened 2015-03-11 10:02 UTC
Inside the *sdoc.jsp* the variable in the address path
**${pageContext.request.contextPath}** does not get resolved.
Is there a way to pass it as a parameter or set it externally?

**Comment by dilipkrish** [comment] 2015-03-24 21:57
Closing this as its a  duplicate of https://github.com/springfox/springfox/issues/496. Let us know if that resolves your issues

**Closed by dilipkrish** 2015-03-24 21:57 UTC
Labels: duplicate
