### ISSUE TITLE
Cannot specify client_id param in Implicit OAuth2 flow

### ISSUE THREAD

**Issue by martin3361** [springfox/springfox#1537] opened 2016-10-21 13:26 UTC
When using the implicit flow for OAuth2, the request is sent to the server, but the client_id is nowhere to be found in the Swagger config, which could be specified.
The request sent actually contains parameters such as client_id and realm. This is the outcome URL:

`http://AUTH_SERVER/oauth/authorize?response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A64259%2Fwebjars%2Fspringfox-swagger-ui%2Fo2c.html&realm=undefined&client_id=undefined&scope=phoenix&state=oauth2schema`

Below is my code for Swagger configuration. I'm using Swagger 2.6.0.

```
private static final Predicate<String> SWAGGER_PATHS = PathSelectors.regex("^(?!.*error$).*");

@Value("${security.oauth2.resource.authorizationUri}")
private String authorizationUri;

@Value("${application.swagger.pathMapping}")
private String swaggerPathMapping;

@Value("${application.swagger.apiInfoTitle}")
private String apiInfoTitle;

@Value("${application.swagger.apiInfoDescription}")
private String apiInfoDescription;

/**
 * Provides swagger interface.
 *
 * @return {@link Docket}
 */
@Bean
public Docket swagger() {
    return new Docket(DocumentationType.SWAGGER_2).select().apis(
            RequestHandlerSelectors.withClassAnnotation(RequestMapping.class))
            .paths(SWAGGER_PATHS)
            .build().pathMapping(this.swaggerPathMapping).apiInfo(this.apiInfo())
            .securitySchemes(Arrays.asList(this.securitySchema()))
            .securityContexts(Arrays.asList(this.securityContext()));
}

/**
 * Provides API information.
 *
 * @return {@link ApiInfo}
 */
private ApiInfo apiInfo() {
    final ApiInfo apiInfo = new ApiInfo(this.apiInfoTitle, this.apiInfoDescription, "0.0.1", null,
            new Contact("Phoenix Team", null, "phoenix-web@example.com"), null, null);
    return apiInfo;
}

public static final String securitySchemaOAuth2 = "oauth2schema";

public static final String authorizationScopeGlobal = "phoenix";

public static final String authorizationScopeGlobalDesc = "accessEverything";

private OAuth securitySchema() {
    final AuthorizationScope authorizationScope =
            new AuthorizationScope(authorizationScopeGlobal, authorizationScopeGlobal);
    final LoginEndpoint loginEndpoint = new LoginEndpoint(this.authorizationUri);
    final GrantType grantType = new ImplicitGrant(loginEndpoint, "access_token");
    return new OAuth(securitySchemaOAuth2, Arrays.asList(authorizationScope), Arrays.asList(grantType));
}

private SecurityContext securityContext() {
    return SecurityContext.builder()
            .securityReferences(this.defaultAuth())
            .forPaths(SWAGGER_PATHS)
            .build();
}

private List<SecurityReference> defaultAuth() {
    final AuthorizationScope authorizationScope =
            new AuthorizationScope(authorizationScopeGlobal, authorizationScopeGlobalDesc);
    final AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
    authorizationScopes[0] = authorizationScope;
    return Arrays.asList(
            new SecurityReference(securitySchemaOAuth2, authorizationScopes));
}
```

**Comment by dilipkrish** [comment] 2016-10-21 14:27
I think you're missing a [security configuration bean #19](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot).

**Comment by martin3361** [comment] 2016-10-24 08:12
I added this as an addition to the code above, still no client_id in the URL

	@Bean
	public SecurityConfiguration security() {
		return new SecurityConfiguration(
				"Phoenix", null, "realm", null, null, ApiKeyVehicle.HEADER, "api_key", ",");
	}

**Comment by pricelee** [comment] 2016-10-25 03:58
me too , client_id undefined

**Comment by pricelee** [comment] 2016-10-25 04:32
/swagger-resources/configuration/security  
url body is

{"clientId":"restapi-client","clientSecret":"","realm":"clipper","appName":"clipperapi","apiKey":"apikey","apiKeyVehicle":"header","scopeSeparator":",","apiKeyName":"api_key"}

**Comment by pricelee** [comment] 2016-10-25 05:40
i used  springfox-swagger2 and springfox-swagger-ui  2.6.0 version

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.0</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.0</version>
		</dependency>

**Comment by dilipkrish** [comment] 2016-10-25 15:08
My guess would be make sure you reload your swagger-ui and see if it fixes your problem. Clearly `.../swagger-resources/configuration/security` has the right values. Also I verified that it works in [the demos](https://github.com/springfox/springfox-demos).

**Comment by pricelee** [comment] 2016-10-26 05:14
It is not a problem by reload . 
I guess that bug on springfox-swagger-ui 2.6  version.

**Comment by dilipkrish** [comment] 2016-10-26 05:16
Are u saying you're still seeing the bug? Or is it fixed by reloading the page?

**Comment by pricelee** [comment] 2016-10-26 09:36
i mean ,
i still seeing the bug and not fixed by reloading

**Comment by dilipkrish** [comment] 2016-10-26 14:37
Could you share a repository that replicates the issue so I can investigate?

**Comment by pricelee** [comment] 2016-10-26 15:42
I found the cause of the problem.
springfox.js  68  line 

 function oAuthIsDefined(security) {
      return security.clientId
          && security.clientSecret
          && security.appName
          && security.realm;
    }
    function initializeSpringfox() {
      var security = {};
      window.springfox.securityConfig(function(data) {
        security = data;
        addApiKeyAuthorization(security);
        if (typeof initOAuth == "function" && oAuthIsDefined(security)) {
          initOAuth(security);
        }
      });
    }
  });


The only run initOAuth function  if security data is all not empty;

i think Require modification;

reference
https://tools.ietf.org/html/rfc6749#section-2.3

**Comment by dilipkrish** [comment] 2016-10-26 19:25
@pricelee Not sure what the fix is... swagger ui does not implement oauth2 completely. Perhaps you can submit a PR with a suggested fix. [The demos](https://github.com/springfox/springfox-demos) are here so that you can play with your authentication scenario.

**Comment by dmzaytsev** [comment] 2017-01-07 16:11
@dilipkrish I facing the same issue on 2.6.1
the implicit flow doesn't work properly
right as in the ticket description `&realm=undefined&client_id=undefined`

SecurityConfiguration bean defined as
```
@Bean
  public SecurityConfiguration securityInfo() {
    return new SecurityConfiguration(
      "test-api-swagger", "",
      "public", "api-auth-example", "", ApiKeyVehicle.HEADER, "apiKey", ",");
  }
```

**Comment by mmsinclair** [comment] 2017-01-20 17:29
@dmzaytsev the problem is in this method:

```
function oAuthIsDefined(security) {
      return security.clientId
          && security.clientSecret
          && security.appName
          && security.realm;
    }
```

I could workaround it by making sure all of those were set in the `SecurityConfiguration` bean:

```
    @Bean
    public SecurityConfiguration security() {
        return new SecurityConfiguration(
                "my-client-id", "foo", "foo", "foo", "foo", ApiKeyVehicle.HEADER, "api_key", ",");
    }
```

See #1593 for a proposed fix.

**Comment by dmzaytsev** [comment] 2017-01-20 17:34
I will try,  thank you

пт, 20 янв. 2017 г., 22:29 Mark Sinclair <notifications@github.com>:

**Comment by dilipkrish** [comment] 2017-03-20 01:06
This should be solved.

**Closed** 2017-03-20 01:06 UTC
Labels: question
