### ISSUE TITLE
Duplicate class names across packages in ResponseClass not rendered

### ISSUE THREAD

**Issue by ssrini** [springfox/springfox#1192] opened 2016-02-27 03:19 UTC
I have multiple APIs and multiple response objects.  In most cases the names of the Response objects are the same but are in different packages (a package per API).  

For e.g there are multiple User classes .. API1 is com.xyz.apione.User and API2 is com.xyz.apitwo.User
The generated docs are all pointing to a single class (either from apione or apitwo) and incorrect.

Is a fix in the pipeline? Is there a workaround while we wait for a fix? This is a more or less a blocker for me as the generated docs indicate wrong responses and we cannot use the generated docs unless we get a fix or a workaround for this.

Request assistance / help to get around this.

Note: 
I did see an earlier issue (listed in 2013) for duplicate classes in parameters but don't see any activity.  Not sure if these are related

**Comment by dilipkrish** [comment] 2016-02-28 21:15
Closing this is a duplicate of #182 

Fixing this is a bit involved and there has been a few starts and attempts at doing it. At the moment its not scheduled to be fixed until the next minor release which is in June.

**Closed by dilipkrish** 2016-02-28 21:15 UTC
Labels: duplicate
