### ISSUE TITLE
@JsonUnwrapped response is not shown correct at ui

### ISSUE THREAD

**Issue by MaximKislekov** [springfox/springfox#1760] opened 2017-04-07 12:22 UTC
I am using springfox-swagger-ui and springfox-swagger2 version 2.6.1.
When I am specify my response with @JsonUnwrapped entity in @ApiResponse it shown incorrect at swagger-ui.

Actual:
```
{
"fieldA": 0,
"innerClass":{
    "fieldB":0,
    "fieldC":0
    }
}
```

While expected:
```
{
"fieldA":0,
"fieldB":0,
"fieldC":0
}
```

We are using spring-boot and lombok if it can make any difference.

Thanks, waiting for your response.

**Comment by dilipkrish** [comment] 2017-04-12 11:36
This is a duplicate of #1740

**Closed by dilipkrish** 2017-04-12 11:36 UTC
Labels: duplicate, question
