### ISSUE TITLE
Why PlaceholderResolver's ignoreUnresolvablePlaceholders is set as true?

### ISSUE THREAD

**Issue by cenkakin** [springfox/springfox#799] opened 2015-06-16 21:02 UTC
Hi,

As you know, after the version 2.0, springfox is added to new placeholderResolver which is set ignoreUnresolvablePlaceholders as true (see #667). It prevents my application to throw exception when it is needed. Actually, I don't understand why you needed this change. Can you please clarify me about that?

Moreover, I think auto configuration coming from springfox shouldn't change the default behaviour of the application configuration. Maybe you can create this bean conditionally, since spring boot has already auto configuration for this (org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration)

Thanks in advance!

**Comment by dilipkrish** [comment] 2015-06-16 22:19
The reason we introduced that was because we need to be able to configure [properties with default values](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L63). 

Keep in mind that springfox can be used outside the context of springboot. Do you have any suggestions to solve that problem? Would love a PR if you do.

**Comment by cemo** [comment] 2015-06-17 14:16
Hey @dilipkrish I am a colleague of @cenkakin. I think that correct behaviour should investigate existing beans and should not register another `PropertyPlaceholderAutoConfiguration` in case an existing bean.

The natural way of Spring Boot would be using `@ConditionalOnMissingBean` but this is not valid for SpringFox due to not depending Spring Boot.

I am not considering to duplicate all existing implementation of `@ConditionalOnBean`. I would rather implement  '@ConditionalOnMissingBean' with limited capabilities or '@ConditionalOnMissingPropertyPlaceholderAutoConfiguration'.

**Comment by dilipkrish** [comment] 2015-06-17 14:30
@cenkakin That seems reasonable, just that I don't have the bandwidth to work on it. Would be awesome if one of you could submit a PR.

**Comment by sdoeringNew** [comment] 2017-11-23 16:08
I can confirm the bug for v2.5.0. But it can't confirm it in v2.7.0 anymore.

Was it resolved with v2.7.0?

**Comment by dilipkrish** [comment] 2017-11-26 15:48
This has been fixed in 2.7.0. So yes it was.

**Closed** 2017-11-26 15:48 UTC
Labels: feature, help wanted
