### ISSUE TITLE
Swagger shows wrong id field using Spring Data Rest

### ISSUE THREAD

**Issue by drenda** [springfox/springfox#1906] opened 2017-07-08 09:40 UTC
I tried to write in StackOverflow before write here, but unfortunately noone came up with the solution or an explanation, so I'm not sure if this is a bug. For sure is something strange.
The [link to the question is this](https://stackoverflow.com/questions/44735101/swagger-shows-wrong-id-field-using-spring-data-rest).

I'm using Spring Boot + Spring DATA REST and Swagger (Springfox 2.7.0). Spring DATA REST follows HATEOAS principles, so id field should never be present in return resources. In GET methods this works fine but in POST methods the form show an id parameter I don't understand where it comes from.

This is the screenshot of the Swagger ui. Like you see, the form contains an id parameter of type path that is not present in the model definition.

I'm sure it is not needed, in fact doing a request via Postman, it works without set id param. Also in swagger everything works fine, filling id param with a random value.

**Comment by dilipkrish** [comment] 2017-07-09 16:59
Closing this as a duplicate of #1839 (which is fixed).

**Closed by dilipkrish** 2017-07-09 16:59 UTC
Labels: bug, duplicate, in progress
