### ISSUE TITLE
swagger-ui redirects to petstore

### ISSUE THREAD

**Issue by omayevskiy** [springfox/springfox#744] opened 2015-05-14 18:17 UTC
GIVEN
```
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.0.0</version>
        </dependency>
```
ACTUAL

After I navigate to one of my controllers using the swagger ui navigation to an url like:

http://localhost:8080/swagger-ui.html#!/my-controller/doSomethingUsingPOST

If reloading the page swagger-ui shows me the example petstore documentation.

EXPECTED

After reloading I still see the documentation of my-controller and I never see the example petstore project in my projects docs.

**Comment by dilipkrish** [comment] 2015-05-15 03:24
Closing this as a duplicate of #713. Once we release 2.0.1 this should be fixed

**Closed by dilipkrish** 2015-05-15 03:24 UTC
