### ISSUE TITLE
404 when for snapshot version of springfox-swagger-ui 3.0.0-SNAPSHOT 

### ISSUE THREAD

**Issue by KamilJedrzejuk** [springfox/springfox#3360] opened 2020-07-01 22:15 UTC
Hello I am getting a 404 while access the swagger UI ...
What's the problem How Can I resolve issue?
![image](https://user-images.githubusercontent.com/10248783/86296498-32b20600-bbf9-11ea-9901-45194134bfef.png)

**Comment by dilipkrish** [comment] 2020-07-01 22:21
Yeah it has moved, which is probably why .. try hitting the website at `/swagger-ui/` or `/swagger-ui/index.html` instead

**Comment by KamilJedrzejuk** [comment] 2020-07-02 09:40
IT doesnt work

**Comment by dilipkrish** [comment] 2020-07-02 11:29
thats as much as I can help with the information provided. If you can share you repo or provide steps to reproduce that can greatly help me solve your issue.

**Comment by akshayjain7983** [comment] 2020-07-02 11:39
Hi Dilip,
I too faced same issue and after looking at your code in master figured out myself that it has been moved to /swagger-ui/. However I have a bigger concern around the timeline of actual release version of 3.0.0 because with SNAPSHOTS it is very risky for us and can break any day should you guys move it again or make any change which is not backward compatible. So if you can throw some light on timelines for release version of 3.0.0 then it will be helpful.

**Comment by dilipkrish** [comment] 2020-07-02 13:15
Plan is to release early next week.

**Comment by akshayjain7983** [comment] 2020-07-02 14:30
That is good to know. Thanks Dilip for prompt reply.

And kudos to you and whole team for making api developer's life easy. You
guys have done exemplary service to community.

Much appreciated !!

**Comment by KamilJedrzejuk** [comment] 2020-07-02 16:03
![image](https://user-images.githubusercontent.com/10248783/86381301-77877c80-bc8d-11ea-9e9c-4bad1d22fad4.png)
![image](https://user-images.githubusercontent.com/10248783/86381352-88d08900-bc8d-11ea-812a-81d77f00ac25.png)
What is the correct url?

**Comment by gilams** [comment] 2020-07-02 17:37
God!!!!!!!!!! I wasted whole day trying to figure out what was broken....
Does anyone figured out what is the new URL?

**Comment by KamilJedrzejuk** [comment] 2020-07-02 20:24
URL is Shrouded in mystery

**Comment by dilipkrish** [comment] 2020-07-03 01:24
Sorry about that, it was a breaking change/fix to the swagger-ui module. First off. If you're using 3.0.0 snapshot and using spring boot, Please [follow these instructions](https://github.com/springfox/springfox#migrating-from-earlier-snapshot). The url should be available @ `[/context-path]/swagger-ui/index.html`

**Comment by KamilJedrzejuk** [comment] 2020-07-03 09:20
By default, Spring boot applications are accessed by context path “/” which is default. 
![image](https://user-images.githubusercontent.com/10248783/86454244-4061ab80-bd1f-11ea-9520-07c06f2bc9ac.png)

**Comment by dilipkrish** [comment] 2020-07-03 10:09
Can u share what you’ve tried @KamilJedrzejuk?  It should work if everything is auto configured.

**Comment by KamilJedrzejuk** [comment] 2020-07-03 11:01
What I should do? Please provide me a config. I've tried all ways, with @EnableSwagger2WebMvc and also without ...

**Comment by gilams** [comment] 2020-07-03 11:04
Hi Kamil, are you using spring boot?

**Comment by gilams** [comment] 2020-07-03 11:10
I did the following:
1. I configured the pom, as you did above (i added data-rest, dont know if I can remove it)
2. I removed all EnableSwagger2WebMvc or EnableSwagger2WebFlux
3. Run Maven  with Clean and Install targets

then I was able to access the ui via host:port/swagger-ui/

**Comment by KamilJedrzejuk** [comment] 2020-07-03 11:15
I am using Spring boot with Spring Sleuth and Feign I've removed also @EnableSwagger2WebMvc After clean install
![image](https://user-images.githubusercontent.com/10248783/86464198-465f8880-bd2f-11ea-97fa-d1811bdf7612.png)
Thank You :)

**Comment by akshayjain7983** [comment] 2020-07-03 11:53
Hi Dilip,

I was trying to import OpenAPI docs generated by swagger into Postman 
app using /v3/api-docs but Postman complains of format error. Is there 
something to look at your end for this?

Regards,

AkshayJain

**Comment by dilipkrish** [comment] 2020-07-03 12:47
Thank you @gilams for chiming in to help! 

@akshayjain7983 Please create a new issue with your request mapping that post man is complaining about, I dont want to muddy this issue with _other_ issues you may be finding. Also please paste your api specification in `http://editor.swagger.io/` to verify there is actually a problem with the generated spec. It could be a postman issue too.

**Comment by akshayjain7983** [comment] 2020-07-03 13:02
Thanks Dilip. Sorry about posting here. Will be careful in future.

Regards,

AkshayJain

**Comment by ogerardin** [comment] 2020-07-06 15:00
I also had the dreaded 404 after the latest snapshot. I followed the [migration guide](https://github.com/springfox/springfox#migrating-from-earlier-snapshot) and was able to make it work, with a few twists:

- the migration guide doesn't make it clear that when you're migrating from an earlier snapshot you must remove all existing dependencies to springfox-* modules (not just springfox-swagger2) and replace them with springfox-boot-starter
- springfox-spring-web has an implicit dependency on spring-plugin-core 2.0.0.RELEASE... I had to add it explicitly otherwise my app would not start saying that method "PluginRegistry.getPluginOrDefaultFor" did not exist

**Comment by andrew-property-xyz** [comment] 2020-07-08 11:18
Following on from comment I left on duplicate issue #3362, I have now tried the following:

> FYI - my app is Spring Boot WebFlux using Spring Boot 2.2.4.RELEASE. I'll try with 2.3.1 (the version used in boot-webflux demo) later. The background is that my app was working quite happily with Springfox 3.0.0-SNAPSHOT (original dependencies not the springfox-boot-starter) and then, about 2-3 weeks ago I noticed that I suddenly had no swagger-ui but still had the API docs. However, I only noticed this morning that the API docs were actually broken and unusable.

* As per @ogerardin, removed all previous springfox-xxx dependencies and replaced with single dependency on springfox-boot-starter (3.0.0-SNAPSHOT)
* Removed the `@EnableSwagger2WebFlux` annotation
* Did _not_ need explicit dependency on spring-plugin-core 2.0.0.RELEASE as my app starts fine without it and whether I had it or not made no difference to the outcome
* App started but absolutely no sign of Springfox initialising or working at all. No swagger-ui.html anywhere (even at /swagger-ui/) and no docs. Basically Springfox has just not initialised at all.

I then, based on a hunch, added the `@EnableSwagger2WebFlux` annotation back and restarted... hey presto, I can see Springfox doing stuff and I can now see the API docs but still no swagger-ui.

I thought about trying 2.10.5 or 2.10.4 but Maven simply could not find them (in either jcenter repo) so got nowhere with that (and I suspect, like 2.9.2, they don't support WebFlux).

FYI - my background is that my app was working quite happily with Springfox 3.0.0-SNAPSHOT (original dependencies not the springfox-boot-starter) and then, about 2-3 weeks ago I noticed that I suddenly had no swagger-ui but still had the API docs. However, I only noticed this morning that the API docs were actually broken and unusable.

Next steps:
* I'll try upgrading Spring Boot to 2.3.1 (or later) release and see if that helps, or
* I'll try and find the 'release' of 3.0.0-SNAPSHOT that actually worked for me and set it as a 'provided' dependency, or
* I'll ditch Springfox altogether and try Spring REST Docs, or
* I'll become a hermit so I don't inflict my insane ramblings on others

Any help/hints would be greatly appreciated.

**Comment by dilipkrish** [comment] 2020-07-08 11:30
@andrew-property-xyz Couple of things with the `3.0.0-SNAPSHOT`
- it supports boot 2.2.x and above
- in 3.0 I turned down the logging to debug (so you may not see any activity). Turning it up to debug, should get u to see activity
- Im not sure what the `@EnableSwagger2WebFlux` is doing in your case. the auto configuration should've just worked for you. Are you saying that you dont see the ui when you navigate to `.../swagger-ui/`? Also the auto-configuration is the only way to get the UI to work going forward, unless you manually setup the web configurer to render the ui.

Thanks for your detailed response. Would love to know what the friction is so it can be fixed before the release.

**Comment by andrew-property-xyz** [comment] 2020-07-08 12:04
@dilipkrish Thanks for your response.

* I'm in the process of upgrading to Spring Boot 2.3.1 to see if that will make any difference - possibly not.
* I've enabled debug logging for `io.springfox` logger so will see if this gives me any clues.
* I'm not sure why auto configuration doesn't seem to work. I do not see the UI at either `.../swagger-ui.html` or `.../swagger-ui/`.
* Not seeing the UI is not my major issue, its the fact the the API docs have changed so dramatically and no longer seem to conform to OAS2. As my API is deployed behind an API gateway (Google Cloud Endpoints), this is a massive issue.

Let me do some more digging and come back with any further findings.

**Comment by dilipkrish** [comment] 2020-07-08 12:33
I’d also recommend changing your docket documentation type to OAS_30 and use `@EnableOpenApi ` instead. Also I suspect you have a bean that’s causing auto configuration to not work.

**Comment by ogerardin** [comment] 2020-07-08 14:41
@andrew-property-xyz 
> * I'm not sure why auto configuration doesn't seem to work. I do not see the UI at either `.../swagger-ui.html` or `.../swagger-ui/`.

Are you sure you are using `swagger-ui/` not `swagger-ui`? It will **NOT** work if you omit the trailing "/"!

**Comment by andrew-property-xyz** [comment] 2020-07-08 15:02
@ogerardin Thanks. Yes, I was using `/swagger-ui/`. It was not working.

@dilipkrish 

OAS3 is not an option - it is not yet supported by Google Endpoints, otherwise, yes, I would look at that route.

Ok. I don't know why but I do now have this working (up to a point). I've upgraded to Spring Boot 2.3.1 and made some minor fixes to global error handling that were required and auto-configuration is now working and I can now see the Swagger UI. It seems odd to me that the Spring Boot upgrade resolved the issue (I'm not convinced that alone is the reason) but its the only significant change I made.

There is still a problem, however... Other than `@RequestMapping`, `@PostMapping`, etc. annotations to define the operation paths, I almost exclusively use the legacy Swagger annotations to define the API. So, in reality, other than the reappearance of the Swagger UI, I still have the same issue which is that none of my `@ApiImplicitParam` annotations are being processed (it seems).

The pattern of all my handlers is something like this:

```
    @PostMapping(value = "/access-request", consumes = {MediaType.APPLICATION_JSON_VALUE})
    @ApiOperation(value = "${AdminHandler.submitAccessRequest.value}", nickname = "submitAccessRequest")
    @ApiImplicitParams({
            @ApiImplicitParam(name = "body", value = "${AdminHandler.submitAccessRequest.request.value}", required = true,
                    dataType = "AccessRequest", paramType = "body")
    })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Request successfully submitted."),
            @ApiResponse(code = 400, message = "Invalid request - a required element of the submission was not provided."),
            @ApiResponse(code = 500, message = "Request submission failed - check system logs."),
    })
    @GoogleEndpoint
    public Mono<ServerResponse> submitAccessRequest(ServerRequest request) {
        Mono<AccessRequest> requestMono = handleRequest(request);

        return defaultWriteResponse(requestMono);
    }
```

All of the Swagger annotations above appear to be processed ok, except `@ApiImplicitParam` (or perhaps it is being processed but not interpreted correctly). The `AccessRequest` model definition does exist and is correct so it's not down to that being missing... _hold that thought_

Ok, have just realised that the annotation is definitely being processed because I can see the parameter description (from `value` attribute) in the UI. If I change `dataType = "AccessRequest"` to `dataTypeClass = AccessRequest.class`, it works.

Let me fix that up for all my handlers and see what it looks like. I'll report back. Thank you for your hints and patience.

**Comment by andrew-property-xyz** [comment] 2020-07-08 16:01
@dilipkrish An update:

I had to replace all `dataType = ...` with `dataTypeClass = ...` even for primitive types (so `dataType = "double"` had to be changed to `dataTypeClass = Double.class`.

The only issue I can now see is that the `description` attribute of `@ResponseHeader` annotation is not being picked up (it was before). So, if I have:

    @ResponseHeader(name = HEADER_PAGE_SIZE, response = Integer.class, description = "Number of results per page")

The description no longer appears in the UI. There is no `value` attribute for this annotation so not sure how to resolve this other than implementing a custom extension. Any idea why this is no longer being picked up?

The real test will be deploying the specification doc to the Google Cloud Endpoint Service - its validation is quite strict.

**Comment by dilipkrish** [comment] 2020-07-08 17:05
Thanks for reporting back ... I'll look at what's going on with that. Im still curious why swagger-ui isn't working for you :thinking:

**Comment by andrew-property-xyz** [comment] 2020-07-08 17:19
It is working ok now but not sure why it wasn't in the first place - ah, it would have been because the auto configuration wasn't working and I did not have manual renderer config in place. However, as you say, not sure why auto configuration was not working initially but it is now.

**Comment by dilipkrish** [comment] 2020-07-08 17:45
Closing this issue since the original issue has been addressed.

**Closed by dilipkrish** 2020-07-08 17:45 UTC
Labels: question

**Comment by jamesmedice** [comment] 2020-10-28 19:43
> I did the following:
> 
> 1. I configured the pom, as you did above (i added data-rest, dont know if I can remove it)
> 2. I removed all EnableSwagger2WebMvc and EnableSwagger2WebFlux
> 3. Run Maven  with Clean and Install targets
> 
> then I was able to access the ui via host:port/swagger-ui/

**Comment by kangqiwang** [comment] 2020-11-02 15:31
thanks, I spent a half day to find out the problem in my project. after comment springfox-swagger2 and springfox-swagger-ui, it works now
