### ISSUE TITLE
How to set data type of response?

### ISSUE THREAD

**Issue by E006840** [springfox/springfox#1175] opened 2016-02-15 19:08 UTC
I am new to springfox. I have multiple RESTFUL services share the same response data structure  like OaResponse below. In the item list, the object structure can be completely different given the different REST route. In swagger-ui.html, I only see the same response without details of different item object. It will make the API documentation not much useful. Do you know how to fix it?

```java
public class OaResponse
{
    
    private List<? extends Object> items;
    private List<OaError> errors;
    
    
    /**
     * @return the items
     */
    public List getItems()
    {
        return items;
    }

    /**
     * @param items the items to set
     */
    public void setItems(List items)
    {
        this.items = items;
    }


    /**
     * @return the errors
     */
    public List<OaError> getErrors()
    {
        return errors;
    }

    /**
     * @param errors the errors to set
     */
    public void setErrors(List<OaError> errors)
    {
        this.errors = errors;
    }
}
```
Swagger API documentation always shows:
```json
{
  "count": 0,
  "errorCount": 0,
  "errors": [
    {}
  ],
  "items": [
    {}
  ]
}
```

**Comment by dilipkrish** [comment] 2016-02-16 14:36
Your generic `OaResponse` doesn't have enough information to be useful to generate contracts and schemas. This is because there is no information on what type the list of items is. You might have better success with the following class...

```java
public class  OaResponse<T extends Object>
{

    private List<T> items;
    private List<OaError> errors;


    /**
     * @return the items
     */
    public List<T> getItems()
    {
        return items;
    }

    /**
     * @param items the items to set
     */
    public void setItems(List<T> items)
    {
        this.items = items;
    }


    /**
     * @return the errors
     */
    public List<OaError> getErrors()
    {
        return errors;
    }

    /**
     * @param errors the errors to set
     */
    public void setErrors(List<OaError> errors)
    {
        this.errors = errors;
    }
}
public class <T extends Object> OaResponse<T>
{

    private List<T> items;
    private List<OaError> errors;


    /**
     * @return the items
     */
    public List<T> getItems()
    {
        return items;
    }

    /**
     * @param items the items to set
     */
    public void setItems(List<T> items)
    {
        this.items = items;
    }


    /**
     * @return the errors
     */
    public List<OaError> getErrors()
    {
        return errors;
    }

    /**
     * @param errors the errors to set
     */
    public void setErrors(List<OaError> errors)
    {
        this.errors = errors;
    }
}

// ... and then using it like so
@RequestMapping
OaResponse<MyObjecT> process(...) {
...
}
```

**Comment by E006840** [comment] 2016-02-18 00:54
I changed the code as you suggested. I still get the same result without details. Do you have any other way to make it work?

**Comment by dilipkrish** [comment] 2016-02-18 01:03
No sure. Can u share your code or reproduce the issue using the [springfox-demos](https://github.com/springfox/springfox-demos) application

**Comment by E006840** [comment] 2016-02-18 14:53
I cleaned up some of my code. Now it seems they can recognize the data type in the Response object. Thanks!

Meanwhile, I get another issue. Since our application is using a lot of legacy code. When an object has two overriding set method setDateOfBirth like below, springfox will throw exception. 

public class Role implements Serializable
{
    private GregorianCalendar dateOfBirth;
    

    public GregorianCalendar getDateOfBirth()
    {
        return dateOfBirth;
    }
    
    public void setDateOfBirth(GregorianCalendar newDateOfBirth)
    {
        dateOfBirth = newDateOfBirth;
    }

    public void setDateOfBirth(String newDateOfBirth)
    {
        if (newDateOfBirth != null)
        {
            StringTokenizer token = new StringTokenizer(newDateOfBirth, "/");
            int month = Integer.parseInt(token.nextToken());
            int day = Integer.parseInt(token.nextToken());
            int year = Integer.parseInt(token.nextToken());

            dateOfBirth = new GregorianCalendar(year, (month - 1), day);
        }

    }
}

The error I get is below. 

Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Conflicting setter definitions for property "dateOfBirth": com.common.Role#setDateOfBirth(1 params) vs com.common.Role#setDateOfBirth(1 params)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at springfox.documentation.schema.CachingModelDependencyProvider.dependentModels(CachingModelDependencyProvider.java:55)
	at springfox.documentation.schema.DefaultModelProvider.dependencies(DefaultModelProvider.java:113)
	at springfox.documentation.schema.CachingModelProvider.dependencies(CachingModelProvider.java:61)
	at springfox.documentation.spring.web.scanners.ApiModelReader.populateDependencies(ApiModelReader.java:132)
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:76)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:88)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:69)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:87)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:1686)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:414)
	... 57 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Conflicting setter definitions for property "dateOfBirth": com.common.Role#setDateOfBirth(1 params) vs com.common.Role.Role#setDateOfBirth(1 params)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at springfox.documentation.schema.property.CachingModelPropertiesProvider.propertiesFor(CachingModelPropertiesProvider.java:59)
	at springfox.documentation.schema.DefaultModelDependencyProvider.propertiesFor(DefaultModelDependencyProvider.java:187)
	at springfox.documentation.schema.DefaultModelDependencyProvider.nonTrivialProperties(DefaultModelDependencyProvider.java:135)
	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:124)
	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:103)
	at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:153)
	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:129)
	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:103)
	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedTypeParameters(DefaultModelDependencyProvider.java:113)
	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:102)
	at springfox.documentation.schema.DefaultModelDependencyProvider.dependentModels(DefaultModelDependencyProvider.java:65)
	at springfox.documentation.schema.CachingModelDependencyProvider$1.load(CachingModelDependencyProvider.java:47)
	at springfox.documentation.schema.CachingModelDependencyProvider$1.load(CachingModelDependencyProvider.java:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 82 more
Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property "dateOfBirth": com.common.Role#setDateOfBirth(1 params) vs com.common.Role#setDateOfBirth(1 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:222)
	at springfox.documentation.schema.Annotations.tryGetSetterAnnotation(Annotations.java:74)
	at springfox.documentation.schema.Annotations.findPropertyAnnotation(Annotations.java:48)
	at springfox.documentation.swagger.schema.ApiModelPropertyPropertyBuilder.apply(ApiModelPropertyPropertyBuilder.java:45)
	at springfox.documentation.schema.plugins.SchemaPluginsManager.property(SchemaPluginsManager.java:51)
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.beanModelProperty(OptimizedModelPropertiesProvider.java:260)
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.access$200(OptimizedModelPropertiesProvider.java:76)
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$1.apply(OptimizedModelPropertiesProvider.java:141)
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$1.apply(OptimizedModelPropertiesProvider.java:133)
	at com.google.common.base.Present.transform(Present.java:71)
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.candidateProperties(OptimizedModelPropertiesProvider.java:188)
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.propertiesFor(OptimizedModelPropertiesProvider.java:123)
	at springfox.documentation.schema.property.CachingModelPropertiesProvider$1.load(CachingModelPropertiesProvider.java:52)
	at springfox.documentation.schema.property.CachingModelPropertiesProvider$1.load(CachingModelPropertiesProvider.java:50)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 103 more

**Comment by dilipkrish** [comment] 2016-02-18 15:00
This issue will be fixed in the next release. In the mean while you could make sure that you hide the other setter for the GregorianCalendar property or call it `setDateOfBirthGregorianCalendar()`

**Comment by E006840** [comment] 2016-02-18 18:13
Our legacy code has a lot of the same issues. Change them may not be a case at this moment. Do you know when the next release is available?

**Comment by dilipkrish** [comment] 2016-02-18 18:29
hopefully this weekend if everything looks ok

**Comment by E006840** [comment] 2016-02-18 18:37
I am using Springfox io.springfox:springfox-swagger2:2.3.1. Please let me know the new version when it is ready. I will follow up with this issue. Thanks!

**Comment by E006840** [comment] 2016-02-22 13:40
Did we have a new release last weekend?

**Comment by dilipkrish** [comment] 2016-02-22 14:06
Not yet, discovered a but I'd like to fix before releasing

**Comment by E006840** [comment] 2016-03-02 00:16
Do you know when you will have a release to fix the issue above?

**Closed** 2016-03-03 00:45 UTC
Labels: question
