### ISSUE TITLE
Terms of Service URL mismatch

### ISSUE THREAD

**Issue by jonhines** [springfox/springfox#1425] opened 2016-07-28 16:19 UTC
- [ 2.5.0] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?
 - [ X] Bug report. 
If a specify a termsOfServiceURL in my ApiInfo, it is returned in the api-docs json structure as termsOfService:

`"info": {
"version": "0.5",
"title": "Service",
"termsOfService": "https://www.blah.com",
"contact": {
"name": "Someone",
"url": "https://www.blah.com",
"email": "some@email.com"
}
}`

But the swagger-ui code is expecting this value to be termsOfServiceURL:
https://github.com/swagger-api/swagger-ui/blob/master/src/main/template/main.handlebars#L9

ApiInfo class used to generate APIDocs:
https://gist.github.com/jonhines/71686e651bc08737ad9f4e2472626eaa

**Comment by dilipkrish** [comment] 2016-07-28 20:51
We haven't updated swagger ui to master (2.1.5). This is a duplicate of #1415

**Closed by dilipkrish** 2016-07-28 20:51 UTC
Labels: duplicate

**Comment by zhx828** [comment] 2016-10-24 21:41
I still have this issue.
swagger-annotations: 1.5.10
springfox-swagger-ui: 2.6.0
springfox-swagger2: 2.6.0

**Comment by dilipkrish** [comment] 2016-10-25 15:28
What you see when you look at the api-docs `/v2/api-docs`? If that looks correct, then its an issue with swagger-ui using a cached version.

**Comment by zhx828** [comment] 2016-10-25 15:34
It returns termsOfService

**Comment by dilipkrish** [comment] 2016-10-25 15:35
Then try clearing your browser cache or force reloading resources so that you have the latest swagger-ui
