### ISSUE TITLE
How to disable 'example' output in models for booleans

### ISSUE THREAD

**Issue by fairct** [springfox/springfox#1964] opened 2017-08-02 22:45 UTC
Using Springfox 2.7.0, Spring boot 1.5.4.RELEASE

I'm generating swagger JSON in order to import that into the API Gateway. The model objects generated must conform to JSON Schema. 

Apparently part of that is that 'example' output is not supported. This isn't an issue because I haven't added that to any of my ApiModelProperty annotations, but 'example' output is being added to boolean member variables of my model classes.

Is there a way to disable this behavior? I tried implementing a ModelPropertyBuilderPlugin but it appears that I'm not able to modify the value.

Example JSON output:
`"isSubscriptionNeeded": {
    "type": "boolean",
    "example": false
}`

The offending getter method:
`@JsonProperty
  @DynamoDBAttribute
    @ApiModelProperty(
        required = true
    )
    public Boolean getIsSubscriptionNeeded() {
        return this.isSubscriptionNeeded;
    }`

Please let me know if I can provide anymore info. Thanks!

**Comment by dilipkrish** [comment] 2017-09-27 02:48
Not sure why this happening. Will investigate thanks for reporting

**Comment by simonamc** [comment] 2017-10-11 17:34
Yup, I'm now seeing this too.  I think the problem lies in BooleanProperty#setExample

example is defaulted to the empty string but Boolean.parseBoolean((String)example) evaluates that to false, I think the empty string needs to be treated as a special case and mapped to null.

Is there time to get this in before 2.8 is released?

**Comment by dilipkrish** [comment] 2017-10-26 10:20
There is time, because I haven't had much time recently to work on 2.8.0 unfortunately. Trying to get it out before the end of the year.

**Comment by simonamc** [comment] 2017-11-01 15:04
Would a pull request help, although as I say it's a super minor change. I don't think it impacts any of the other XxxProperty classes as they will all already map the empty string to the empty string and thus not emit an example value.

**Comment by dilipkrish** [comment] 2017-11-13 13:11
@simonamc it would absolutely help. Thank you.

**Comment by duartesantos** [comment] 2017-11-30 15:16
👍

**Comment by simonamc** [comment] 2017-12-02 11:56
Looking at this again I don't think this is an issue with Spring for, I think it's a duplicate of this Swagger issue https://github.com/swagger-api/swagger-core/issues/2484

**Comment by duartesantos** [comment] 2017-12-03 08:55
When do you think the fix will be visible in Springfox project?

**Comment by dilipkrish** [comment] 2017-12-03 20:38
@duartesantos thanks for digging that up!

**Comment by simonamc** [comment] 2017-12-04 13:06
Like I say I don't think that this is actually a bug in Springfox, swagger-core also suffers from this.  A possible workaround would be to check for Boolean properties in ```ModelMapper#mapProperty``` and set the example value to null in the case that the value was the default empty string.  Not sure how @dilipkrish would feel about that, then create another issue to back out the change if a version of swagger is released fixing the downstream issue.

**Comment by simonamc** [comment] 2017-12-05 11:13
A quick update, the fix to Swagger just got merged, but I'd guess maybe a quarter before it's available in a release.

**Comment by duartesantos** [comment] 2017-12-05 11:24
Awesome, I guess we'll have to wait then. Thanks @simonamc

**Comment by dilipkrish** [comment] 2017-12-05 12:00
@simonamc Thanks for following up!

**Comment by pbthorste** [comment] 2018-02-01 12:06
This is still an issue in Springfox 2.8.0.

The problem is that if the @ApiModelProperty annotation is used, the "example" field is by default set to an empty string - which in return gets resolved to as a boolean false for the example field in BooleanProperty.java

A (not-so-great) workaround is to not use the @ApiModelProperty annotation.

**Comment by dilipkrish** [comment] 2018-02-02 11:41
I depends on the latest swagger-core. I'll pull that in when its available @pbthorste

**Comment by fairct** [comment] 2018-02-02 15:46
Looking at swagger-core, it seems this update has been included in the 1.5.18 release, though it was just released ~11 days ago :).

**Comment by dilipkrish** [comment] 2018-02-03 21:41
@fairct not likely it would've made it to 2.8.0 :)

**Comment by nikunjundhad** [comment] 2018-02-23 07:41
Same problem for other Wrapper classes like BigDecimal, Integer. etc. setExample method try to parse empty string "" and due to this its blow up with NumberFormatExcemption

**Closed** 2018-03-08 05:52 UTC
Labels: bug, next
