### ISSUE TITLE
springfox-data-rest : @Param annotation not supported

### ISSUE THREAD

**Issue by tooms4444** [springfox/springfox#1588] opened 2016-11-30 14:40 UTC
Module: springfox-data-rest
Version: 2.6.1

@Param annotation is not supported, you have to add a **@RequestParam** one in order for the custom query to be interpreted as GET (instead of POST) and for the parameter to be named.

see http://stackoverflow.com/questions/40718680/spring-data-rest-springfox-and-jparepository-custom-finders

**Comment by dilipkrish** [comment] 2017-02-26 02:01
Closing this a duplicate of #1623

**Closed** 2017-02-26 02:01 UTC
Labels: bug, duplicate
