### ISSUE TITLE
Bug : springfox data rest not reading repo information correctly

### ISSUE THREAD

**Issue by salah3x** [springfox/springfox#2298] opened 2018-03-14 12:09 UTC
The application failed to start after importing SpringDataRestConfiguration.
## gradle dependencies :
```
compile('io.springfox:springfox-swagger2:2.8.0')
compile('io.springfox:springfox-swagger-ui:2.8.0')
compile('io.springfox:springfox-data-rest:2.8.0')
```
## Spring boot main class (2.0.0.RELEASE)
```ruby
@SpringBootApplication
@EnableSwagger2
@Import({SpringDataRestConfiguration.class})
public class DemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build();
	}
}
```
## Result
the application failed to start:
```
...
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:184) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:157) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:121) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:21) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.0.RELEASE.jar:2.0.0.RELEASE]
Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;
	at springfox.documentation.spring.data.rest.EntityServicesProvider.requestHandlers(EntityServicesProvider.java:81) ~[springfox-data-rest-2.8.0.jar:2.8.0]
...
```
##  Possible fix
Line 81 in [EntityServicesProvider](https://github.com/springfox/springfox/blob/master/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/EntityServicesProvider.java#L81) is expecting RepositoryInformation but got Optional instead.

is there any available fix ?

**Comment by jivimberg** [comment] 2018-03-16 19:21
I think this is a duplicate of #1773

**Closed** 2018-03-16 21:14 UTC

**Comment by gt-tech** [comment] 2018-04-26 17:25
I am seeing the same issue with 2.9.0 release as well

Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;

**Comment by dilipkrish** [comment] 2018-04-27 11:44
Yes, it will not be fixed until spring boot 2 support

**Comment by nebrass** [comment] 2018-05-02 19:43
I thought it will be closed by the 2.9.0 😢

**Comment by dilipkrish** [comment] 2018-05-05 15:41
@nebrass 2.9 is still running under java 6 compatibility. Supporting that would mean moving to java 8 at the very least, which would be a breaking change. It will be fixed in 3.0

**Comment by vinu** [comment] 2018-05-23 17:13
@dilipkrish any work around to get this running?

**Comment by dilipkrish** [comment] 2018-05-31 02:53
Not at the moment @vinu, sorry!

**Comment by halower** [comment] 2018-08-02 03:32
I am seeing the same issue with 2.9.2 release as well

Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;

**Comment by dilipkrish** [comment] 2018-08-04 23:35
Most likely you're using spring boot 2.0 or using a compatible version of spring data rest @halower. There is a fix coming in 3.x for that

**Comment by siyantombela** [comment] 2018-08-22 07:37
Hi there, any idea when 3.0 is releasing? @dilipkrish

**Comment by dilipkrish** [comment] 2018-08-26 16:59
Mid to late september

**Comment by ecristobal** [comment] 2018-10-10 14:03
Hi @dilipkrish, any idea when 3.0 is releasing? I'm facing this issue and I wonder to know if it will be faster to roll back to Spring Boot 1.5 or wait for Springfox 3.0.

Thank you!

**Comment by Masterxilo** [comment] 2018-11-09 13:09
Was this fixed? I am also running into

    Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation; -> [Help 1]

with spring boot 2.1.0 & swagger/springfox 2.9.2

**Comment by Masterxilo** [comment] 2018-11-09 14:19
And also with spring boot 2.1.0.RELEASE and swagger/springfox 3.0.0-SNAPSHOT which I obtained from

```
<repositories>
    <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
</repositories>
```

**Comment by dilipkrish** [comment] 2018-11-12 01:15
Spring boot 2.1.0 isnt support for sure, it barely supports 2.0 with the latest snapshot :). I hope to get to it @Masterxilo

**Comment by EdwardDrapkin** [comment] 2019-01-07 21:43
Any idea when 3.0 might have a release?  It's been months since the latest update

**Comment by carlislefox** [comment] 2019-02-11 11:26
Another month rolls by, any updates on 3.0 guys? _Please?_

**Comment by ranma2913** [comment] 2019-03-01 18:10
### Same issue Here:
`<properties>`
`  <springfox.version>2.9.2</springfox.version>`
`</properties>`
`<dependencies>`
`  <dependency>`
`      <groupId>io.springfox</groupId>`
`      <artifactId>springfox-swagger2</artifactId>`
`      <version>${springfox.version}</version>`
`  </dependency>`
`  <dependency>`
`      <groupId>io.springfox</groupId>`
`      <artifactId>springfox-data-rest</artifactId>`
`      <version>${springfox.version}</version>`
`  </dependency>`
`  <dependency>`
`      <groupId>io.springfox</groupId>`
`      <artifactId>springfox-swagger-ui</artifactId>`
`      <version>${springfox.version}</version>`
`  </dependency>`
`  <dependency>`
`      <groupId>io.springfox</groupId>`
`      <artifactId>springfox-bean-validators</artifactId>`
`      <version>${springfox.version}</version>`
`  </dependency>`
`</dependencies>`


### Startup Error Log:

>***************************
>APPLICATION FAILED TO START
>***************************
>
>Description:
>
>An attempt was made to call the method org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation; but it does not exist. Its class, org.springframework.data.repository.support.Repositories, is available from the following locations:
>
>    jar:file:/Users/jsticha/.m2/repository/org/springframework/data/spring-data-commons/2.1.5.RELEASE/spring-data-commons-2.1.5.RELEASE.jar!/org/springframework/data/repository/support/Repositories.class
>
>It was loaded from the following location:
>
>    file:/Users/jsticha/.m2/repository/org/springframework/data/spring-data-commons/2.1.5.RELEASE/spring-data-commons-2.1.5.RELEASE.jar
>
>
>Action:
>
>Correct the classpath of your application so that it contains a single, compatible version of org.springframework.data.repository.support.Repositories

**Comment by regojoyson** [comment] 2019-10-24 18:20
I upgraded spring boot from 2.1.9 to 2.1.0 now getting the below exception. 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.data.rest.core.support.UnwrappingRepositoryInvokerFactory.<init>(UnwrappingRepositoryInvokerFactory.java:57)

The following method did not exist:

    org.springframework.plugin.core.PluginRegistry.of(Ljava/util/List;)Lorg/springframework/plugin/core/PluginRegistry;

The method's class, org.springframework.plugin.core.PluginRegistry, is available from the following locations:

    jar:file:/C:/Users/regosa/.m2/repository/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar!/org/springframework/plugin/core/PluginRegistry.class

It was loaded from the following location:

    file:/C:/Users/regosa/.m2/repository/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar


Action:

Correct the classpath of your application s
```

**Comment by guptasac-git** [comment] 2020-04-04 18:07
Use 3.0.0-SNAPSHOT to resolve this
I have tested and error resolved using below.   
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
.......
This also need to require below repository to download this.
   <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
