### ISSUE TITLE
documentationPluginsBootstrapper - NoSuchMethodError

### ISSUE THREAD

**Issue by ssnmworld** [springfox/springfox#2089] opened 2017-11-04 02:56 UTC
We are upgrading the application with Spring Boot 2.0, Java 9, Spring framework 5.0.0 with Springfox 2.7.1. I am facing this error. Does it mean it is not compatible with this upgraded framework. 

<details>
	<summary>Stacktrace</summary>

```logs
ERROR [org.springframework.boot.SpringApplication] [main] [] Application startup failed
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: springfox.documentation.spi.service.contexts.RequestMappingContext.getHandlerMethod()Lorg/springframework/web/method/HandlerMethod;
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:358)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:159)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233)
	at com.tsys.enterprise.issuing.account.application.Main.main(Main.java:30)
Caused by: java.lang.NoSuchMethodError: springfox.documentation.spi.service.contexts.RequestMappingContext.getHandlerMethod()Lorg/springframework/web/method/HandlerMethod;
	at springfox.documentation.swagger.readers.operation.SwaggerOperationModelsProvider.collectFromApiOperation(SwaggerOperationModelsProvider.java:72)
	at springfox.documentation.swagger.readers.operation.SwaggerOperationModelsProvider.apply(SwaggerOperationModelsProvider.java:62)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:136)
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:63)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:88)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:95)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:183)
```
</details>

**Comment by dilipkrish** [comment] 2017-11-13 13:27
Duplicate of #1773

**Closed by dilipkrish** 2017-11-13 13:27 UTC
Labels: duplicate
