### ISSUE TITLE
ResponseMessageBuilder doesn't generate the schema definition for the responseModel

### ISSUE THREAD

**Issue by dplacinta** [springfox/springfox#741] opened 2015-05-13 18:25 UTC
I'm using the 2.0.1-SNAPSHOT version. I've got my custom plugin for generating response messages. The code looks like:
```java
  private ResponseMessage buildResponseMessage(int statusCode, String responseMessageKey, String overrideTypeName) {
    return new ResponseMessageBuilder()
      .code(statusCode)
      .message(getResourceValue(responseMessageKey))
      .responseModel(new ModelRef(overrideTypeName))
      .build();
  }
```
For the overrideTypeName I'm using a custom error class: ErrorResponse.class.getSimpleName()

The final result references the ErrorResponse object model, but there's no ErrorResponse definition in the definitions object of the resulting JSON:
An extras of it looks like:
```java
responses: {
   200: {
      description: "OK",
      schema: {
         $ref: "#/definitions/OfferList"
      }
   },
   400: {
      description: "The request was invalid. Check the parameters list and try again",
      schema: {
         $ref: "#/definitions/ErrorResponse"
      }
   },
   ...
}
```

**Comment by dilipkrish** [comment] 2015-05-13 18:52
This is a duplicate of https://github.com/springfox/springfox/issues/735. The work around is to define at least one Api operation with an ApiResponse with that response model.

**Closed by dilipkrish** 2015-05-13 18:52 UTC

**Comment by dplacinta** [comment] 2015-05-13 20:15
Great, thanks for the reply
