### ISSUE TITLE
@Api - description argument being ignored

### ISSUE THREAD

**Issue by cyberbliss** [springfox/springfox#674] opened 2015-04-14 07:39 UTC
Hi,

I'm using the latest master snapshot with Swagger2 and it appears that the description argument in the @Api annotation is being ignored when generating the json. My understanding is that the @Api annotation provides values for the tags array, with the value argument mapping to tags[n].name and the description argument mapping to tags[n].description - the value argument is being mapped correctly but not the description. Is this by design or an oversight?

Thanks... Steve

**Comment by dilipkrish** [comment] 2015-04-14 12:25
@cyberbill this is more of an artifact of how things used to work in the past. I'll look at it

**Comment by dilipkrish** [comment] 2015-04-14 18:00
Closing this as its a duplicate of #675

**Closed by dilipkrish** 2015-04-14 18:00 UTC
Labels: duplicate

**Comment by cyberbliss** [comment] 2015-04-15 07:37
Hi,

Appreciate you taking the time to investigate this. Although #675 is
related, not sure it is a duplicate. SwaggerUI uses the description field
from @Api which is something I want to take advantage of. If you can point
me in the direction of the code that deals with the @Api annotation maybe I
can investigate further?

Many thanks... Steve

**Comment by adrianbk** [comment] 2015-04-15 10:05
@cyberbliss see here: https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/ClassOrApiAnnotationResourceGrouping.java#L44-44
