### ISSUE TITLE
OperationId not unique if methods in different controllers have the same name

### ISSUE THREAD

**Issue by cbornet** [springfox/springfox#818] opened 2015-06-26 08:39 UTC
From the swagger spec, the operationId must be unique since it shall be used by generators to name the methods (eg, https://github.com/wcandillon/swagger-js-codegen puts all the methods in a single class).

I use JHipster to generate entities with CRUD controllers. The methods in the controllers all have the same names like create(), getAll(), update(), ... And in the swagger spec, operationIds named createUsingPOST, getAllUsingGET, ... are thus repeating for each controller.

I am not sure how the integration between JHipster and springfox should be done : whether JHipster should include the resource name in its methods (eg. createFoo(), getAllFoos(), ...) or if springfox should prefix the operationId with the "@Api value" in case of duplicates (eg. "operationId": "fooCreateUsingPOST", "barCreateUsingPOST"). 

@dilipkrish Do you have an opinion ?

**Comment by dilipkrish** [comment] 2015-06-26 21:04
By definition operation id is optional per swagger 2.0 spec, so JHipster or any other tool for that matter would need to be able to use some other means to generate the client methods.

Having said, that there are a couple of issues that are to provide best effort uniqueness for operations already. Closing this as a duplicate of #682

**Closed by dilipkrish** 2015-06-26 21:04 UTC
