### ISSUE TITLE
Dead circulation

### ISSUE THREAD

**Issue by evencht** [springfox/springfox#1555] opened 2016-11-01 14:11 UTC
A class named ‘Area’  in my project ：

`public class Area extends BaseDomain{
  ……
private List<Area> children;
……
}`

step1：Expanding parameter type: com.woyi.mhub.area.domain.Area
step2：Attempting to expand expandable field: children
step3：Expanding parameter type: java.util.List<com.woyi.mhub.area.domain.Area>
step4：Attempting to expand collection/array field: children

Dead circulation！

**Comment by dilipkrish** [comment] 2016-11-01 15:41
This is a duplicate of #1513. Should be fixed in 2.6.1 to be released shortly

**Closed by dilipkrish** 2016-11-01 15:41 UTC
Labels: bug, duplicate
